### ISSUE TITLE
Inference Stuck

### ISSUE THREAD

**Issue by JunMa11** [MIC-DKFZ/nnUNet#10]
Hi Fabian,

During the inference, all the data have been inferred, but the program gets stuck here.
I only use 3 data for inference, the issue occurred again.

Have you ever had this problem for LiTS?
And what does "separate z: False lowres axis None" mean?

![Capture - Copy](https://user-images.githubusercontent.com/19947331/58433939-3c2c7e80-8087-11e9-9193-f302ba768d71.PNG)

Best,
Jun

**Comment by FabianIsensee** [comment]
Hi Jun,

> And what does "separate z: False lowres axis None" mean?

This is a debug information I print for myself. nnU-Net will sometime do resampling independently for xy and z when the spacing along z is larger than the spacing in xy.

I don't think your inference is stuck to be honest. How did you detect it being stuck? Did you give it enough time to finish? Also one of your patients is really large (see that 1800,651,651 shape). This requires a LOT of RAM to resample (probably 64G or more) so make sure you run this on a large enough system. 
Also note the "This output is too large for python process-process communication" warning :-) nnU-Net puts all the resampling and saving of niftis into background processes. Python can however not communicate anything larger then 2GB (which is a stupid resitriction) which is why I save .npy files for large data and pass along the file name to the background process. These files can be easily 3GB or more, maybe this is slowing things down for you?

I have never had inference being stuck on me, so I don't know how I can help. Please let it run for longer, look out for the npy file and have a look at htop to maybe see the background process.

Best,
Fabian

**Comment by JunMa11** [comment]
Hi Fabian,

Thanks for your help very much.

> How did you detect it being stuck?

This is because all the test data have been inferred and I can access the prediction results, but the program stopped at `separate z: False lowres axis None`.

Yes, you are right.  I let the inference **run longer** (although all the data have been inferred), it costs about 5 minutes and then the program can finish correctly. 

The reason may be the large volume bacause this issue disappeared when I play with some small data.

Best,
Jun

**Comment by FabianIsensee** [comment]
Hm it should not take that long to finish. At the end of inference the main python process needs to wait for all the workers to finish. I don't know why this takes so long. If I find the time I will look into this.
Best,
Fabian
