### ISSUE TITLE
several question about model selection

### ISSUE THREAD

**Issue by jihoon3327** [MIC-DKFZ/nnUNet#1001]
Please read the following resources before posting issues:

Common questions:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_questions.md

Common Problems and their solutions:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_problems_and_solutions.md

Expected epoch times and tips on how to identify bottlenecks:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/expected_epoch_times.md

Hello Fabian,
I have a few questions about model selection.
Before that, let me introduce my database.

![image](https://user-images.githubusercontent.com/80459891/161017857-825d5cee-97ea-4681-a9e6-eae670421976.png)

As for my dataset, it is shown in the picture above. In this part, I want to ask you something.

1. In the nnUNet paper, if the resampled median size is more than four times larger than the input patch size, the cascade model is recommendation for training. Is this right?
Then, looking at the data set in the figure above, it can be seen that the resampled size (181x512x512=47,448,064 voxels) is 28.96 times larger than the input patch size (64x160x160=1,638,400 voxels). Then, it is better that i select cascade model, right?

(in nnUNet paper)
--------------------------------------------------------------------------------------------------------------

Although nnU-Net prioritizes large input patches, the patch size of the 3D full resolution U-Net is too small to capture sufficient contextual information (it only covers 1/60 of the voxels of the median image shape after resampling). This can cause misclassifications of voxels because the patches are too ‘zoomed in’, making for instance the distinction between the spleen and the liver particularly hard. The 3D U-Net cascade is designed to tackle this problem by first training a 3D U-Net on downsampled data and then refining the low-resolution segmentation output with a second U-Net that operates as full resolution.

Necessity for the U-Net Cascade is determined by the following heuristics: If the median shape of the resampled data has more than 4 times the voxels that can be processed as input patch by the 3D U-Net (with a batch size of 2), it qualifies for the U-Net Cascade and this dataset is additionally resampled to a lower resolution

---------------------------------------------------------------------------------------------------------------

2. I thought it would be right to apply the cascade model in this dataset. Also, I did training by applying the 3D_fullres model just in case. And the results are as follows.
The paper says that when the resampled size is more than four times larger than the patch size, there may be a problem of misclassification if the 3d_fullres model is applied. However, as you can see in the results below, the results of 3d_fullres look almost the same as cascade. Can you explain this part?

![image](https://user-images.githubusercontent.com/80459891/161020596-ac6db84e-c5ce-40e4-9198-7ceebf3a796e.png)

For reference, my gpu specification is "NVIDIA TITAN RTX 24G".

3. I proceeded with "3d_lowres" and "3d_cascade_fullres" models with only "all" option on training stage. You said that those models are must proceeded with 5-fold in the "3d_lowres" model to proceed "cascade" model. but i'm done with only "all" option. can you explain this?

**Comment by FabianIsensee** [comment]
Hi, thkanks for the really detailed post! It helps me a lot to give good answers when I get presented all the information I need :-)

> In the nnUNet paper, if the resampled median size is more than four times larger than the input patch size, the cascade model is recommendation for training. Is this right?
> Then, looking at the data set in the figure above, it can be seen that the resampled size (181x512x512=47,448,064 voxels) is 28.96 times larger than the input patch size (64x160x160=1,638,400 voxels). Then, it is better that i select cascade model, right?

Not necessarily. This is only an indication that the cascade COULD be needed but no guarantee that it will outperform the other configurations. That's why nnU-Net always does model selection based on cross-validation performance. 

> Can you explain this part?

Yeah again there is no guarantee, that's why `nnUNet_find_best_configuration` exists. Cascade is only needed if global (!) shape AND texture are required to do the classification (lowres lacks texture and fullres lacks global shape). You problem seems to be solvable within the patch size of the fullres configuration.

> I proceeded with "3d_lowres" and "3d_cascade_fullres" models with only "all" option on training stage. You said that those models are must proceeded with 5-fold in the "3d_lowres" model to proceed "cascade" model. but i'm done with only "all" option. can you explain this?

You should not train the cascade without having trained the 3d_lowres cross-validation. Maybe it's technically possible but it doesnt give ideal results because the predictions form the lowres stage are going to be too precise from the all training. You need the cross validation to produce realistic predictions (with errors) that the cascade can learn to correct.

Best,
Fabian
