### ISSUE TITLE
Get time to predict each test case?

### ISSUE THREAD

**Issue by ltsc256** [MIC-DKFZ/nnUNet#1041]
Hello, I wanted to show how much time can be saved by using the model. For each of the test cases, I have manual segmentation time in seconds but I cannot figure out how to get the time needed by the model. I know I can time the predict process but that will be results for all the cases together and I wanted time per case. Any guidance here?

**Comment by FabianIsensee** [comment]
I just pushed a change that will create a prediction_time.txt file in the output directory of the prediction. Note that this time is for all predicted cases, not per case!
Computing a prediction time per case is not useful because nnU-net interlaces preprocessing, prediction and segmentation export. It is much better to just take the time needed for all cases and then compute the average time per case from that
