### ISSUE TITLE
Assertion Error: If does not seem like you trained all the folds! --> But trained all folds

### ISSUE THREAD

**Issue by annewiet** [MIC-DKFZ/nnUNet#1051]
Thank you for developing and managing this great tool! I have trained nnU-Net succesfully on one dataset, but now I have created a new task and trained all the folds again for the 3d_fullres configuration (with --npz) on the MM-WHS17 challenge data. 

However, when I run nnUNet_determine_postprocessing -m 3d_fullres -t 504 or nnUNet_find_best_configuration, I get  'Assertion Error: If does not seem like you trained all the folds! Train all fold first!'

I am sure I have trained folds 0 to 4 and also checked the traininglog for each fold. What could be the issue? Thanks in advance.

**Comment by Andras1396** [comment]
HI, I trained on my custom dataset (on all folds) and when I want to get the best parameters with the following command:
`nnUNet_find_best_configuration -m 2d -t 715`
the same error occurs. I also checked that all the folds are trained. 

Thanks in advance!

**Comment by 911456451** [comment]
Maybe it's because of some problem in figure_out_what_to_submit.py .
If just want to get a result,regard less of performance,you can copy file `nnUNet_trained_models/nnUNet/3d_fullres/Task001_XXX/nnUNetTrainerV2__nnUNetPlansv2.1/fold_X/postprocessing.json` to folder `nnUNet_trained_models/nnUNet/3d_fullres/Task001_Effusions/nnUNetTrainerV2__nnUNetPlansv2.1/`,and copy file `nnUNet_trained_models/nnUNet/3d_fullres/Task001_Effusions/nnUNetTrainerV2__nnUNetPlansv2.1/fold_0/validation_raw_postprocessed/summary.json` to folder `nnUNet_trained_models/nnUNet/3d_fullres/Task001_Effusions/nnUNetTrainerV2__nnUNetPlansv2.1/cv_niftis_raw`, for me, it's OK

**Comment by FabianIsensee** [comment]
Did you maybe use a different trainer? If so then you need to specify which one. Can you also share the path of your trained model?
