### ISSUE TITLE
continue_training problems with nnUNet_train

### ISSUE THREAD

**Issue by min-star** [MIC-DKFZ/nnUNet#1099]
Hello,

Thank you so much for your work on this project, it is very amazing, i learned a lot.

I had run the command: nnUNet_train 3d_lowres  nnUNetTrainerV2 520 0 -c.but at the initial several epoches, the metric is dramaticly decresed. The reason i think maybe because during the first training time,the lr rate is decreased to 0 after 1000 epoches. when we continue training, the lr is another value, I am confused with the regular of set the continue training initial lr .could you give some suggestions? I'm looking forward your reply!

the following content is my process.png!
![progress](https://user-images.githubusercontent.com/59134868/177306806-ef4cb75f-babd-4c95-9365-acc174445494.png)

Best Wishes!

**Comment by FabianIsensee** [comment]
Hey this is a bit odd. Did you maybe also change the splits in between? (splits_final.pkl file?)
Apart form that you should not continue after changing the number of epochs because that messes with the learning rathe schedule. Please specify the correct number of epochs at the start by using a custom trainer
