### ISSUE TITLE
error in nnunet.experiment_planning.utils.split_4d

### ISSUE THREAD

**Issue by huangmozhilv** [MIC-DKFZ/nnUNet#1100]
I created my task with name of 'Task501_XXXX'. After running `nnUNet_convert_decathlon_task -i /xxx/Task501_XXXX`, an error occured as below:
![image](https://user-images.githubusercontent.com/26662685/177503729-fbbbd090-8c7a-47bd-ba16-589d89e98cd2.png)

This might be because that previously the tasks were named with 2-digit id (as suggested by `input_task_id = int(full_task_name[4:6])` so that the first underscore was the 7th character. However, the current task names are all with 3-digit id, and the first underscore is the 8th character. Therefore, I would recommend the authors to update the following codes:
1. `assert first_underscore == 6, "Input folder start with TaskXX with XX being a 3-digit id: 00, 01, 02 etc"`
to  `assert first_underscore == 7, "Input folder start with TaskXX with XX being a 3-digit id: 000, 001, 002 etc"`
2. `input_task_id = int(full_task_name[4:6])`
to `input_task_id = int(full_task_name[4:7])`
3. `task_name = full_task_name[7:]`
to `task_name = full_task_name[8:]`

**Comment by FabianIsensee** [comment]
What task did you apply this on? This needs to be applied to datasets from the original MSD only. These are called TaskXX with 2 digits and that's why the code is the way it is. If you created your own MSD task and want to convert it to nnU-Net you should adhere to MSD standards and name it with 2 digits ;-)
