### ISSUE TITLE
Patch Size in plan file is different

### ISSUE THREAD

**Issue by sbajpai2** [MIC-DKFZ/nnUNet#113]
Hi Fabian,

When i generated the plan file for a task and viewed it, I found out that the patch _size in it is different than what is written in the paper. For example: for lung dataset, below is the content of plan file:
**1: {'batch_size': 2,
   'num_pool_per_axis': [4, 5, 5],
   'patch_size': array([ 80, 160, 160]),
   'median_patient_size_in_voxels': array([252, 512, 512]),
   'current_spacing': array([1.24497998, 0.78515625, 0.78515625]),
   'original_spacing': array([1.24497998, 0.78515625, 0.78515625]),
   'do_dummy_2D_data_aug': False,
   'pool_op_kernel_sizes': [[1, 2, 2],
    [2, 2, 2],
    [2, 2, 2],
    [2, 2, 2],
    [2, 2, 2]],
   'conv_kernel_sizes': [[3, 3, 3],
    [3, 3, 3],
    [3, 3, 3],
    [3, 3, 3],
    [3, 3, 3],
    [3, 3, 3]]}}}** 

Now as per adaptations in the paper:  **Due to memory constraints, we do not increase the input patch volume beyond 128^3 voxels, but instead match the aspect ratio of the input patch size to that of the median size of the dataset in voxels**

So the patch size for lungs should be (64,128,128) because median size of the dataset is (252,512,512).

Can you please help me clarify that?

**Comment by FabianIsensee** [comment]
Hi,
you misinterpreted the statement in the paper. The patch size is not larger than 128x128x128 voxels **in total**, not per axis. 80x160x160 is less voxels than 128x128x128.
Best,
Fabian

**Comment by sbajpai2** [comment]
Hi Fabian,

Thank you so much for your reply. I have one more question.
Can you please clarify, why the patch_size generated in my plans file is different than the ones reported in the paper.
I am also getting different results than what is reported in the paper when I reproduced the results for different tasks using nnU-Net framework. 

Best,
Shivam Bajpai

**Comment by FabianIsensee** [comment]
Can you please provide additional information? What dataset? What patch
size? What results?

**Comment by sbajpai2** [comment]
I am really sorry for not specifying everything.
For example: for lung dataset, below is the content of nnunet_3d_plan file after running plan and preprocess script: 
**1: {'batch_size': 2,
'num_pool_per_axis': [4, 5, 5],
'patch_size': array([ 80, 160, 160]),
'median_patient_size_in_voxels': array([252, 512, 512]),
'current_spacing': array([1.24497998, 0.78515625, 0.78515625]),
'original_spacing': array([1.24497998, 0.78515625, 0.78515625]),
'do_dummy_2D_data_aug': False,
'pool_op_kernel_sizes': [[1, 2, 2],
[2, 2, 2],
[2, 2, 2],
[2, 2, 2],
[2, 2, 2]],
'conv_kernel_sizes': [[3, 3, 3],
[3, 3, 3],
[3, 3, 3],
[3, 3, 3],
[3, 3, 3],
[3, 3, 3]]}}}**

We can see the patch size as [ 80, 160, 160] in above plan file content. While in the paper the patch size written is [112, 128, 128] for same lung dataset. 
Also when I reproduced the results using nnU-Net for lung tumour segmentation task, I got dice score as 62.44 using 3d_Unet which is 3D_fullres. While in the paper for same 3d_Unet the dice score is 55.87.

**Comment by FabianIsensee** [comment]
Are you referring to the Medcial Segmentation Decathlon Challenge report? Then this is expected because we have updated nnU-Net in the meantime. It handles a few things differently now and gives better results (as you have observed as well).
Please have a look at this publication:
https://arxiv.org/abs/1904.08128

It describes the new, better nnU-Net.

If you still want to use the old settings I can tell you how. Just let me know.
Best,
Fabian

**Comment by FabianIsensee** [comment]
I am also wondering why you are getting patch size [ 80, 160, 160]. It should be [ 80, 192, 160]. Have you pulled from github recently?

**Comment by sbajpai2** [comment]
I have looked into this (https://arxiv.org/pdf/1809.10486.pdf) one. 
You have Table 1 in the paper denoting the input patch size.
The patch size in the plan file when i ran plan and preprocess gives me different results. And even if it is [80, 192, 160], shouldn't nnU-Net determine the same patch size as in the paper i linked.
Why am I asking about the patch size? It's because it changes the architecture layers.

I haven't pulled github recently and sure if you can help me out with the same old settings, it will be really helpful.

**Comment by sbajpai2** [comment]
Hi Fabian,

Can you please help me out with above query?

Best,
Shivam

**Comment by FabianIsensee** [comment]
Hi, apologies I am currently very busy with writing my thesis. The  paper you are referring to is the original one from the Medical Segmentation Decathlon. **The code for this was never released because we made a number of improvements between writing this initial paper and releasing the code.The paper does not give a link to this Github repo because of that.** 
This Github repo started with https://arxiv.org/abs/1904.08128v1 and has since been updated to https://arxiv.org/abs/1904.08128v2 (they are both the same arxiv link but the second paper is a much more refined version that also comes with several improvements to nnunet)
All the code for these papers is contained in the repo.
I really don't know why you insist on having the old settings if the new ones perform better.
Best,
Fabian
