### ISSUE TITLE
Anisotropic image issue (code)

### ISSUE THREAD

**Issue by 89douner** [MIC-DKFZ/nnUNet#1139]
Hi, 

I have two questions about anisotropic code.

```
has_aniso_spacing = target[worst_spacing_axis] > (self.anisotropy_threshold * max(other_spacings))
has_aniso_voxels = target_size[worst_spacing_axis] * self.anisotropy_threshold < min(other_sizes)
```
Q1. 
Paper mentioned that  "For anisotropic images (maximum axis spacing ÷ minimum axis spacing > 3)"
But, when I checked the code ('has_aniso_spacing'), there is max function.
Shouldn't the max function be changed to the min function?

Q2. Is the formular for has_aniso_voxels right?
I mean, shouldn't the code be changed as below?
```
has_aniso_voxels = min(other_sizes) * self.anisotropy_threshold > target_size[worst_spacing_axis]
```

**Comment by seziegler** [comment]
Hi @89douner , thank you for your questions and apologies for letting this issue stale for so long! 
It seems to me that you are right with Q1. In practice, it probably does not make a difference because the other two spacings are usually very similar. 
In Q2 I think the original nnunet implementation is correct. When you have a high spacing this results in smaller data. So if the size of the axis with the highest spacing multiplied by 3 (anisotropy_threshold) is still smaller than the minimum of the other sizes you have anisotropic voxels. 
Best,
Sebastian
