### ISSUE TITLE
Empty segmentation while patch predictions non empty

### ISSUE THREAD

**Issue by alexaatm** [MIC-DKFZ/nnUNet#1165]
Dear nnUNet Team,
Thank you so much for your work!

I have an issue with running inference with the Kidney Pretrained Model (Task48) on my own data -> the final segmentation is always empty (has only 0s).

Testing the same pretrained model on the Kits challenge data provides a nice segmentation.
I also visualized the patches and their prediction during inference. So for KITS data sample it looks like this:
![image](https://user-images.githubusercontent.com/37114516/190399463-930df745-642e-4d8e-9a60-b392e8fa613d.png)

But for my own data sample (also Kidney, also CT) the predictions are weird. On some of them you can see an outline of kidney, but then this gaussian overlay is always present. 
![image](https://user-images.githubusercontent.com/37114516/190399737-18ac3afd-760b-4a81-929b-a265b50355cc.png)

Then I removed the gaussian_importance_map from the function call to _internal_maybe_mirror_and_pred_3D.  And the prediction now looks  more similar to the one for the Kits data. 

![image](https://user-images.githubusercontent.com/37114516/190400346-9b84c51f-b769-4a2e-8579-7750c8e7d785.png)

But still the final prediction is empty. What could be the issue?? Are there additional requirements for the data that I am overlooking? 

P.S. I could send both data samples via email, if needed.

Would be grateful for any insight!!

Thank you!

**Comment by FabianIsensee** [comment]
HI,
please send me the examples via email and I can take a look. f.isensee AT dkfz . de
Best,
Fabian

**Comment by alexaatm** [comment]
Hello,

thank you!
I have just sent an email.

Best,
Oleksandra

**Comment by FabianIsensee** [comment]
Thanks I got it and I spent a lot of time trying to understand the problem. KiTS just doesn't work on your data for some reason. Same with the model trained on the BTCV challenge. This is curious because all the other CT datasets I have play nice with each other. I can predict BTCV -> KiTS and vice versa (when accounting for the transpose thing).

To my untrained eyes your CT looks quite different than the CTs the ohter models are trained on. This is probably the (unsatisfying) explanation for this problem -> there is some domain gap that cannot be closed out of the box.

Is there anything special about your CT images? Was an unusual kernel used to reconstruct the images? Did the patients get a funny treatment? Is it some special type of CT device?
Best,
Fabian

**Comment by alexaatm** [comment]
Hi Fabian,

Thank you so much for taking a look!

This is a contrast-enhanced CT. But no special processing has been applied that would make it so different. 
So at this point, we are pretty clueless... Will experiment more :)

Kind regards,
Oleksandra

**Comment by FabianIsensee** [comment]
Good luck and sorry I couldn't help you more!
