### ISSUE TITLE
RuntimeError: Cannot run final stage of cascade. 

### ISSUE THREAD

**Issue by maomaoaiTH** [MIC-DKFZ/nnUNet#1182]
Dear Fabian,
I just had the same problem as "Cannot run final stage of cascade #9". Do you know what caused it? Can we just start preprocess all over again?

**Comment by sten2lu** [comment]
Hi @maomaoaiTH,
does your issue with the final stage of 3d cascade still persist?
If so, please get in touch here, so that we can solve it together.

If yes, I would advise you to: 
1. upgrade to nnU-Net V2
2. preprocess the data again
3. start training the 3d_lowresolution models again
4. train the final stage of the cascade.


All necessary information for this can be found in the documentation:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/how_to_use_nnunet.md

A Guide for the migration from nnU-Net V1 to V2 can be found here:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/tldr_migration_guide_from_v1.md

If there is no further activity on this issue, it will be close on August 28th.

Best regards,
Carsten
