### ISSUE TITLE
soft dice loss , square numerator and denominator

### ISSUE THREAD

**Issue by vishnusanjayrs** [MIC-DKFZ/nnUNet#12]
def soft_dice(net_output, gt, smooth=1., smooth_in_nom=1., square_nominator=False, square_denom=False):
    axes = tuple(range(2, len(net_output.size())))
    if square_nominator:
        intersect = sum_tensor(net_output * gt, axes, keepdim=False)
    else:
        intersect = sum_tensor((net_output * gt) ** 2, axes, keepdim=False)
    if square_denom:
        denom = sum_tensor(net_output ** 2 + gt ** 2, axes, keepdim=False)
    else:
        denom = sum_tensor(net_output + gt, axes, keepdim=False)
    result = (- ((2 * intersect + smooth_in_nom) / (denom + smooth))).mean()
    return result

if square_nominator is False , the nominator is squared but its not the case with denominator ..is that intended usage ? what is the advantage in this case?

**Comment by FabianIsensee** [comment]
Wow. That's a bug. A big stupid one. Thank you so much for finding it.

At some point I have compared squared vs non-squared dice loss and found no real difference. So there is no advantage either way I think. Still this should not be the case. I will evaluate whether that makes a difference and if not I will probably rewrite the whole dice loss part because it is pretty messy anyways.

**Comment by vishnusanjayrs** [comment]
Thanks Fabian for the reply .. That's what i thought !!
