### ISSUE TITLE
Changing Network in nnUNet

### ISSUE THREAD

**Issue by Colabam** [MIC-DKFZ/nnUNet#1201]
Hello,
I know the network architecture is changeable, but I am wondering if is it possible to implement any kind of network? (for example Mask RCNN)

Best,

**Comment by Joeycho** [comment]
Hi,

in my knowledge, yes you can! You can either create your own network and fit in Trainer, one of nnUNetTrainerV2, V2... etc,  or edit GenericUNet (this one is default network architecture in nnUNet currently).

**Comment by yangqiqi** [comment]
I have the same question. I want to add maskrcnn model to nnunet. How should I start? What files need to be modified? What are the general steps?

**Comment by yangqiqi** [comment]
I refer to this: https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/extending_nnunet.md,but,I still don't know where to start?

**Comment by LEON-gittech** [comment]
maybe we can create a discord group and talk about this.

**Comment by Kobalt93** [comment]
You can change the network architecture, there are some examples of that here: [https://github.com/MIC-DKFZ/nnUNet/tree/master/nnunetv2/training/nnUNetTrainer/variants/network_architecture]
If you want to use another architecture than U-Net you have to implement it by yourself, because currently Mask RCNN is not supported.
