### ISSUE TITLE
Deep supervision with MaxPooling

### ISSUE THREAD

**Issue by SimJeg** [MIC-DKFZ/nnUNet#1226]
Hello,

The default way to perform deep supervision in `nnUNetTrainerV2.py` is to downsample the target using nearest neighbor interpolation (see `DownsampleSegForDSTransform2`). However this eventually deletes small components (e.g. small lesions in a tumor segmentation task). 

Have you experienced other settings ? For instance, use max pooling instead of average pooling such as in  `DownsampleSegForDSTransform3`? (would work for binary segmentation)

**Comment by TaWald** [comment]
Hello SimJeg,

according to Fabian he hasn't really looked into the different schemes of downsampling for deep supervision.
So your guess would be as good as anyone else's. Your observation that small lesions are affected by this is certainly true, however we would expect immeasurable differences due to it being an edge case.

This is especially true, if there are also larger lesions present, which will further decrease relevancy of the small instances. (Speaking from a DICE point of view).

If you have tried this out yourself and would provide the results here, we would certainly be interested in it and could update current schemes should it affect the performance in a significant way. 

Cheers,
Tassilo

**Comment by SimJeg** [comment]
Hello, 

I don't think I made A/B testing on this, but I used  average pooling because in my use case, detecting a lesion was much more important than having a nice delineation of it, so dice was not the main metric,

Best,
Simon

**Comment by TaWald** [comment]
nnU-Net was not really designed for the segmentation of very small instances out-of-the-box, as this currently is more of the exception than the norm. The adaptations you are proposing certainly sound reasonable but I would recommend you to check out [nnDetection](https://github.com/MIC-DKFZ/nnDetection). It is specifically designed for detection (also of small objects) and might be more suitable for the problem at hand :) 

Cheers,
Tassilo
