### ISSUE TITLE
A question about preprocess

### ISSUE THREAD

**Issue by Sissi-lu** [MIC-DKFZ/nnUNet#1289]
Hi @FabianIsensee,

Thank you for your gorgeous work on nn-Unet. I learned a lot from your work. And I found a question about its preprocess. In the published paper, it said If the dataset is anisotropic, the higher-resolution axes are first downsampled until they match the low-resolution axis/axes and only then all axes are downsampled simultaneously. (It describes after the U-Net Cascade ) 

So I don't know whether it needs when the data itself is anisotropic. Like the CT of the lung, the resolution of z-axis is not the same as the x and y-axis. In nn-Unet, I wonder whether the data is resampled to be isotropic. Or it is not necessary because the mask itself is anisotropic either.

thank you very much. I'm looking forward to hearing from you.

Best,
Sissi

**Comment by FabianIsensee** [comment]
Hey, this part only applies to the 3d_lowres configuration. That doesn't mean though that the resulting data will be isotropic because the increase in spacing is performed gradually until the GPU memory requirement is met.
So it could be the following (remember that higher spacing = lower resolution)
2 1 1
2 1.1 1.1
2 1.2 1.2
2 1.3 1.3
2 1.4 1.4 -> GPU memory requirement reached, stop here!

For other datasets (depends on image size) this may go down all the way to 
2 2 2
from which point on further downscaling would be performed simultaneously for all axes:
2.1 2.1 2.1 etc

Note that the actual steps nnU-Net makes are much smaller

**Comment by Sissi-lu** [comment]
Oh thank u for your answer. I understand what you said now. It seems that your idea is to downsample the data while making full use of GPU. And your method is to downsample the high-resolution axis,  then adjust the other axis to meet the GPU requirement. Thank u again!!

**Comment by FabianIsensee** [comment]
exactly
