### ISSUE TITLE
Way to reduce RAM usage on validation?

### ISSUE THREAD

**Issue by karllandheer** [MIC-DKFZ/nnUNet#1296]
Hello, as the title suggests is there a way to reduce RAM usage on validation? I am running nnUNet on a cloud computing platform which does not allow me access to the entirety of the available RAM on the instance (some other processes are running). I believe this is resulting in the job freezing (not crashing) at the validation step. Is there a way to reduce RAM usage at this step?

**Comment by FabianIsensee** [comment]
Unfortunately not out of the box. What is eating up all the ram is the resampling operation at the end. The softmax probabilities are resampled to the original shape and then an argmax is performed.
If you want to fiddle with the inference code you can set the order of the interpolation to 0. That will reduce RAM usage.
Best,
Fabian

**Comment by karllandheer** [comment]
Hello, I found out that it wasn't that my RAM was getting full, rather that for some reason the multiprocessing threading is causing my instance to hang (i.e., never completes). I have found by replacing starmap_async with just for loops it no longer hangs there, however there's also some parallelization in MultiThreadedAugmenter that it's still hanging on. Is there an easy way to turn multi-threading off?

**Comment by FabianIsensee** [comment]
Honestly you should probably fix your environment rather than trying to patch nnU-Net. You need multiprocessing for it to run properly.
Your message mentions something about an instance? So you are using a cloud solution? There could be documentation about multiprocessing for these kinds of settings somewhere. I am not familiar with that.
If you are using Docker, make sure to set --ipc=host when starting the container
