### ISSUE TITLE
AssertionError: Cannot do mirroring as test time augmentation when training was done without mirroring

### ISSUE THREAD

**Issue by Junye-Chen** [MIC-DKFZ/nnUNet#1326]
hello, thanks for your excellent work. 
I met a problem when I want to do a prediction on my model. Specifically, I trained my model by using
`nnUNet_train 3d_fullres nnUNetTrainerV2_noMirroring 1 4`
and predicted by
`nnUNet_predict -i /workspace2/github/nnUNetFrame/DATASET/nnUNet_raw/nnUNet_raw_data/Task001_Tooth/imagesTs/ -o /workspace2/github/nnUNetFrame/DATASET/nnUNet_raw/nnUNet_raw_data/Task001_Tooth/inferTs -t 1 -m 3d_fullres -f 4 -tr nnUNetTrainerV2_noMirroring`

However, when running the prediction, the error shown below occurred and the computer got stuck.
I have checked all the memory and they are available enough.
```
using preprocessor GenericPreprocessor
Traceback (most recent call last):
  File "/workspace2/conda/conda_envs/nndet/bin/nnUNet_predict", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_predict')())
  File "/workspace2/github/nnUNetFrame/nnUNet/nnunet/inference/predict_simple.py", line 219, in main
    predict_from_folder(model_folder_name, input_folder, output_folder, folds, save_npz, num_threads_preprocessing,
  File "/workspace2/github/nnUNetFrame/nnUNet/nnunet/inference/predict.py", line 658, in predict_from_folder
    return predict_cases(model, list_of_lists[part_id::num_parts], output_files[part_id::num_parts], folds,
  File "/workspace2/github/nnUNetFrame/nnUNet/nnunet/inference/predict.py", line 216, in predict_cases
    softmax = trainer.predict_preprocessed_data_return_seg_and_softmax(
  File "/workspace2/github/nnUNetFrame/nnUNet/nnunet/training/network_training/nnUNetTrainerV2.py", line 212, in predict_preprocessed_data_return_seg_and_softmax
    ret = super().predict_preprocessed_data_return_seg_and_softmax(data,
  File "/workspace2/github/nnUNetFrame/nnUNet/nnunet/training/network_training/nnUNetTrainer.py", line 510, in predict_preprocessed_data_return_seg_and_softmax
    assert self.data_aug_params["do_mirror"], "Cannot do mirroring as test time augmentation when training " \
AssertionError: Cannot do mirroring as test time augmentation when training was done without mirroring
(1, 155, 186, 212)
before crop: (1, 212, 224, 255) after crop: (1, 212, 224, 255) spacing: [0.40000001 0.40000001 0.40000001]

no resampling necessary
no resampling necessary
before: {'spacing': array([0.40000001, 0.40000001, 0.40000001]), 'spacing_transposed': array([0.40000001, 0.40000001, 0.40000001]), 'data.shape (data is transposed)': (1, 165, 221, 221)}
after:  {'spacing': array([0.40000001, 0.40000001, 0.40000001]), 'data.shape (data is resampled)': (1, 165, 221, 221)}

no resampling necessary
no resampling necessary
before: {'spacing': array([0.40000001, 0.40000001, 0.40000001]), 'spacing_transposed': array([0.40000001, 0.40000001, 0.40000001]), 'data.shape (data is transposed)': (1, 199, 182, 248)}
after:  {'spacing': array([0.40000001, 0.40000001, 0.40000001]), 'data.shape (data is resampled)': (1, 199, 182, 248)}

(1, 165, 221, 221)
(1, 199, 182, 248)
no resampling necessary
no resampling necessary
before: {'spacing': array([0.40000001, 0.40000001, 0.40000001]), 'spacing_transposed': array([0.40000001, 0.40000001, 0.40000001]), 'data.shape (data is transposed)': (1, 212, 224, 255)}
after:  {'spacing': array([0.40000001, 0.40000001, 0.40000001]), 'data.shape (data is resampled)': (1, 212, 224, 255)}

before crop: (1, 124, 159, 208) after crop: (1, 124, 159, 208) spacing: [0.40000001 0.40000001 0.40000001]

before crop: (1, 164, 205, 208) after crop: (1, 164, 205, 208) spacing: [0.40000001 0.40000001 0.40000001]

(1, 212, 224, 255)
no resampling necessary
no resampling necessary
before: {'spacing': array([0.40000001, 0.40000001, 0.40000001]), 'spacing_transposed': array([0.40000001, 0.40000001, 0.40000001]), 'data.shape (data is transposed)': (1, 124, 159, 208)}
after:  {'spacing': array([0.40000001, 0.40000001, 0.40000001]), 'data.shape (data is resampled)': (1, 124, 159, 208)}

(1, 124, 159, 208)
no resampling necessary
no resampling necessary
before: {'spacing': array([0.40000001, 0.40000001, 0.40000001]), 'spacing_transposed': array([0.40000001, 0.40000001, 0.40000001]), 'data.shape (data is transposed)': (1, 164, 205, 208)}
after:  {'spacing': array([0.40000001, 0.40000001, 0.40000001]), 'data.shape (data is resampled)': 

(1, 164, 205, 208)}
```

**Comment by MrMarkusJ** [comment]
Dear Junye-Chen,

I am facing the same problem. Unfortunately I can´t offer you any solution :-(

- Training using _noMirroring:
- Prediction: ` nnUNet_predict -i ~/nnUNet_raw_data_base/nnUNet_raw_data/XYZ/imagesTs/ -o ~/RESULTS_FOLDER/XYZ/ -tr nnUNetTrainerV2_noMirroring -m 3d_fullres -p nnUNetPlansv2.1 -t xyz`
- error message: **/nnUNet/nnunet/training/network_training/nnUNetTrainer.py", line 510, in predict_preprocessed_data_return_seg_and_softmax
    assert self.data_aug_params["do_mirror"], "Cannot do mirroring as test time augmentation when training " \
AssertionError: Cannot do mirroring as test time augmentation when training was done without mirroring**

Afterwards the Soft max outputs were generated by calling `--npz` option for each fold `nnUNet_train 3d_fullres nnUNetTrainerV2_noMirroring xyz 4 -val --npz` ; which worked out!

Calling 'nnUNetTrainerV2_noMirroring' resulted in the following output at:

_I am running the following nnUNet: 3d_fullres
My trainer class is:  <class 'nnunet.training.network_training.nnUNet_variants.data_augmentation.nnUNetTrainerV2_noMirroring.nnUNetTrainerV2_noMirroring'>_
--> looks like that _noMirroring was recognized. While later along the output of the 'nnUNetTrainerV2_noMirroring' command the output sated:

_I am using data from this folder:  /nnUNet_preprocessed/xyz/nnUNetData_plans_v2.1
###############################################
2023-03-13 15:15:33.204445: loading checkpoint /nnUNet_trained_models/nnUNet/3d_fullres/xyz/nnUNetTrainerV2_noMirroring__nnUNetPlansv2.1/fold_4/model_final_checkpoint.model train= False
WARNING! do_mirroring was True but we cannot do that because we trained without mirroring. do_mirroring was set to False
loading dataset_
-->looks like that _noMirroring trainer is causing a WARNING.

Looks like that the "noMirroring" options needs to be set/enabled for the prediction, looks like it is not enough to call 'nnUNetTrainerV2_noMirroring' for the prediction; 

Not sure how to proceed at this stage.

Does anyone have a suggestion?
For any help I am grateful!

Best,
Markus

**Comment by Junye-Chen** [comment]
> Dear Junye-Chen,
> 
> I am facing the same problem. MEANWHILE I guess I found an answere :-)
> 
> * take a look at  [about predict #747](https://github.com/MIC-DKFZ/nnUNet/issues/747)
> * or at this example: https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/inference_example_Prostate.md
> 
> _If you would like to speed it up (at the expense of a slightly lower segmentation quality) you can **disable** _test time data augmentation_ by setting the **--disable_tta** flag (8x speedup)._
> 
> --- @Junye-Chen : try nnUNet_predict -i /workspace2/github/nnUNetFrame/DATASET/nnUNet_raw/nnUNet_raw_data/Task001_Tooth/imagesTs/ -o /workspace2/github/nnUNetFrame/DATASET/nnUNet_raw/nnUNet_raw_data/Task001_Tooth/inferTs -t 1 -m 3d_fullres -f 4 -tr nnUNetTrainerV2_noMirroring **--disable_tta**
> 
> Hopefully this will improve your situation.
> 
> Best, Markus

Thank you very much! It did help me. :)

**Comment by FabianIsensee** [comment]
Thanks @MrMarkusJ  :-)
