### ISSUE TITLE
Using symlinks for input files for prediction

### ISSUE THREAD

**Issue by krekiehn** [MIC-DKFZ/nnUNet#1430]
Hello,

I want to do prediction with a trained nnunet model. I have a folder with symlink files to the original input CTs. 
But if i run the prediction i get:

There are 0 cases in the source folder
I am process 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 0 cases that I would like to predict
using pin_memory on device 0

If i put a original file in the same folder i get:
There are 1 cases in the source folder
I am process 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict
using pin_memory on device 0

Predicting BI0002:
perform_everything_on_gpu: True
Prediction done, transferring to CPU if needed
sending off prediction to background worker for resampling and export
done with BI0002

Is there any chance to work with symlink files for the prediction?

Greetings Nicolai

**Comment by GregorKoehler** [comment]
Hi @krekiehn,
on behalf of all nnUNet maintainers, we want to apologize for leaving this issue stale for so long!

From what I've gathered, the issue you describe boils down to the following line in batchgenerators:
https://github.com/MIC-DKFZ/batchgenerators/blob/8822a08a7dbfa4986db014e6a74b040778164ca6/batchgenerators/utilities/file_and_folder_operations.py#L40

Here, a list of files in a given folder is created and for each path, os.path.isfile is used to check if the path belongs to a file. In my quick test, os.path.isfile returns False for symbolic links. So it seems like in order to be able to use symlinks, one would have to change this check in batchgenerators. I'm not sure if this would break other stuff w.r.t. nnUNet though, as this `subfiles` function is used all over the place.
We would have to consult with @FabianIsensee if you want this to be supported.

**Comment by GregorKoehler** [comment]
Hi @krekiehn,
closing this issue for now. If there is still a need for using symlinks during inference, please feel free to re-open the issue!
