### ISSUE TITLE
predict problem

### ISSUE THREAD

**Issue by ysj-xuanyuan** [MIC-DKFZ/nnUNet#1553]
Hello, I used this project to test the 002 sequence in the MSD dataset. I predicted the results of the test set. May I know where to find the GT of the test set and how to calculate the performance indicators of the model on the test set

**Comment by mrokuss** [comment]
Hey @ysj-xuanyuan

In order to obtain the perfromance of your model you can submit it to the leaderboard [here](https://decathlon-10.grand-challenge.org/evaluation/challenge/leaderboard/) which is still open. The final leaderboard of the challenge in 2018 can be found [here](http://medicaldecathlon.com/results/) though.

**Comment by ysj-xuanyuan** [comment]
> Hey @ysj-xuanyuan
> 
> In order to obtain the perfromance of your model you can submit it to the leaderboard [here](https://decathlon-10.grand-challenge.org/evaluation/challenge/leaderboard/) which is still open. The final leaderboard of the challenge in 2018 can be found [here](http://medicaldecathlon.com/results/) though.

Sorry, the test submission for this challenge seems to have been closed. Is there any other way to obtain test results for the test set?
