### ISSUE TITLE
AssertionError - After training is done (during prediction)

### ISSUE THREAD

**Issue by RancyChepchirchir** [MIC-DKFZ/nnUNet#1559]
My problem comes in when it's done training; it does prediction then it outputs this message:
![Screenshot from 2023-07-15 17-03-52](https://github.com/MIC-DKFZ/nnUNet/assets/50427374/00784628-bc25-418c-82df-15f57b8ccb6f)
![Screenshot from 2023-07-15 17-04-21](https://github.com/MIC-DKFZ/nnUNet/assets/50427374/84d74160-fdb0-428e-9b7c-3dc54749a196)
(P.S. my output dimension is 4)

**Comment by sten2lu** [comment]
Hi @RancyChepchirchir,

it seems as if the assertion in line 354 in export_prediction.py seems to be the cause of the problem as it catches your output_dimension to be 4.

However, the BraTS dataset is volumetric and therefore a segmentation map should have in my experience 3 dimensions instead of 4.
Could you please elaborate why your output dimension is 4?

Also, did you use standard nnU-Net V2 Planning and Preprocessing for the BraTS 21 dataset?

Best regards,

Carsten

**Comment by RancyChepchirchir** [comment]
Hi! Yes, I did employ the nnU-Net V2 Planning and Preprocessing and passed the integrity and sanity checks..but somehow not able to create the segmentation files..I really can't tell when the problem comes up nor why my segmentation files are of dimension 4..I'm aware I have (4,155,240,240) images' and (155,240,240) labels' dimensions in raw form respectively.

**Comment by sten2lu** [comment]
Could you maybe upload your dataset which you saved in the nnUNet_raw folder?
Therefore I would .

**Comment by sten2lu** [comment]
I will mark this issue as completed since it was not possible for me to reproduce the error message, and the data was not provided to me.
