### ISSUE TITLE
Slow inference time for double-lung images compared to single-lung images

### ISSUE THREAD

**Issue by TanCherYen** [MIC-DKFZ/nnUNet#1608]
Thank you for developing nnUNet! It's been very helpful for my medical imaging work.

I've encountered an issue related to inference speed:

## Problem
I've trained my models with single-lung medical images. However, when I try to inference with double-lung images, the process takes considerably longer than it does for single-lung image inference. It seems that the number of slices increases before inference. Is this expected? 

Below are the details for the lung images (sorry but I can only share the data for lung_01 with you).

1. lung_0024
    original dimension: (512, 512, 66)
    number of lung: single-lung
2. lung_0032
    original dimension: (512, 512, 68)
    number of lung: single-lung
3. lung_0081
    original dimension: (512, 512, 81)
    number of lung: single-lung
4. lung_01 (downloaded from https://wiki.cancerimagingarchive.net/display/Public/NSCLC+Radiogenomics)
    original dimension: (512, 512, 284)
    number of lung: **double-lung**
    download link: https://easyupload.io/h9iz1o
5. lung_02
    original dimension: (512, 512, 303)
    number of lung: **double-lung**
6. lung_0710
    original dimension: (512, 512, 321)
    number of lung: single-lung

As shown in the screenshots, the number of slices inferred for the double-lung has increased significantly: by 4x for lung_01 (from 284 to 1136) and by 9x for lung_02 (from 303 to 2727). This issue is also observed with the 3d_fullres model. Typically, the number of slices inferred should be fewer than the original count.

I'm wondering if nnUNet might be performing some preprocessing prior to inference that could account for this issue, or is this because I didn't register them (lung_01, lung_02) to the nnUNet Dataset? (the other 4 were registered as the test dataset)
Any insights or suggestions would be greatly appreciated.

### 2d model on Ubuntu 20.04 (GPU)
<img width="1064" alt="0102_2d_Ubuntu" src="https://github.com/MIC-DKFZ/nnUNet/assets/33594984/9857cdc8-7417-4a12-9ac0-d5dbb3317118">

### 3d_fullres model on Ubuntu 20.04 (GPU)
<img width="1064" alt="0102_3d_fullres_Ubuntu" src="https://github.com/MIC-DKFZ/nnUNet/assets/33594984/52257c43-766e-4cbe-ad44-d92d2676eb4f">

### 2d model on M1 Pro MacBook Pro (MPS)
<img width="1587" alt="0102_2d_Mac" src="https://github.com/MIC-DKFZ/nnUNet/assets/33594984/4a8951de-7c3c-4e83-bedc-0db2477937fe">

**Comment by ykirchhoff** [comment]
Hi @TanCherYen,

it is expected that the number of individual predictions done increases with the size of the images due to the fixed patch size and the sliding window approach. Usually this scales linearly in every dimension.
I assume that lung_01 and lung_02 have different spacings compared to the rest of your data. nnUNet will resample the spacing used during training, as saved in nnUNetPlans.json and predict on the resampled data, which then has a different shape.

Best,
Yannick

**Comment by TanCherYen** [comment]
Hi Yannick,

Thank you for the response!

After checking, I found that these two images indeed have different spacings compared to the other four images. Is there a way to reduce the inference time for data with differing spacings from the original data? Or, is it possible to resample before making an inference? (because it is just taking too long to infer...)

Kind regards,
Cher Yen

**Comment by ykirchhoff** [comment]
Hi Cher Yen,

you could disable resampling of the images during inference. That would save you the extra time but most likely only works reasonably well if the spacings in your training data are also very diverse. So usually you try to avoid that. A better way without losing too much performance is probably to disable test time augmentations, i.e. mirroring during inference. Just do that by running `nnUNetv2_predict --disable_tta ...`. But both approaches will lead to a degradation of performance, so do that carefully and only if time is a real problem and not just a minor annoyance.

Best,
Yannick

**Comment by TanCherYen** [comment]
Hi Yannick,

May I know how to disable the resampling of images during inference? I'd like to experiment with it. I'm using the `initialize_from_trained_model_folder` and `predict_from_files` methods in my code. It would be helpful if you could indicate which part of the code I should comment out to disable resampling.

Kind regards,
Cher Yen

**Comment by ykirchhoff** [comment]
Hi Cher Yen,

as far as I know there is no default way of how to do this. You can have a look at these [examples](https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunetv2/inference/examples.py#L59), you can overwrite the spacings in there (the props of the images) and use the `predict_from_list_of_npy_arrays` method to get your segmentations and then save them with the correct spacing. That is a bit of a hacky way but probably the easiest for just a few cases. Otherwise you could think about changing the [preprocessor](https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunetv2/preprocessing/preprocessors/default_preprocessor.py) not to resample images at all (this will be applied to preprocessing for training and inference and might be a good idea in case you incorporate images with different spacings into your training.
Let me know if that helps.

Best,
Yannick

**Comment by TanCherYen** [comment]
Hi Yannick,

Thank you for the advice! I have one last question. The spacing used during training, as saved in nnUNetPlans.json is the median spacing of the dataset, right?

Kind regards,
Cher Yen

**Comment by ykirchhoff** [comment]
Hi Cher Yen,

no problem at all. Yes, exactly. The spacing used by nnUNet by default is the median spacing. For some datasets it can be sensible to depart from the default but usually that is a good choice.

Best,
Yannick

**Comment by TanCherYen** [comment]
Hi Yannick,

Thanks a lot for the support. Your response has really helped! I'll be closing this issue now, but I'm grateful for the assistance.

Kind regards,
Cher Yen
