### ISSUE TITLE
How can I inference single file?

### ISSUE THREAD

**Issue by iskenderkahramanoglu** [MIC-DKFZ/nnUNet#1621]
First of all, thanks for this great project!

I can infer using "nnUNetv2_predict -i IN -o OUT_lowres -c 3d_lowres -d DATASET -f 0 1 2 3 4" on bash.
This takes folders as input and output.
I want to give a single file as input and output.
Is there a way for this?

I also want to change the batch size, number of epochs and apply augmentation.
I would appreciate if you can help with this!

**Comment by GregorKoehler** [comment]
Hi @iskenderkahramanoglu,
sorry for the late reply to this issue! Have you tried giving a folder which contains just the file you want to run inference for? Otherwise, nnUNetv2_predict uses the [predict_from_files](https://github.com/MIC-DKFZ/nnUNet/blob/b4e97fe38a9eb6728077678d4850c41570a1cb02/nnunetv2/inference/predict_from_raw_data.py#L190C6-L190C6)  method [here](https://github.com/MIC-DKFZ/nnUNet/blob/b4e97fe38a9eb6728077678d4850c41570a1cb02/nnunetv2/inference/predict_from_raw_data.py#L838C2-L838C2). The method requires either a foldername, or a list of list of filenames. The latter is due to the representation of inference files as lists of modalities, each belonging to a prediction case in a list of prediction cases. So another option would be to give the single prediction file e.g. as `[[path_to_file]]`. A simple hack for this could be to change [this line](https://github.com/MIC-DKFZ/nnUNet/blob/b4e97fe38a9eb6728077678d4850c41570a1cb02/nnunetv2/inference/predict_from_raw_data.py#L838C2-L838C2) to:
`predictor.predict_from_files([[args.i]], args.o, save_probabilities=args.save_probabilities,`

Let me know if this works for you!

**Comment by GregorKoehler** [comment]
As to the second part of your issue, let me give you some pointers to where these parameters are set in the standard nnUNetTrainer:
Number of epochs are set [here](https://github.com/MIC-DKFZ/nnUNet/blob/b4e97fe38a9eb6728077678d4850c41570a1cb02/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py#L145).
The batch_size is part of your plans json file, so you can edit the batch_size for your configuration of interest (e.g. "2d" / "3d") directly in the json file.
Concerning data augmentation, you can take a look at the standard augmentations used during training by the default trainer [here](https://github.com/MIC-DKFZ/nnUNet/blob/b4e97fe38a9eb6728077678d4850c41570a1cb02/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py#L660) onwards.
There do exist other trainers with increased amounts of data augmentation, e.g. the trainers found here:
https://github.com/MIC-DKFZ/nnUNet/tree/master/nnunetv2/training/nnUNetTrainer/variants/data_augmentation

**Comment by GregorKoehler** [comment]
I hope the answers above solved your issue. I'll close this issue due to it being stale for 3 weeks now. Feel free to re-open if you still encounter issues!
