### ISSUE TITLE
nnUNetv2_predict issue when running inference on the folder with variable input shapes

### ISSUE THREAD

**Issue by adityakillekar** [MIC-DKFZ/nnUNet#1627]
Hi,

I have been trying to run prediction with my trained model but facing the following error:

ERROR! Not all input images have the same shape!

Do I have to do some preprocessing before running inference on these raw nil.gz files. I have identified the location from where the error is originating would it not be better to perform transpose -> crop -> resample before appending them to stacked_images on line #100 in simpleitk_reader_writer.py? This way we can avoid any preprocessing required to the raw nil.gz files.

Thank you!

**Comment by adityakillekar** [comment]
My bad, I forgot to label the raw files {filename}_0000.nii.gz. The channel ID 0000 was missing.

**Comment by mrokuss** [comment]
Hi @adityakillekar 

I am glad you could already fix the issue by bringing all the files into nnUNet format. Regarding the preprocessing, nnUNet generally performs all of this on the fly during the prediction process such that no manual messing with the data is needed. The images also have to be preprocessed (internally) since nnUNet defines a specific image setting (spacing, normalization scheme, ..) it can best work with. Hope this helped!

Max
