### ISSUE TITLE
Use nnUNet pretrained encoding for other tasks such as classification

### ISSUE THREAD

**Issue by NassimBelmecheri** [MIC-DKFZ/nnUNet#1715]
How can i use the pretrained model last layer for different task such as classification?

**Comment by TaWald** [comment]
NnU-net is not made for such a use-case out of the box, as it is developed for segmentation. So there will be a bunch of customisation and coding required from your side.

In theory what you'd have to do is copy the architecture structure (partially) load weights, freeze loaded weights and optimize the last layer.

**Comment by LIKP0** [comment]
Hello all, I think maybe you can extract the bottom feature of nnUNet, and put that feature into other network for classification.

It's should be a lot easier to do this in nnUNet v2. (See "How to extract nnUNet features" #608 )

But im my opinion, it's not a good idea to use pretrained nnUNet to do feature extraction, since that feature may not represent the input data very well according to my own experiment.
