### ISSUE TITLE
Prediction  error : multi processing error during resampling.

### ISSUE THREAD

**Issue by bhatrana** [MIC-DKFZ/nnUNet#1719]
I have an issue shown in pic, installed nnunet2 on windows with pip. RAM of 48 GB and a GPU. 

![272628036-94aa9045-8406-4c89-9a6a-eb89c30ef4c4](https://github.com/MIC-DKFZ/nnUNet/assets/79718549/363972f3-4018-4a5b-bf7c-bef08d2b7cbe)

**Comment by seziegler** [comment]
If you actually only have 20 classes then you could map your labels to consecutive integers starting with 0 for background to 19 for the last class. After prediction you can simply remap the labels back to your original classes (100, 201, 210 etc) if needed. 
So what I mean exactly is copying your label files and modify the copies by changing e.g. label 210 to 19 etc so that you end up with consecutive integers. 0 has to be background!

Best,
Sebastian

**Comment by bhatrana** [comment]
@seziegler Thank you for the suggestion. I would go for this . Again a quick thinking, do classes has to be in order for this network ?
say I have 0 , 1 , 2 , 10 and 20. 
What if I eliminate sanity check for ascending order ?

**Comment by seziegler** [comment]
Hi @bhatrana ,
yes, the labels have to be in ascending order. 
This is assumed to be the case in later stages of the code so removing assertions from the code will not help and since assertions are usually there for a reason this should never be done.

Best,
Sebastian
