### ISSUE TITLE
Training stops after a few epochs, killing whole terminal session

### ISSUE THREAD

**Issue by VonbatenBach** [MIC-DKFZ/nnUNet#1732]
Hi, 
I have the following problem. When I try to train my 3d_fullres model with command `nnUNetv2_train DATASET_ID 3d_fullres all ` the training starts as expected, then it completely shuts down in a random moment after 0-3 epochs. The terminal session that I have run that training from, just disappears. Now, some technical info:
- my dataset is quite huge and I try to train a model with 4 input channels. As I've seen, the unpacked inputs (.npy files) can sometimes have ~1GB, so they are pretty big
- I thought this is maybe due to some CPU resources depletion when preprocessing (as initially I was trying to run it on 14 threads) so I tried to change the parameter `nnUNet_n_proc_DA`. I went all the way down to 1 but it still does exactly the same.
- I use option `export nnUNet_keep_files_open=True` and before running any training I always change the system limit for open files with `ulimit -n SOME_BIG_NUMBER`
- my GPU is Geforce RTX 3070 Ti Laptop and CPU is AMD Ryzen 7 6800H (8 cores, 16 threads). I use Ubuntu.
- This problem did not occur with smaller datasets and 1-channel input, although now I recall that my terminal session was sometimes also killed in the last stages of validation
- I have the updated nnUNetv2 version, installed via `pip install nnunetv2 -U`
- I have some training hyperparameters tweaked such as `num_iterations_per_epoch` (100), `num_epochs` (100) or `save_every`.
I also attach some pictures from system monitor (maybe they will be useful) witch catch the moments of "shutting down". With large `nnUNet_n_proc_DA` [(pic)](https://imgur.com/KJP8zC2) it usually happens when for some time (like 10-15 sec maybe) all CPU threads seem to be fully occupied. For `nnUNet_n_proc_DA=1` [(pic)](https://imgur.com/n6gyvXr) however, it just happens randomly. In each case RAM ans swap stay in a good range (I suppose). I also provide some logs: [Example of logs](https://github.com/MIC-DKFZ/nnUNet/files/12843633/training_log_2023_10_8_14_32_44.txt), [debug.json](https://github.com/MIC-DKFZ/nnUNet/files/12843641/debug.txt)

Thank you in advance!

**Comment by ancestor-mithril** [comment]
Did you try `nnUNet_n_proc_DA=0` and `nnUNet_keep_files_open=False`? 
`nnUNet_n_proc_DA=0` does not use multiprocessing at all when loading the data and doing data augmentation, so it might solve any problem related to multiprocessing.

**Comment by VonbatenBach** [comment]
Right after I wrote my post, I thought that keep_files_open=True might be causing some problems. I've just started a session with `nnUNet_keep_files_open=False` and I'll update you soon.

**Comment by VonbatenBach** [comment]
Ok, 10 epochs have passed without a problem, I fixed `nnUNet_keep_files_open=False` and `nnUNet_n_proc_DA=12` (as setting it to 0 would probably significantly slow down my training). It actually trains faster now, than before. Do you have a theory why did `nnUNet_keep_files_open=True` cause problems? Or maybe it was because of `ulimit -n SOME_BIG_NUMBER` run locally in a terminal session instead of globally?

**Comment by mrokuss** [comment]
Hey @VonbatenBach 

So if I understand correctly, you experienced issues in nnUNetv2 with the training (of large files) crashing after a few epochs and `nnUNet_keep_files_open` to False now gladly resolved this and lead to a smooth training?

Regarding why `nnUNet_keep_files_open=True` may have caused problems, it could be due to a combination of factors, including your system's file handle limits (which you did increase but maybe this still did not work properly as you mentioned) and the interaction between nnUNet's file handling and data loading processes. Keeping this many, especially large files, open at the same time might have just killed the process internally, thus explaining the disappearing terminal. It is hard to judge from afar but I am glad you could resolve your issue!

If you still have questions feel free to reopen! Best,

Max
