### ISSUE TITLE
3d_cascade_fullres: Is postprocessing done on 3d_lowres?

### ISSUE THREAD

**Issue by learningdeep2023** [MIC-DKFZ/nnUNet#1733]
I do not think that postprocessing is performed on the 3d_lowres.
Is this true? Any reason not to do it?

**Comment by Karol-G** [comment]
Hey @learningdeep2023,

In order to apply postprocessing on 3d_lowres when doing 3d_cascade_fullres, you need to first run `nnUNetv2_accumulate_crossval_results` to collect all 5 folds from lowres and afterwards `nnUNetv2_determine_postprocessing`. At last, you can use the result to apply it with nnUNetv2_apply_postprocessing

I hope I could help.

Kind regards,
Karol
