### ISSUE TITLE
small sclerosis segmentation

### ISSUE THREAD

**Issue by nightandweather** [MIC-DKFZ/nnUNet#1754]
Thank you for sharing the great repository!

I'm currently working on detecting small sclerosis in T1 images. However, due to their small size, 
I'm facing difficulties in segmentation. When running nnUnet as a baseline, 
I obtained a dice score of 0.14. I'm wondering how to address this issue.

<img width="293" alt="Screenshot 2023-10-18 at 3 55 55 PM" src="https://github.com/MIC-DKFZ/nnUNet/assets/48376964/684bdcb6-3121-47d5-9d88-50b6a8383130">

I'm working on modifying the default plan.json settings to make the model more robust to smaller objects by reducing the patch size. If there are any other approaches you could recommend, I would greatly appreciate it

Great
Kanghoun

**Comment by nightandweather** [comment]
plus, how to change LR policy? I want to use SWA(stochastic weight averaging)

**Comment by LIKP0** [comment]
Hello,

For your first question, I think you can refer to the existing method on sclerosis segmentation problem, and find out their network architecture so that you can modify the nnUNet. Since this is a specific question, there may be lots of reasons which lead to the bad result. It's not easy to give a common answer. You can share more info about your problem, for example, the trainging log of nnUNet, the validation dice, etc.

For your second question, you can overwrite the `configure_optimzers()` in nnUNetTrainer.py

![image](https://github.com/MIC-DKFZ/nnUNet/assets/56829276/47f25d3e-9e47-4f38-b0d9-c8d09522e9fe)

What's more, you'd better to implement a new trainer class inherited from nnUNetTrainer instead of changing the raw class directly. 

See [how to extend nnUNet](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/extending_nnunet.md)

**Comment by norajitr** [comment]
Hi nightandweather,

@LIKP0 thanks for clarifying. Regarding the performance problem for small structures, you can generally consider increasing foreground oversampling in the dataloader. Please feel welcome to report back.

Best,
Tobias

**Comment by nightandweather** [comment]
ah.. yes thank you for sharing idea

I won the first prize at 2023 Asan Help Challenge in Vessel sclerosis segmentation T1-mri images using nnUNet, 

thank you very much

https://github.com/nightandweather/2023-Asan-Help-Challenge-topic4-1st-solution
