### ISSUE TITLE
Question on patch sampling

### ISSUE THREAD

**Issue by Treeboy2762** [MIC-DKFZ/nnUNet#1759]
Thanks for sharing such a meaningful research!

To the best of my knowledge, there is no documentation on how the patch sampling is done, as @FabianIsensee mentioned in #210.

I am planning to use small size patches, 3D, such as (32, 32, 32), but the way nnUNetDataLoader3D extracts patches seems inefficient to my case.

If I understood the code correctly, the behavior of training/dataloading/data_loader_3d.py would be as follows:

```python
class nnUNetDataLoader3D(nnUNetDataLoaderBase):
    def generate_train_batch(self):
        # get indices of cases
        selected_keys = self.get_indices()

        # iterate over those
        for j, i in enumerate(selected_keys):

            # load each case
            data, seg, properties = self._data.load_case(i)

            # and perform foreground cropping
            bbox_lbs, bbox_ubs = self.get_bbox(shape, force_fg, properties['class_locations'])
            ...

        return ...
```

However, this only results in obtaining a batch with images. Actual patch cropping is done with "training_transforms", specifically with SpatialTransform from batchgenerators library.

This means, while nnU-Net dataloader provides well-optimized pipeline for large patches, it may not be efficient in training with mini patches, as the pipeline only extracts one patch per case; multiple patches per case would be desirable for mini-patch training.

May I ask if my understanding is complete?

**Comment by FabianIsensee** [comment]
Hey, I think you forgot one important detail:

`data, seg, properties = self._data.load_case(i)`

never actually reads the entire image! We open the raw numpy file with `mmap_mode='r'` which leaves the array on disk. We then proceed to find the bbox of where we want the current patch to be and take that crop. Only when we take the crop the data will be read, and because the crop can be much smaller than the image we only read a tiny part. So there isn't any wastage at all. The only 'problem' is the overhead of opening and closing the file, which is really negligible.

An additional plus about the way we do this is that all reads will be cached by the OS so over time (and given lage enough ram) large parts of the dataset can reside in memory and do not require additional read operations.

What may have gotten you confused is that we have two crop sized. The initial crop size and then the final patch size. The initial size is larger because we want to be able to rotate etc without introducing border artifacts. Even though it's a bit larger, it is still tiny.

Best,
Fabian

**Comment by Treeboy2762** [comment]
Thank you! As this information is new to me, now I can see the ingenuity in the design.
