### ISSUE TITLE
Number of patches in an image

### ISSUE THREAD

**Issue by hoangnambui2301** [MIC-DKFZ/nnUNet#1760]
Hello.

I'm using nnUNet for the MRI 3D segmentation task. I changed the input patch size to fit with my PC's condition. 

This may sounds silly but I wonder about the "patch size" here. Does it mean that an entire image is divided into several patches and these patches are pass through the model one-by-one? If yes, I would like to ask whether there is code that determine the number of patches for one image.

for example, my image has the size of 250x184x103 and with the default nnUNet's auto-configuration, it gives the patch size of 196x160x80. I reduced the patch size by modifying the variable "self.UNet_reference_val_3d" until I get the patch size of 24x20x10. So, dose only one patch with that size go to the model and then the other patch (of the other image) goes to the model? Or, several patches of the image go to the model one-by-one and then the other image comes (with its patches)? How can we name a turn of one patch? Iteration? Batch? Epoch?

Thanks a lot for help.

**Comment by TaWald** [comment]
In 3D we don't have enough GPU Memory to pass a whole patient through our networks (with a large network), as the volumes have a lot voxels. Hence all methods use patching, where you train with a subset of the image (a 3D Crop) or in 3D lingo, a patch. 

When you train with the patches, your network is accustomed to the patch size (i.e. the boundary artifacts from padding, image statistics for the norms) so changing the patch size during inference usually comes with a performance penalty. 

Now when you want to predict a whole patient, you do so via Tiling, which divides the image into a set of patches of the size you trained with, you can imagine it like using the network in a sliding window fashion. In nnU-Net the steps between the tiles are 0.5 the dims of the patch, so you have a significant overlap. This is due to nnU-Net being better in non-border regions.

Now to your Questions:
 >Does it mean that an entire image is divided into several patches and these patches are pass through the model one-by-one? 

 No. nnU-Net dynamically pulls one patch from a randomly sampled image (and centeres around foreground, because usually there is a lot of background and you want your model to see foreground often)

> I reduced the patch size by modifying the variable "self.UNet_reference_val_3d" until I get the patch size of 24x20x10. So, dose only one patch with that size go to the model and then the other patch (of the other image) goes to the model?

Yes, only one patch of the whole volume of the patch size in the plans goes to that model. With some probability it has foreground or it is randomly drawn from somewhere else. [Code](https://github.com/MIC-DKFZ/nnUNet/blob/de48541317a8019668cfb37a354da241040fe3ce/nnunetv2/training/dataloading/base_data_loader.py#L25) -- Also you can manually define patch size in the plans directly.
 
 > If yes, I would like to ask whether there is code that determine the number of patches for one image.
 
nnU-Net always uses exactly one patch per sample, but the patch is dynamically changed.

>How can we name a turn of one patch? Iteration? Batch? Epoch?

nnU-Net uses the term of `Epoch` for 250 iterations independent of dataset size. In each iteration a batch of 1 or more patches is used. *So, to answer your question there is no proper name for that.* Calling it an Epoch is technically wrong, since you don't see all input images. But even if you would see all input images once, you would not see the whole volume once, so that could arguably not be an Epoch either. If you would try to sample the patches, so you see the whole volume once, one could argue, that larger volumes are `seen` more often by the network, which would bias your model to be better on larger volumes than smaller ones. Basically the whole concept of Epoch breaks down when you can't input the whole image at once.
