### ISSUE TITLE
I need the weights of the BraTs22 competition or the reports on the paraments in the BraTs22 competition

### ISSUE THREAD

**Issue by TueNguyen2006** [MIC-DKFZ/nnUNet#1769]
I used the default parameters in the nnUNetv2 model on the Brats22 dataset, but I found it to be ineffective even after training for 500 epochs. I believe the issue lies with the parameters. When participating in the Brats22 competition, should the author modify the parameters to align with the competition? 

Thank you very much!

**Comment by norajitr** [comment]
Hi TueNguyen2006,

unfortunately, we cannot provide you with parameters for the Brats22 datset, since we have not participated in Brats22. Just for sanity checking, have you tried reproducing results e.g. from Brats20? In general, we can recommend thorough quality checks of your data e.g. wrt label quality. Please feel welcome to report back your findings and in case of further questions.

Best,
Tobias

**Comment by TueNguyen2006** [comment]
Hi Tobias

I sincerely apologize for the delayed response and any inconvenience it may have caused. Currently, I have switched to the brats21 dataset and noticed that it seems your model has been previously trained on it. I was wondering if you have the best weights for this dataset or, at least, any adjusted parameters to optimize and speed up the model.

Best,
Tue

**Comment by norajitr** [comment]
Dear Tue,

no problem! What you can do is try and scale up the training for the Brats challenge a bit. You can do this by going along the lines as described here:

https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/competitions/AutoPETII.md  

Please don't hesitate to let us know if this helps.

Best,
Tobias
