### ISSUE TITLE
RuntimeError: Some segmentation images contained unexpected labels. Please check text output above to see which one(s).

### ISSUE THREAD

**Issue by apuomline** [MIC-DKFZ/nnUNet#1777]
Hello, author! I used the thyroid nodule dataset to train nnunet, I entered is: 
<<nnUNetv2_plan_and_preprocess -d 666  --verify_dataset_integrity >>but there was an error in the data preprocessing:
    Error: Unexpected labels found in file F:\liuxiao\project\nnUNet\nnUNetFrame\nnUNet_raw_data_base\Dataset666_thyroid\labelsTr\59.png.
Expected: [0, 1]
Found: [  0. 255.]
Traceback (most recent call last):
  File "F:\miniconda\envs\nnunet\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "F:\miniconda\envs\nnunet\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "F:\miniconda\envs\nnUNet\Scripts\nnUNetv2_plan_and_preprocess.exe\__main__.py", line 7, in <module>
  File "F:\liuxiao\project\nnUNet\nnunetv2\experiment_planning\plan_and_preprocess_entrypoints.py", line 182, in plan_and_preprocess_entry
    extract_fingerprints(args.d, args.fpe, args.npfp, args.verify_dataset_integrity, args.clean, args.verbose)
  File "F:\liuxiao\project\nnUNet\nnunetv2\experiment_planning\plan_and_preprocess_api.py", line 47, in extract_fingerprints
    extract_fingerprint_dataset(d, fingerprint_extractor_class, num_processes, check_dataset_integrity, clean,
  File "F:\liuxiao\project\nnUNet\nnunetv2\experiment_planning\plan_and_preprocess_api.py", line 30, in extract_fingerprint_dataset
    verify_dataset_integrity(join(nnUNet_raw, dataset_name), num_processes)
  File "F:\liuxiao\project\nnUNet\nnunetv2\experiment_planning\verify_dataset_integrity.py", line 210, in verify_dataset_integrity
    raise RuntimeError(
RuntimeError: Some segmentation images contained unexpected labels. Please check text output above to see which one(s).
----------------------------------------------------------------------------------------------------------------------
  The dataset.json file in the dataset is configured as follows:
     {
    "channel_names": {
        "0": "R",
        "1": "G",
        "2": "B"
    },
    "labels": {
        "background": 0,
        "diaphramg":1
    },
    "numTraining": 637,
    "file_ending": ".png",
    "name": "Dataset666_thyroid"
}
The thyroid nodule data set is similar to this:
    image:
![0000_0000](https://github.com/MIC-DKFZ/nnUNet/assets/119391475/855ea28a-bb66-4b13-aca1-e813696de051)
  label:
    
![1](https://github.com/MIC-DKFZ/nnUNet/assets/119391475/9219d320-3491-4661-81c5-82e274997a27)

Excuse me, is this due to the wrong setting of data set classification category? What should I do specifically? I don't quite understand the specific program error reasons.

**Comment by mrokuss** [comment]
Hey @apuomline 

As the error message you provided indicates there is an issue with the labels in the thyroid nodule dataset you used to train nnU-Net. Specifically, it states that some segmentation images contain unexpected labels. Here's a breakdown of the error message:

- The problematic file is "59.png" in the "labelsTr" directory of the dataset although I suppose that all label images are affected since this is a classic problem when working with 2D color images.
- The expected labels for the segmentation images should be [0, 1] integers.
- However, the labels found in "59.png" are [0, 255].

This inconsistency in the labels is causing the error. To resolve this issue, you should inspect the dataset and correct the labels so that they match the expected values of [0, 1]. The error you're encountering is a typical problem often seen in image processing and computer vision, where the scale of 0-1 (floating point numbers) is mapped to the scale of 0-255 (uint8) in images. Make sure your labels are saved correctly (with values 0 and 1), then you should be able to proceed. Hope this helps :)

Max

**Comment by LIKP0** [comment]
Hello all, 

Just a simple supplement, your original label image is actual RGB color images with (0,0,0) and (255,255,255) (so that we can see there are black and white). You should map the RGB value to 0 and 1 and save them with correct file type. Now the label image looks whole dark since human eyes cannot distingulish (1,1,1) from (0,0,0), but that makes sense to nnUNet!

Enjoy yourself!
