### ISSUE TITLE
having 2 different ground truth for T1 and T2 how to put them in the LabelTr file 

### ISSUE THREAD

**Issue by Body123** [MIC-DKFZ/nnUNet#1810]
I have a ground truth image for T1 and another ground truth image for T2 and for the segmentation ground truth label which one I should put in labelTr folder, which one of these 2 ground truths images and when I visualize these 2 images I found that they are different not the same image.

**Comment by ykirchhoff** [comment]
Hi @Body123,

this depends a lot on your specific problem and I unfortunately can't help too much with that. It might be possible to combine the two segmentations into one if they depict different classes, i.e. structures which are only visible on one of the sequences. 
If you feel confident enough modifying code in nnUNet yourself, you could also add a second segmentation head, so that you can predict both segmentations individually, but that would require changing some stuff in the whole pipeline and I wouldn't recommend that if you don't know exactly what to do.

Hope that helps,
Yannick
