### ISSUE TITLE
Overlapping Segmentation Masks in 2D with Region-Based Training.

### ISSUE THREAD

**Issue by rahulghosh2** [MIC-DKFZ/nnUNet#1823]
Hello nnUNet Community,

I am working on a segmentation task involving four labels: background (0) and three distinct objects (1, 2, and 3). In my dataset, labels 2 and 3 can overlap. The segmentation labels are structured in a (512, 512, 3) array, with each channel representing a binary segmentation for labels 1, 2, and 3, respectively.

To accommodate overlapping regions between labels 2 and 3, while also maintaining the requirements for nnUNet training, I transformed this into a single-channel (512, 512, 1) array, introducing a new label (4) to represent the overlap. Thus, my labels are now 0 (background), 1, 2, 3, and 4 (overlap of 2 and 3).

Following the region-based training guide, I defined four regions and successfully trained the network. However, during inference, the model does not recognize the overlapping region (label 4). Instead, it seems to prioritize the last region (3+4), resulting in output labels [0, 1, 2, 3] and omitting the overlap label 4.

I have attached a screenshot of my dataset.json file for reference.

Could you please advise on how to structure this problem to ensure the model correctly learns and represents the overlapping region (label 4) in the output? Ideally, I would like to get the segmentation output at (512, 512, 3) where there are 3 separate binary segmentations, as I feel that learning the overlap independently breaks up the segmentation mask. 

Thank you for your guidance and support.

<img width="232" alt="image" src="https://github.com/MIC-DKFZ/nnUNet/assets/73354599/5575273b-8534-44ff-8a75-49e746c6886c">

**Comment by TaWald** [comment]
https://github.com/MIC-DKFZ/nnUNet/issues/653

**Comment by rahulghosh2** [comment]
Thank you for your response, while #653 is similar in that the region-based training is used to simulate an overlapping multi-class segmentation problem, it primarily deals with how to handle this problem from the input end, while my question is about how to derive the output as a 3-channel binary segmentation map. The solution I have been using is to use --save_probabilities when using nnUNetv2_predict command. Following this, the segmentation map can be generated from the probability maps with a function like this: 

```
def load_prob_maps_from_directory(prediction_directory_path, threshold=0.5):
    """
    Returns a list of NumPy arrays with shape (512, 512, 3)

    :param prediction_directory_path: folder where the probability maps are stored.
    :param threshold: threshold value for binarizing the map
    """
    # Find all .npz files in the directory and sort them
    npz_files = sorted(glob.glob(os.path.join(prediction_directory_path, '*.npz')))
    print(f"Number of .npz files found: {len(npz_files)}")
    
    # List to store the reshaped and binarized arrays
    binarized_npz_arrays = []

    # Loop through the sorted .npz files and load them
    for file in npz_files:
        with np.load(file) as data:
            for array in data.values():
                # Squeeze out the singleton dimension and transpose if necessary
                if array.shape == (3, 1, 512, 512):
                    array = np.squeeze(array, axis=1).transpose(1, 2, 0)

                # Binarize the array based on the threshold
                binarized_array = (array >= threshold).astype(np.uint8)
                binarized_npz_arrays.append(binarized_array)    

    return binarized_npz_arrays
```

**Comment by TaWald** [comment]
You are right, due to the overlap nnU-Net would overwrite overlapping regions due to the class region ordering once you do the conversion to hard labels. 
Writing a dedicated function due to the class probabilities like you did is probably the least invasive way to achieve this at the moment as you don't have to touch nnU-Nets internal logic.

If you would want this to happen automatically you would have to touch the `LabelManager` and overload the `convert_probabilities_to_segmentation` function ([here](https://github.com/MIC-DKFZ/nnUNet/blob/6309155280b119e35391d679b91476b01faf0b1b/nnunetv2/utilities/label_handling/label_handling.py#L143)) where the probabilities get converted and overwritten in the label region order.

If you make it into multiple binary maps you don't even have to touch the saving method.

Hope this helps!
Best Tassilo

**Comment by TaWald** [comment]
As this seems done and this feature will be included in v3, I will close this due to inactivity.

**Comment by anabm07** [comment]
Hi there, I have been reading this issue because we are also training nnunet on a dataset with multiple overlaps. In our case we have 24 organs (in the brain) and many of them are overlapping, so having extra regions to learn the overlap is not an option for us (we will end up having too many regions). You mention that v3 include this feature of having a separate output channels for each structure, is this version coming up soon?  If there is still longtime till the new version, do you recommend us to do the same solution as [rahulghosh2]? @MargerieHD
