### ISSUE TITLE
What does cascaded do?

### ISSUE THREAD

**Issue by dark16sider** [MIC-DKFZ/nnUNet#183]
Hi,
I want to understand the 3D cascaded Unet. Correct me if I'm wrong, you use 2 U-nets one trained on lower resolution and the other on higher resolution. But what do you actually do with the first U-net. I have read that you can use it to crop the CT/MRI so that it become smaller. Also, Do you use the output of the the first U-net as an extra input for the second  U-net? Finally why do you need to do 5 fold in the lower resolution U-net ?  Is it to avoid overfitting?
Thank you

**Comment by FabianIsensee** [comment]
Hi,
all the information should be in the paper: https://arxiv.org/abs/1904.08128
The low resolution unet is not making the images smaller through cropping! It generates a segmentation map at lower resolution.
The second unet gets the segmentations of the first unet as additional input.
You need the 5 fold cv because only the validation split can be used as input for the second unet. By running the cross validation all training cases were part of a validation split at some point.
Best,
Fabian

**Comment by dark16sider** [comment]
Thank you so much

**Comment by dark16sider** [comment]
Than you so much
