### ISSUE TITLE
Hello I want ask about how to implement 'pretraining_and_finetuning' part

### ISSUE THREAD

**Issue by copiglet** [MIC-DKFZ/nnUNet#1844]
I conducted all of training phase, and i got very extraodinary result this model.
therefore, i want to try 'pretraining_and_finetuning' part.
However i cannot have any clue about this.
Can you give some script from initial data configuration to last phase,  all of phase?

**Comment by ykirchhoff** [comment]
Hi @copiglet,

there is documentation about [pretraining and finetuning](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/pretraining_and_finetuning.md) in the repo. If you have any problems with this I am happy to help, but would need some further details about what part you are struggling with.

Best,
Yannick

**Comment by copiglet** [comment]
For example, when i want to run 'nnUNetv2_plan_and_preprocess -d TARGET_DATASET', can i maintain Environment Variables that are set in SOURCE_DATASET?

And i want you to tell me what files TARGET_PLANS_IDENTIFIER and SOURCE_PLANS_IDENTIFIER specifically specify

**Comment by ykirchhoff** [comment]
Hi @copiglet,

I am not sure what you mean with the environment variables set in SOURCE_DATASET? What you would usually do is to run `nnUNetv2_plan_and_preprocess -d TARGET_DATASET` first, which does all the planning and preprocessing on the dataset, which you want to use for finetuning, i.e. the one relevant for your downstream task. All the extracted properties should be taken from this dataset in order to optimize performance on this. Therefore we run this first and then transfer the extracted plans files to the source dataset for the pretraining. `TARGET_PLANS_IDENTIFIER` and `SOURCE_PLANS_IDENTIFIER` are just the names/identifiers used for the plans, which you can also specifically choose in `nnUNetv2_train ... -p PLANS_IDENTIFIER`. nnUNet usually uses `nnUNetPlans` for this. However, for the pretraining, when you copy the plans to the SOURCE_DATASET you might want to rename that to not mix that up.

Hope this helps clarify a few things, let me know if there is anything else I can help you with.

Best,
Yannick
