### ISSUE TITLE
Where is the EMA model?

### ISSUE THREAD

**Issue by tomato18463** [MIC-DKFZ/nnUNet#1849]
Hi,

I read from [here](https://github.com/MIC-DKFZ/nnUNet/issues/1709) that nnUNetV2 keeps an EMA model, but I could not find it in the saved checkpoints. Where can I find the EMA model, and where is the code to compute it / save it? Thank you for your help!

**Comment by TaWald** [comment]
The answer in the thread you reference to is referring to an EMA of the dice metric and not an EMA of the model's weights.
In case you want to compute an EMA model you instead have to calculate an EMA of the model yourself. However you can take inspiration from the DICE EMA computation as it is the same concept, just with many tensors instead of a single scalar value.

Best,
Tassilo
