### ISSUE TITLE
Minor questions: e.g., lost anisotropic spacing?

### ISSUE THREAD

**Issue by JunMa11** [MIC-DKFZ/nnUNet#185]
Hi Fabian,

How is it going? I hope everything goes well with you.
Thanks for releasing the nnUNetV2, really awesome work.

I have some questions about the code.

### Q1. The spacing of anisotropic data should be the 10th percentile. However, it seems this part was commented out.

https://github.com/MIC-DKFZ/nnUNet/blob/180d773b65bb200178c7ed7eb944104a7afc1c76/nnunet/experiment_planning/experiment_planner_baseline_3DUNet.py#L66-L80

### Q2. How did you determine the GPU constraint?
https://github.com/MIC-DKFZ/nnUNet/blob/180d773b65bb200178c7ed7eb944104a7afc1c76/nnunet/network_architecture/generic_UNet.py#L182

I also noticed that you create some `experiment_planning` files for different GPUs. 
https://github.com/MIC-DKFZ/nnUNet/tree/master/nnunet/experiment_planning/alternative_experiment_planning

Would it be possible to automatically determine the input patch size and batch size according to the memory of GPUs?

### Q3. Would it be possible for you to give some explanation on this function?

https://github.com/MIC-DKFZ/nnUNet/blob/180d773b65bb200178c7ed7eb944104a7afc1c76/nnunet/network_architecture/generic_UNet.py#L410-L449

### Q4 When determining the input patch size, why do you introduce an isotropic patch of size 512x512x512mm?
https://github.com/MIC-DKFZ/nnUNet/blob/180d773b65bb200178c7ed7eb944104a7afc1c76/nnunet/experiment_planning/experiment_planner_baseline_3DUNet.py#L163-L181

 and the `DEFAULT_PATCH_SIZE_3D` is not used, right?
https://github.com/MIC-DKFZ/nnUNet/blob/180d773b65bb200178c7ed7eb944104a7afc1c76/nnunet/network_architecture/generic_UNet.py#L169

### Q5. Is there a risk that `maxzidx, maxyidx, maxxidx` exceed the data.shape?
https://github.com/MIC-DKFZ/nnUNet/blob/180d773b65bb200178c7ed7eb944104a7afc1c76/nnunet/preprocessing/cropping.py#L34-L42

How about
```python
def get_bbox_from_mask(mask, outside_value=0):
    mask_voxel_coords = np.where(mask != outside_value)
    minzidx = int(np.min(mask_voxel_coords[0]))
    maxzidx = int(np.min([np.max(mask_voxel_coords[0])+1, mask.shape[0]]))
    minxidx = int(np.min(mask_voxel_coords[1]))
    maxxidx = int(np.min([np.max(mask_voxel_coords[1])+1, mask.shape[1]]))
    minyidx = int(np.min(mask_voxel_coords[2]))
    maxyidx = int(np.min([np.max(mask_voxel_coords[2])+1, mask.shape[2]]))
    return [[minzidx, maxzidx], [minxidx, maxxidx], [minyidx, maxyidx]]
```

Best regards,
Jun

**Comment by FabianIsensee** [comment]
Hi Jun,
great to hear from you! Everything is fine here, it's just home-office time for everyone. Unfortunately my internet connection is quite bad at home so all this remote stuff is going slower than I would like. How are things for you?

About your questions:
Q1: You are loking at the wrong experiment planner. The new default is experiment_planner_baseline_3DUNet_v21.py

Q2 & Q3: The GPU memory constraint is quite difficult and the way this is handled is certainly not optimal. First I implement some 3D U-Net architecture manually and make it as large as I can given the GPU memory constraing (again, manually. This is only done once during development). Then I implement `compute_approx_vram_consumption` which effectively computes the aggregated size of the feature maps found in the network architecture. This function returns some number, which is going to be proportional to the GPU memory consumption. Because this function reflects the dynamic nature of the network architecture, it can be used to compute the feature map sizes of other network topologies (different input patches and network depths) as well. As long as the return value is smaller than the reference (`520000000`) we can be reasonably sure that this new topology will also fit into the GPU memory constraint.
This whole process makes some assumptions about the network architecture and it completely disregards the memory required for parameters, so it is a good idea to give it a little headroom. But overall I found it works really well for nnU-Net. If you want to implement your own network architecture you need to reimplement `compute_approx_vram_consumption` for it

Q4: We do not start with an isotropic patch of size 512x512x512mm. The comment is incorrect. We start with an input patch size that is large but has the same aspect ratio than the median image shape after resampling. Then we scale it down until the resulting architecture matches the GPU memory constraint

Q5: We never run into out of boundary problems with this. Consider an image that is all 1's (so no cropping will be done). This image has shape 10x10x10. For this image, `np.max(mask_voxel_coords[0]))` will be 9. But the image has a shape of img.shape[0]
= 10. We need ti increment by 1 so that when we reverse the cropping, we can do new_img[0:10, 0:10, 0:10] = cropped_img

Best,
Fabian

**Comment by FabianIsensee** [comment]
I just noticed you are right about Q1. We indeed start with 512x512x512mm and then move towards the aspect ratio (in voxels) of the data. 
Best,
Fabian

**Comment by JunMa11** [comment]
Hi @FabianIsensee ,

Thanks for your quick and detailed reply very much. It helps me a lot.

Similarly, I also suffer from very slow internet speed because my home university only allows using an internal VPN to access computational resources. Hope the epidemic can be over soon.

I found your finding

> We should note that we did not observe substantial disparities in segmentation accuracy between this approach and alternatives (e.g. max pooling, bi/trilinear upsampling)

is in accordance with this [blog](https://www.intel.com/content/www/us/en/artificial-intelligence/posts/biomedical-image-segmentation-u-net.html), 
> We believe that both UpSampling2D and Conv2DTranspose are equally reliable methods for generating accurate predictions in the U-Net topology. 

### Q6. Bi/trilinear upsampling has fewer parameters than transposed conv, why does nnunet choose the later one? 

### Q7. I really enjoy reading your [paper](https://arxiv.org/abs/1904.08128v2), what tools do you use to create the following wonderful figures?
- Figure 4-b
![image](https://user-images.githubusercontent.com/19947331/78558645-8eacfe80-7845-11ea-8c52-ae4330a77152.png)

- Figure 6
![image](https://user-images.githubusercontent.com/19947331/78558533-53123480-7845-11ea-8ee7-e275db904393.png)

Best regards,
Jun

**Comment by FabianIsensee** [comment]
Hi Jun,
there are so many design choices in nnunet and it is impossible to validate them all. So whenever you find something that seems off feel free to ask. It could just be there without a specific region.You don't want to know how many GPU hours already went into this thing :-D

Q6: I like to keep things consistent. Downsampling by strided conv, upsampling by conv transposed. Also if you want to use trilinear upsampling without running into an information bottleneck you need to upsample prior to changing the number of kernels and then introduce an additional 1x1(x1) conv to make the number of kernels match the ones that come from the skip connection. Not very pretty :-)

Q7: These Figures were created by my co-author Paul (@pfjaeger ). I really don't have the necessary skills to do pretty figures so I was happy that he stepped in. I believe he used keynote on his Mac, along with matplotlib/pyplot/seaborn plots.

Q8: I don't think this will be a problem but there is only one way to find out: try :-)

Q9: You don't need that anymore. Batchgenerators now used threadpoolctl to take care of that.

Best,
Fabian

**Comment by JunMa11** [comment]
Got it. Thank you very much for your kindly reply.
