### ISSUE TITLE
How to standardize data by scaling to 0 to 1?

### ISSUE THREAD

**Issue by goodsave** [MIC-DKFZ/nnUNet#1876]
May I ask how V1 version data preprocessing does not apply Z-Score normalization data, but instead uses a preprocessing mechanism that scales to 0 to 1.

**Comment by goodsave** [comment]
I found the following code:

` def determine_normalization_scheme(self):
        schemes = OrderedDict()
        modalities = self.dataset_properties['modalities']
        num_modalities = len(list(modalities.keys()))

        for i in range(num_modalities):
            if modalities[i] == "CT" or modalities[i] == 'ct':
                schemes[i] = "CT"
            elif modalities[i] == 'noNorm':
                schemes[i] = "noNorm"
            else:
                schemes[i] = "nonCT"
        return schemes`

I changed him to this:

` def determine_normalization_scheme(self):
        schemes = OrderedDict()
        modalities = self.dataset_properties['modalities']
        num_modalities = len(list(modalities.keys()))

        for i in range(num_modalities):
            if modalities[i] == "CT" or modalities[i] == 'ct':
                schemes[i] = "CT"
            elif modalities[i] == 'MR':
                schemes[i] = "MR"
            elif modalities[i] == 'noNorm':
                schemes[i] = "noNorm"
            else:
                schemes[i] = "nonCT"
        return schemes`

we can define the specific implementation in the "resample_1nd_dormalize" method.

**Comment by TaWald** [comment]
As you can see from the code the normalization scheme is determined by the 'modalities' that you write into your `dataset.json` e.g. if you denote "ct" you will apply the CT normalization instead of z-score normalization.\

The reasoning lies in that is that CT is a quantitative measure as it contains the Houndsfield units, which will have similar intensity for organs across patients/clinics and so on. The MRIs do not have such a correspondence and hence are z-score normalized while for CT a special normalization can be made.

If you want to know how to add normalization schemes, this position is where you could make additionsin the logic but then have to add a specific normalization scheme that does what you desire. 

If you have any more questions it would be very helpful to explain _in detail_ what you want to achieve in order for us to help.

Best, Tassilo

**Comment by goodsave** [comment]
Thank you very much for your reply.

I have implemented custom standardization (using nnunet v1).
I am testing the impact of some and all scales on the results.

Best, AllenWang
