### ISSUE TITLE
There is a vertical line in the upper left corner of CT on BatchData

### ISSUE THREAD

**Issue by goodsave** [MIC-DKFZ/nnUNet#1882]
When viewing BatchData data through BatchViewer, it was found that there is a vertical line in the upper left corner of CT. Is this an intentional design or an unintentional bug introduced?

![BatchViewer](https://github.com/MIC-DKFZ/nnUNet/assets/19647156/8ab671a9-7e3f-47cd-a147-eef60edc061e)

**Comment by goodsave** [comment]
If it is unintentionally introduced, how can it be removed?
I discovered it on the V1 version and hope it can also be fixed on the code branch in V1.

**Comment by FabianIsensee** [comment]
This is intentionally introduced because the viewer used in the GUI automatically scales intensity values in the currently visible 2D image. This causes flickering when scrolling through slices plus can cause problems interpreting blank segmentation maps as you would never know whether everything is 0, 1, 2, 3 etc. By displaying the whole gray scale of the 3D stack in each of the 2D images we force consistent brightness across slices.
What you are seeing is not a bright bar but a linear interpolation between the lowest and highest grayscale value. Left to the 'bright bar' you mention you see a second one that starts all black and gradually becomes brighter.
BatchViewer is a hacky tool purpose written to do a very specific thing. It is not nice, it is not user-friendly but it gets the job done ;-)
