### ISSUE TITLE
Merging labels

### ISSUE THREAD

**Issue by Yasna-frn** [MIC-DKFZ/nnUNet#1903]
I have three labels and I want to merge labels 2 and 1 in one label. I added the following to my JSON file according to [Region-based training](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/region_based_training.md)

"labels": {
    "background": 0,
    "Breast": [1, 2],
    "FGT": 3  
},
"regions_class_order": [1, 3],

But it segments labels separately (the same as before without adding in JSON file). Could you guide me to solve it?

**Comment by sten2lu** [comment]
Hi @Yasna-frn,

The merging of labels operates in a hierarchical fashion. So I believe there are 2 changes required for hierarchical merging of labels:
1. For "Breast" labels 1, 2 there seems to be no hierarchy involved where 1 is e.g. a body.
If you want labels 1 and 2 to be merged and always predicted to be the same, I suggest you perform this change in the labelsTr in nnUnet_raw folder and change all labels (2 to 1) and all labels (3 to 2). 


2. The region class order works on the integer labels. So, assuming you performed the first step already, you would fix this by setting it to the labels that are in the FGT and Breast so that FGT stands last.

The resulting dataset.json would look like this:
```
"labels": {
"background": 0,
"Breast": [1],
"FGT": 2
},
"regions_class_order": [1, 2],
```

This would make nnU-Net learn the overlapping structures. But as described in the Documentation on [Region-based training](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/region_based_training.md):

"Important: nnU-Net still requires integer label maps as input and will produce integer label maps as output! Region-based training can be used to learn overlapping labels, but there must be a way to model these overlaps for nnU-Net to work..."

Therefore, the label maps that nnU-Net will return are not merged; the labels 1 and 2 will still be present. So, this change mostly affects training and evaluation.

Best regards,

Carsten
