### ISSUE TITLE
Number of folds

### ISSUE THREAD

**Issue by jamtheim** [MIC-DKFZ/nnUNet#1904]
I want to change number of folds from 5 to 10. 
Is is sufficient to edit the number in n_splits in do_split function
(splits = generate_crossval_split(all_keys_sorted, seed=12345, n_splits=5)
found in 
nnUNetTrainer.py

Or will something else break during inference on test data with test time augmentation or similar after training?

**Comment by sten2lu** [comment]
Hi @jamtheim,

if you want nnU-Net to use 10 folds during training, the change you describe will allow you to do so.
nnU-Net just requires a splits file which has a specific amount of splits defined and is in the nnU-Net format. You could also generate it by hand or with another function if you would want to do so.
Of course, you would need to set the flags for all folds during training.

During prediction, I suggest you execute it with an explicit call to all trained folds if you want to use all trained folds.
```
nnUNetv2_train -f 0 1 2 3 4 5 6 7 8 9 ...
```
This is because the default parameters would only use the first five folds.

Perhaps I would also try to monitor the GPU VRAM and RAM consumption during prediction. The system requirements will increase with more models used during prediction.

Hope that answers your question.

Best regards,


Carsten

**Comment by jamtheim** [comment]
Great, I did exactly this and training and splitting works. Done in three more days and I will test the inference then. Thanks for great input!
