### ISSUE TITLE
Question about inference optimiation

### ISSUE THREAD

**Issue by aheschl1** [MIC-DKFZ/nnUNet#1917]
Hello, first of all thank you so much for this amazing repo; it is a life saver!

I am running into an issue in which I am limited to a 32GB RAM environment at inference time. I was wondering if you has any advice to optimizing the inference pipeline to allow for such a restriction? Speed does not matter to me, just memory. This environment has a 16GB GPU. I have adjusted code to restrict all multiprocessing to use only a single worker, and have also adjusted preprocessing.resampling.default_resampling.resample_data_or_seg to use float32s. My data is anisotropic, and I am running predict_single_numpy_array with proper arguments to predict on GPU. I have 22 classes to predict. I have tried numerous small optimizations; however, I need to find something significant for this to feasible.

Do you have any advice on where to go looking? I have tried tracing a good ammount of the code and have come up empty handed, I hope there may be some way...

**Comment by mrokuss** [comment]
Hey @aheschl1,

Thank you for your question! This is a tricky one, since you already fiddled around with using only a single worker (for everything including segmentation export and data iterator?). From the top of my head, maybe you could try disabling test-time augmentation (i.e., no mirroring, `use_mirroring=False`) and you could try increasing the steps between the patches nnUNet predicts (e.g. `tile_step_size=0.75`). The latter should then hold fewer arrays in memory if that's the issue.

Hope this helps!
