### ISSUE TITLE
ValueError : operands could not be broadcast together with shapes (1, 650, 686, 686) and (1, 665, 686, 686)

### ISSUE THREAD

**Issue by Peaceandmaths** [MIC-DKFZ/nnUNet#1922]
I have a similar  issue with the evaluate_predictions as in #1640. The solution in #1044 suggests that we should add the --verify_dataset_integrity flag. But the issue is not at the preprocessing step, from my understanding. My images and labels have matching shapes. The issue occurs at the prediction/postprocessing step. Is it possible that nnunet crops some of the predicted images so that the ground truth's and the predictions' shapes don't match ? How can we solve that ? Would skipping the postprocessing step solve the issue ? 

The command used : 
nnUNetv2_evaluate_folder -djfile /data/golubeka/nnUNet_Frame/nnUNet_data/nnUNet_raw/Dataset050_IA/dataset.json -pfile /data/golubeka/nnUNet_Frame/nnUNet_data/nnUNet_results/Dataset050_IA/nnUNetTrainer__nnUNetPlans__3d_fullres/plans.json --chill /data/golubeka/nnUNet_Frame/nnUNet_data/nnUNet_raw/Dataset050_IA/labelsTs /data/golubeka/nnUNet_Frame/nnUNet_data/nnUNet_results/Dataset050_IA/Predicted

The error message : 

![image](https://github.com/MIC-DKFZ/nnUNet/assets/117741432/af9b0787-54d5-4c2b-a3f7-382bc82b1b1f)

**Comment by TaWald** [comment]
Hey @Peaceandmaths,
as you correctly referenced you **likely have a mismatch of shapes between your input images and groundtruth images**.

>My images and labels have matching shapes.

![image](https://github.com/MIC-DKFZ/nnUNet/assets/34198766/0421b209-791e-4b03-8295-c4082ec650b1)

I would advise to _double check that your labels are actually identical to your groundtruths_, because this is very very likely the reason you are encoutering this issue.  If you don't have a size-mismatch in your image/label pairs I would be very surprised and something more nefarious is going on, but I ask you to verify this before hand and maybe create a reproducible test case that we can dive in to find out what is actually hapenning. 

>The issue occurs at the prediction/postprocessing step. Is it possible that nnunet crops some of the predicted images so that the ground truth's and the predictions' shapes don't match ? How can we solve that ? Would skipping the postprocessing step solve the issue ?

While nnU-Net processes your image in a cropped fashion, the crops contain softmax probabilities. These are then aggregated to one set of probabilities before being argmaxed into your final predicted classes. At this point you have the full image size again and then calculate `tp`, `fp` and `fn`  before they are merged back together into the original size. 
 
 ----
It would be really helpful for us though, if you would provide me with your current version of nnU-Net. The newer versions of nnU-Net should have prevented this earlier down the line already and thrown an error, as opposed to failing in this more ofuscated version during inference time.
I suppose we could improve the stack trace as well to highlight which cases have this size mismatch as well.

**Comment by Peaceandmaths** [comment]
Dear @TaWald, 

You are right, I apologize for the overlook. Two of my test images and labels shapes don't match indeed ! 

I found it out by running a code to check the dimensions. Yes, I think it would be very helpful if you could implement a couple of lines that would directly tell which images exactly have a mismatch, that would run in the beginning of the evaluation phase, something like this : 

![image](https://github.com/MIC-DKFZ/nnUNet/assets/117741432/e19274bb-ef5b-4404-9265-25a09ae9698a)


My version of nnunet : 
![image](https://github.com/MIC-DKFZ/nnUNet/assets/117741432/0c4e08ca-3e69-464a-a5be-4ebddb288626)


Thank you very much for your responsiveness and hard work :)
