### ISSUE TITLE
Reproduce preprocessing 

### ISSUE THREAD

**Issue by hyunjung00** [MIC-DKFZ/nnUNet#1969]
Hello, first thank you for  developing such a remarkable model. 

I have encountered a scenario during preprocessing where, after applying your model to a dataset, the dimensions of the images were altered from their original size of [40, 512, 512] to a cropped size of [40, 448, 448], with the patch size being [40, 224, 224]. I aim to replicate this exact preprocessing step on another dataset, which notably lacks ground truth labels, to extract features and incorporate them into the training process.

Could you  guide me on how to achieve this consistent preprocessing across datasets, especially considering the absence of ground truth labels in the second set? Any advice or pointers you could provide would be greatly appreciated.

Thank you for your time and support.

**Comment by ykirchhoff** [comment]
Hi @hyunjung00,

the preprocessing code for nnUNet can be found [here](https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunetv2/preprocessing/preprocessors/default_preprocessor.py).
It basically does three things, cropping to a nonzero box, normalization (can be any of [these](https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunetv2/preprocessing/normalization/default_normalization_schemes.py) - either using dataset statistics or just image statistics) and finally resampling.
You can replicate the preprocessing using nnUNet by copying the plans file of the first dataset to the new dataset and running `nnUNetv2_preprocess` with the plans file specified. However you would need to give it pseudo segmentations (i.e. just empty files of the same shape as the images) as nnUNet expects segmentations to be present. Otherwise you can also import/copy the relevant functions to your own code, if you are confident with doing that.

Let me know if you have any further questions.
Best,
Yannick
