### ISSUE TITLE
Error in Dataset

### ISSUE THREAD

**Issue by onlie202** [MIC-DKFZ/nnUNet#201]
Dear Fabian:
A few days ago I found a new version nnUnet and I updated it.But a new problem came out like this,which was not found before new nnUnet.How to reslove that ?
Error description : "nii.gz does not match the geometry of the label file. The pixel arrays will not be aligned and nnU-Net cannot use this data. Please make sure your image modalities are coregistered and have the same geometry as the label"
Best,

**Comment by FabianIsensee** [comment]
Hi,
It is a warning that the geometried between data and labels do not match and that there is a chance that the pixel arrays are not alinged. It is your responsibility to fix that (because this is your dataset and there is no way nnU-Net can know how this needs to be done).
You can also choose to ignore this warning (remove the verify dataset integrity flag) and it will pretend everything is fine.
Best,
Fabian

**Comment by onlie202** [comment]
Thanks for your fast reply! It works normally now.
Best,

**Comment by abcxubu** [comment]
Hi,
I met the same problem as yours. I'd like to ask that how do you finally deal with the problem. Hope to hear from you as soon as possible.
Best,

**Comment by onlie202** [comment]
> Hi,
> I met the same problem as yours. I'd like to ask that how do you finally deal with the problem. Hope to hear from you as soon as possible.
> Best,

I've forgotten the detail now. But please make sure that your dataset is complete and standardized.
