### ISSUE TITLE
File Not Found

### ISSUE THREAD

**Issue by lordhjx** [MIC-DKFZ/nnUNet#2012]
When I use colab to run the cardiac segmentation project, it shows: 
WARNING! Cannot run postprocessing because the postprocessing file is missing. Make sure to run consolidate_folds in the output folder of the model first!
The folder you need to run this in is /root/.platipy/nnUNet_models/nnUNet/3d_lowres/Task400_OPEN_HEART_1FOLD/nnUNetTrainerV2__nnUNetPlansv2.1 
Despite I can get the result.

And when I try to download the whole package, I pip install platipy[nnunet], but it shows:
error: could not create 'build\bdist.win-amd64\wheel\.\nnunet\experiment_planning\alternative_experiment_planning\target_spacing\experiment_planner_baseline_3DUNet_targetSpacingForAnisoAxis.py': No such file or directory
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for nnunet
  Running setup.py clean for nnunet
Failed to build nnunet
ERROR: Could not build wheels for nnunet, which is required to install pyproject.toml-based projects

So I am not sure is there any file missing? Is this because I run on a windows system?  Thank you very much!

**Comment by ykirchhoff** [comment]
Hi @lordhjx,

the command you need to run to consolidate the folds is `nnUNet_determine_postprocessing`. I don't know about platipy, but you can also install nnUNet directly via pypi with pip install `pip install nnunet`, this will install nnUNet v1. Otherwise you can also clone the repository and install it yourself using `pip install -e .` inside the (local) repository.

Best,
Yannick
