### ISSUE TITLE
Is there any way for low resolution training for small cases?

### ISSUE THREAD

**Issue by iskenderkahramanoglu** [MIC-DKFZ/nnUNet#2015]
Hello!

I want to train a low resolution model, but my labels is too small.
When I try the training, the pseudo dice always being 0.0.
Is there any way for training low resolution model for small cases?
Thank you very much!

**Comment by aymuos15** [comment]
I believe the problem here is with your labels, not a low resolution model. 

For a simple test, try enlarging your labels and see if it works, then you can try accommodating for a lower resolution.

Also Remember - '''Note that not all U-Net configurations are created for all datasets. In datasets with small image sizes, the U-Net cascade (and with it the 3d_lowres configuration) is omitted because the patch size of the full resolution U-Net already covers a large part of the input images.'''

**Comment by iskenderkahramanoglu** [comment]
> I believe the problem here is with your labels, not a low resolution model.
> 
> For a simple test, try enlarging your labels and see if it works, then you can try accommodating for a lower resolution.
> 
> Also Remember - '''Note that not all U-Net configurations are created for all datasets. In datasets with small image sizes, the U-Net cascade (and with it the 3d_lowres configuration) is omitted because the patch size of the full resolution U-Net already covers a large part of the input images.'''

I checked my labels, there is no problem.
I tried to fullres training and the pseudo dice is almost 0.80.
But in lowres traning, it is always 0.0.
Fullres inference and save as nifti usually takes too much time, so I want to train lowres.
What can I do about this?
Or is there any way to discrease inference time in fullres.

**Comment by iskenderkahramanoglu** [comment]
Hi @FabianIsensee , do you have any idea about this?

**Comment by saikat-roy** [comment]
Hey @iskenderkahramanoglu. Can I ask why you are trying to train a low-resolution model if your volumes don't seem to be large enough to require the cascade? Are you primarily doing this to gain inference speed?
