### ISSUE TITLE
what does configure_rotation_dummyDA_mirroring_and_inital_patch_size() do?

### ISSUE THREAD

**Issue by hdnminh** [MIC-DKFZ/nnUNet#2021]
Hi Team,

1. What does the function [configure_rotation_dummyDA_mirroring_and_inital_patch_size()](https://github.com/MIC-DKFZ/nnUNet/blob/95e74d8f50fd84c570820917f31ad9c72d30910b/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py#L392C9-L392C67) do?

2. In that implementation, you said that " This function is stupid and certainly one of the weakest spots of this implementation. Not entirely sure how we can fix it.". Could you explain more?

3. What the variable **do_dummy_2d_data_aug** do?

4. In the implementation, do have:
```py
# todo this function is stupid. It doesn't even use the correct scale range (we keep things as they were in the
        #  old nnunet for now)
        initial_patch_size = get_patch_size(patch_size[-dim:],
                                            *rotation_for_DA.values(),
                                            (0.85, 1.25))
```

- what does **initial_patch_size** do? And what do you mean about the comment? 

5. And why we need 2 types of patch size in dataloader3d: **initial_patch_size** & **self.configuration_manager.patch_size** in **dl_tr** and **self.configuration_manager.patch_size** & **self.configuration_manager.patch_size** in **dl_val**

```py
dl_tr = nnUNetDataLoader3D(dataset_tr, self.batch_size,
                                       initial_patch_size,   <------
                                       self.configuration_manager.patch_size, <------
                                       self.label_manager,
                                       oversample_foreground_percent=self.oversample_foreground_percent,
                                       sampling_probabilities=None, pad_sides=None)

dl_val = nnUNetDataLoader3D(dataset_val, self.batch_size,
                                        self.configuration_manager.patch_size,    <------
                                        self.configuration_manager.patch_size,    <------
                                        self.label_manager,
                                        oversample_foreground_percent=self.oversample_foreground_percent,
                                        sampling_probabilities=None, pad_sides=None)
```

I truly need your help as soon as possible.

Thank you so much for the great work.

**Comment by hdnminh** [comment]
Hey @FabianIsensee 
Please help me as soon as possible.

Thank you so much.

**Comment by hdnminh** [comment]
Hi @FabianIsensee,
please hellp meeee.

**Comment by FabianIsensee** [comment]
Hey there, please be patient. This is not a commercial product you are paying a lot of money for.

1. This function sets some heuristics regarding data augmentation. You are asking about its component sin the subsequent points so I am not going to repeat this here
2. The implementation is a heuristic, it's not perfect and there might be room for improvement
3. do_dummy_2d_data_aug determines whether we should do dummy 2D augmentation. This means that the spatial transform will only be applied in-plane whereas the low resolution axis will not receive augmentation. Effectively reducing it to 2D
4. When applying spatial augmentations (like for example rotations) and the patch size you want is the same as you start with then you will receive a lot of 'black corners' because the rotated image is out of bounds of the original image. So it's better to start with a larger patch from which you can then extract a smaller but rotated etc patch.
5. same answer as 4

Hope this helps.
Best,
Fabian
