### ISSUE TITLE
ModuleNotFoundError: No module named 'nnunetv2'

### ISSUE THREAD

**Issue by kennyha85** [MIC-DKFZ/nnUNet#2022]
Hi all,

I got a bug when I run:

`python nnunetv2/run/run_training.py 200 3d_fullres 0 --c -tr nnUNetTrainer_250epochs`

current dir is:
`/data/ha/Rim_lesion/Rim_segmentation/nnUNetv2`

with nnunetv2 is a sub folder which can be seen by ls 

and the output is: 

```
Traceback (most recent call last):
  File "/data/ha/Rim_lesion/Rim_segmentation/nnUNetv2/nnunetv2/run/run_training.py", line 5, in <module>
    import nnunetv2
ModuleNotFoundError: No module named 'nnunetv2'
```

I type python and import nnunetv2 from terminal, it works

I export a linux environment path:
 export PYTHONPATH="/data/ha/Rim_lesion/Rim_segmentation/nnUNetv2"

the error  "No module named 'nnunetv2'" disappears but it runs into other bug:
```

 import dynamic_network_architectures
ModuleNotFoundError: No module named 'dynamic_network_architectures'
```

does any one have suggestion for solving this.
Thank you very much.

**Comment by GregorKoehler** [comment]
Hi @kennyha85 ,

It seems like you are facing issues with module imports when trying to run your training script for nnU-Net. The first problem with the nnunetv2 module not being found appears to have been solved by setting the PYTHONPATH. Now, you are encountering a similar issue with another module: dynamic_network_architectures. Here are a few steps you can take to troubleshoot and potentially resolve this issue:

Update PYTHONPATH:
Since setting the PYTHONPATH resolved your first import issue, it might be necessary to ensure all dependent module paths are included. If dynamic_network_architectures is located in another directory, add that directory to PYTHONPATH as well.

Check Python Environment:
Sometimes, running scripts from different terminals or environments can lead to discrepancies in the modules that are available. Make sure that the Python interpreter you are running your script with is the same one where the modules are installed.

Virtual Environment:
Consider using a virtual environment if you're not already. This can help manage dependencies more cleanly and avoid conflicts with other projects or system packages. You can create and activate a virtual environment as follows:
```

python -m venv myenv
source myenv/bin/activate
```

After activation, try installing your dependencies within this environment.

**Comment by GregorKoehler** [comment]
Closing this issue for now, as it was stale for roughly a week. Please feel free to re-open if you're still facing this issue!
