### ISSUE TITLE
Could you explain file pickle of each case preprocessed by nnUNet?

### ISSUE THREAD

**Issue by hdnminh** [MIC-DKFZ/nnUNet#2024]
Hi Team,

1. What is class_locations, crop_bbox, use_nonzero_mask_for_norm?

2. What is class_locations, crop_bbox, use_nonzero_mask_for_norm, size_after_cropping, size_after_resampling used for?

3. Why does "classes": [ -1.0,  0.0, 1.0] have 3 values while my dataset has only 2 labels: background and the main organ.
```json
{
    "original_size_of_raw_data": [
        29,
        384,
        384
    ],
    "original_spacing": [
        3.0002601146698,
        0.4687559902667999,
        0.46875065565109253
    ],
    "list_of_data_files": [
        "/home/hdnminh/Documents/context-based-continual-learning/data/nnUNet_raw_data_base/nnUNet_raw_data/Task121_UCL/imagesTr/Case01_0000.nii.gz"
    ],
    "seg_file": "/home/hdnminh/Documents/context-based-continual-learning/data/nnUNet_raw_data_base/nnUNet_raw_data/Task121_UCL/labelsTr/Case01_0000.nii.gz",
    "itk_origin": [
        -93.0374984741211,
        -64.0438003540039,
        -138.27000427246094
    ],
    "itk_spacing": [
        0.46875065565109253,
        0.4687559902667999,
        3.0002601146698
    ],
    "itk_direction": [
        0.999997891895637,
        -9.691366181747261e-05,
        0.0020510514814995316,
        0.0011280354364155353,
        0.8605794796495506,
        -0.5093149312863127,
        -0.0017157331773990214,
        0.5093161589954228,
        0.8605777675240273
    ],
    "crop_bbox": [
        [
            0,
            29
        ],
        [
            0,
            384
        ],
        [
            0,
            384
        ]
    ],
    "classes": [
        -1.0,
        0.0,
        1.0
    ],
    "size_after_cropping": [
        29,
        384,
        384
    ],
    "use_nonzero_mask_for_norm": {
        "0": false
    },
    "size_after_resampling": [
        29,
        346,
        346
    ],
    "spacing_after_resampling": [
        3.0002601146698,
        0.5208333134651184,
        0.5208333134651184
    ],
    "class_locations": {
        "1": [[],[],....[]]
		}
}

```

**Comment by FabianIsensee** [comment]
Hey, I'd like to encourage you to find such answers in the code. That is certainly faster than for one of us to step in and explain it :-)
- class_locations is a dictionary that contains the coordinates of randomly selected pixels belonging to the classes (or regions). It is used to sample foreground patches (instead of running np.where all the time which eats up a lot of CPU and would require us to have the whole segmentation in memory)
- crop_bbox is there so that we remember where the case was cropped during preprocessing. This is used to place the predicted segmentation back into the proper coordinate system. Cropping is only relevant for datasets where the images have a lot of 0-valued pixels around a central nonzero region, such as BraTS.
- use_nonzero_mask_for_norm if we cropped a lot during preprocessing, use a mask of nonzero image pixels to normalize the image and leave all 0-valued pixels at 0. Relevant for brats etc only where we want to normalize the brain but not the black background
- size_after_cropping size after cropping (but before resampling to target spacing)
- size_after_resampling does not exist
- -1 is nonzero mask (see above), 0 is background, 1 is your foreground class

Best,
Fabian
