### ISSUE TITLE
Not sure which folder's checkpoint is the best

### ISSUE THREAD

**Issue by SodaCool7** [MIC-DKFZ/nnUNet#2030]
Hi, 

I have run four configurations, 2d, 3d_fullres, 3d-lowres, and 3d_cascade_fullres. For each configuration, there are 5 folders. Each folder has one best checkpoint and one final checkpoint. I am not sure how to choose the checkpoint which has the best performance.

Then, I ran the code of `nnUNetv2_find_best_configuration`, `nnUNetv2_ensemble`, and `nnUNetv2_apply_postprocessing`. But, I do not know where I could find the checkpoint after being ensembled. 

Looking forword your answers soon. 

Best wishes
max

**Comment by seziegler** [comment]
Hi Max,

when you run `nnUNetv2_predict` an ensemble of all you available folds within your specified configuration will be used automatically.
There cannot be a checkpoint of your ensemble because ensembling is done by averaging the individual predictions from each fold. So you still need the individual checkpoints.

Best,
Sebastian
