### ISSUE TITLE
"joint region" within `remove_all_but_the_largest_connected_component`

### ISSUE THREAD

**Issue by tjhendrickson** [MIC-DKFZ/nnUNet#2035]
Hello,

I'm looking at the `remove_all_but_the_largest_connected_component` within the script `connected_components.py`. I'm using it to perform some postprocessing routines to my data. I'm trying to wrap my head around the concept of a "joint region" when classes are specified within the `for_which_classes` argument. I looked a little bit into the LiTS articles references within the nnUNet paper, but I couldn't figure it out.

Any help would be great!

Best,

-Tim

**Comment by FabianIsensee** [comment]
Hey Tim, 
depends on what you mean by joint region:
- this script will investigate 'remove all but the largest connected component' for each class/region separately AND it will do so for the entire foreground/background as well. Here foreground is defined as the mask of all non-background pixels
- if you use region-based training, the regions will be used instead of the individual classes
Best,
Fabian

**Comment by GregorKoehler** [comment]
Hi @tjhendrickson,

I'm closing this issue for the time being due it being stale for over a week. Feel free to re-open if the info above didn't clear things up!
