### ISSUE TITLE
ONNX export mode is set to TrainingMode.EVAL

### ISSUE THREAD

**Issue by nnagururu** [MIC-DKFZ/nnUNet#2040]
Anyone know why I'm getting the following error and if I should be concerned?

UserWarning: ONNX export mode is set to TrainingMode.EVAL, but operator 'instance_norm' is set to train=True. Exporting with train=True.

Thanks,

Nimesh

**Comment by FabianIsensee** [comment]
Don't worry about this. This is just from hiddenlayer where we generate the pdf visualizing the network architecture. It doesn't affect anything else.
Best,
Fabian

**Comment by nnagururu** [comment]
thanks!

**Comment by lyl-zzz** [comment]
Hello. I recently had the same warning issue when converting a nnunetv1 model to onnx. When I then converted the onnx model to tensorrt's engine, I realized that the model I converted had five outputs. Of these, the first four outputs appeared to be feature maps of the middle layer of the network, and only the last output was the one I needed. In order to get the inference results, I have to request five memory spaces, which increases the resource consumption of the inference and gives me a headache. I think the reason for the five outputs may have something to do with the TrainingModel of the setup of the transformation. I would like to ask if there is a solution to this.Thanks！
