### ISSUE TITLE
Ask something about inference and usage situation

### ISSUE THREAD

**Issue by jxhno1** [MIC-DKFZ/nnUNet#205]
Hi, FabianIsensee ,
Thank you for your V2 of the nnUNet especially contains DP and DDP methods during training, respectful in mind! 
After a test for predict_simple.py in V2 , i found a problem here, some little mistakes occured in code 
1.step_size parameter may not alias in code
2.code in pic below may traceback sometimes , y+=x may  use np.add(y, x, out=y, casting='unsafe')?
![add](https://user-images.githubusercontent.com/37684984/80497298-d46c6b00-899c-11ea-9752-ce00ce2bf014.png)
and sometimes x may be None in value? and may have **duh** warning?
![duh](https://user-images.githubusercontent.com/37684984/80498346-311c5580-899e-11ea-9414-57a40a7f1a03.png)
old version's predic_simple.py is right after my re-run on same data.
And one more thing, I would like to ask if this frame work can work well  when I want to run some tasks on the same machine, after we run a test, we found 2 tasks may be ok, but 3 is more! cpu bottleneck takeplace then. thank you and for your replay.

**Comment by FabianIsensee** [comment]
Hi,
what do you mean by `.step_size parameter may not alias in code`

I just fixed 2. That was my fault :-) It should work now.

You can run as many trainings on your PC as you have GPUs installed. But you need enough CPU power as well. There is no easy way of adjusting that because nnU-Net needs a specific amount of data augmentation and there is no easy way around that. 

The 'duh' appeard when keys loaded from a state dict do not match to a new architecture. This should only happen if you use DP and DDP models. I recommend not using them right now because they are very experimental!

Best,
Fabian

**Comment by jxhno1** [comment]
Thank you for your reply, and I will try by yours
![image](https://user-images.githubusercontent.com/37684984/80582175-d4be4200-8a40-11ea-8e6c-3dc3398f914c.png)
I mean a little mismatch when formal parameter named step, step_size used below

**Comment by FabianIsensee** [comment]
Hi,
please pull from github. This issue is not present in the most recent code.
Best,
Fabian

**Comment by jxhno1** [comment]
Sorry for my fault, that may not be updated in my code here.
thank you!
