### ISSUE TITLE
A question on exchanging label 1 and 2 in Dataset137_Bra21.py

### ISSUE THREAD

**Issue by TSbme** [MIC-DKFZ/nnUNet#2056]
The final result of these two lines of code, why isn't it that the points with values of 1 and 2 both become 2? 
![image](https://github.com/MIC-DKFZ/nnUNet/assets/115214830/c292450f-930d-4abf-8777-a8fa41e7cba4)

Why isn't it written in this following form?

seg_new[img_npy == 4] = 3
seg_new[img_npy == 2] = -1 # Temporarily change 2 to -1
seg_new[img_npy == 1] = 2
seg_new[img_npy == -1] = 1 # Then change -1 to 1

**Comment by TSbme** [comment]
Hi @GregorKoehler ,
Thanks for your reply!
The path is 'nnunetv2/dataset_conversion/Dataset137_BraTS21.py'
Please check the following fuction.
def convert_labels_back_to_BraTS(seg: np.ndarray):
    new_seg = np.zeros_like(seg)
    new_seg[seg == 1] = 2
    new_seg[seg == 3] = 4
    new_seg[seg == 2] = 1
    return new_seg

**Comment by FabianIsensee** [comment]
Nothing is overwritten and we need no temporary changes because we write to a new target array which is initialized with 0 and we read from the original segmentation.
The reason two labels are flipped is because of consistency with other brain tumor segmentation projects I was working with at the time. What order the labels are in doesn't matter. If you change it please remember to change the regions / region_class_order accordingly. My recommendation would be to leave things as they are

**Comment by GregorKoehler** [comment]
Hi @TSbme,

I hope Fabian answered your questions! I'll close the issue for now, but feel free to reopen if you need further clarification!
