### ISSUE TITLE
INFO: Prediction is too large for python process-process communication. Saving to file...

### ISSUE THREAD

**Issue by SuChenHong** [MIC-DKFZ/nnUNet#2091]
It's stuck here while you train the prediction part of the model. How can i solve it?

**Comment by mallikas1** [comment]
Hi! I have a similar issue. Did you figure out a way?

**Comment by Karol-G** [comment]
Hello @SuChenHong,

Thank you for using nnU-Net and reaching out with your issue.

To better understand and assist you, could you please provide more specific details about the task you are working on and the exact problem you encountered? Additionally, it would be helpful if you could share the full command line output related to this issue.

Looking forward to your response to help you resolve this.

Best regards,
Karol Gotkowski

**Comment by YUjh0729** [comment]
Hello @SuChenHong ，
I have a similar issue. Did you figure out a way?

**Comment by YUjh0729** [comment]
Hello @Karol-G ，
I encountered a very strange issue when using the nnUNetv2_predict command. The program can't proceed and is unable to output the prediction results.
These are the results I predicted on the cloud server,
`Predicting FLARE22_010:
perform_everything_on_device: True
0%| | 0/360 [00:00<?, ?it/s]resizing data, order is 3
data shape (1, 227, 512, 512)
11%|████████████████████▍ | 38/360 [00:05<00:48, 6.65it/s]resizing segmentation, order is 1 order z is 0
data shape (1, 227, 512, 512)
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 360/360 [00:54<00:00, 6.60it/s]
sending off prediction to background worker for resampling and export
done with FLARE22_010

Predicting FLARE22_011:
perform_everything_on_device: True
38%|██████████████████████████████████████████████████████████████████████████▊ | 23/60 [00:03<00:05, 6.61it/s]resizing data, order is 1
data shape (14, 250, 628, 628)
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 60/60 [00:08<00:00, 6.74it/s]
sending off prediction to background worker for resampling and export
done with FLARE22_011
resizing data, order is 1
data shape (14, 109, 430, 430)and these are the results I tested locally，The output is similar, but there are these two additional lines of output. Both environments are identical:torch2.0.1，cudu11.8，python3.10perform_everything_on_device: True Prediction on device was unsuccessful, probably due to a lack of memory. Moving results arrays to CPU`
<img width="712" alt="Snipaste_2024-08-07_10-27-05" src="https://github.com/user-attachments/assets/643bf4f9-115f-4d7b-84f5-40f31c35d591">
The CPU and GPU are no longer occupied, and the prediction results should already be in the CPU memory, but they cannot be exported to the output folder, causing the program to freeze and become stuck. This only happens in a few cases with larger data in Abdomen CT_3D. How do you predict larger data in Abdomen CT_3D?

**Comment by Karol-G** [comment]
Please open a separate issue for your problem as it is different to the issue of the original author. Thank you.
