### ISSUE TITLE
Question about patch sampling

### ISSUE THREAD

**Issue by dark16sider** [MIC-DKFZ/nnUNet#210]
How do you sample from let's say abdominal CT? Do you do random crop? I have seen in the default batch generator that you don't use random crops. Also, what does patch_center_dist_from_border do and what value should I set it for abdominal CT for both high resolution and low resolution.

**Comment by FabianIsensee** [comment]
Hi,
please have a look at our paper:
https://arxiv.org/abs/1904.08128

We select 67% of the samples in a batch randomly. The remaining 33% are guaranteed to contain some foreground class (uniform distribution over which class)

The way patch sampling and loading is implemented in nnU-Net is very complicated and I would prefer not to write several pages on how this is done :-) Note that the patch location is determined in DataLoader3D and that patch_center_dist_from_border is not used because random_crop=False (meaning the spatial uses center crop). The crop location is determined in DataLoader3D

Ideally you should just use the nnU-Net dataloader and not change anything unless you know what you are doing.

Best,
Fabian
