### ISSUE TITLE
get_no_augmentation issue

### ISSUE THREAD

**Issue by DaiyangLiu** [MIC-DKFZ/nnUNet#212]
Hi Fabian. Thanks for your awesome nnUNet!
I got a trouble when I trained 2d network for braTS19(By the way, I have read your papers about BraTS before).
I use **get_no_augmentation()** instead of **get_moreDA_augmentation()**.
Then I got an error below.
![image](https://user-images.githubusercontent.com/16055969/81470513-b238df80-921d-11ea-86e4-c2d0a0a9c106.png)

So I comment “batchgenerator_train.restart()” and “batchgenerator_val.restart()”.(Because there is no 'restart()' in get_moreDA_augmentation(). I thought it may be the reason.)

After commenting those codes, I got another error again.
![image](https://user-images.githubusercontent.com/16055969/81470625-35f2cc00-921e-11ea-8c9e-33388df9d1c2.png)

Could you please tell me how to deal with it? Pardon if this is a silly mistake.

**Comment by FabianIsensee** [comment]
Hi,
please update batchgenerators by using pip install --upgrade batchgenerators or pulling from the current master.
Also please use the official nnUNetTrainerV2_noDataAugmentation unless you you have fully read and understood all the code :-) Simply replacing the DA pipeline without adapting the trainer properly will not work.
Best,
Fabian

**Comment by DaiyangLiu** [comment]
Hi,Fabian!
Thank you very much! I'll try later.
Best,
Daiyang

**Comment by Giammarco07** [comment]
Hi, Fabian!
Sorry to open this issue again but... I successfully trained the network with no data augmentation, as you suggested doing, however when I try to test it with predict_simple.py, it gets stuck here:
![predict](https://user-images.githubusercontent.com/43208690/94241157-94da8880-ff14-11ea-8a40-ce5318eeccf0.jpg)

It's not a dataset problem, because I have successfully managed to train and then make predictions with predict_simple.py using the classic nnUNetTrainerV2. It seems to be something linked to "preprocess_save_to_queue". Do you think it's a memory problem? Or is it related to the different trainer? 

I take this opportunity to congratulate you on your work, it is superb in the details and really difficult to overcome in performance!

Best,
Giammarco
