### ISSUE TITLE
How to speed up the process of inference?

### ISSUE THREAD

**Issue by xinlong007** [MIC-DKFZ/nnUNet#214]
Thank you for your help before!
Is there any methods to speed up the process of inference?
I've set the tta to 0, and the inference becomed quicker than before but  the test time still cannot satisfy my goal.
Should I change the structure of nnUnet to reduce the quantity of parameters ?  
Is there any methods？

**Comment by JunMa11** [comment]
Have you tried to add [`--mode fastest`](https://github.com/MIC-DKFZ/nnUNet/blob/b38c69b345b2f60cd0d053039669e8f988b0c0af/nnunet/inference/predict.py#L599) at the end of the command?

**Comment by xinlong007** [comment]
> Have you tried to add [`--mode fastest`](https://github.com/MIC-DKFZ/nnUNet/blob/b38c69b345b2f60cd0d053039669e8f988b0c0af/nnunet/inference/predict.py#L599) at the end of the command?
Thank you!
please tell me which version of nnUnet? new or old?  I use the old version and the command cannot be added.

**Comment by JunMa11** [comment]
@xinlong007 
Sorry for the late reply.

I use V2.

**Comment by FabianIsensee** [comment]
`fast` and `fastest`  is not recommended because they do very specific things and only help if these things are actually the bottleneck. This is why I have not added them to the documentation.
If you need to speed up inference you can consider changing the step_size parameter or disabling test time data augmentation. Best to test your new settings on some validation set first to make sure you don't break anything.
Best,
Fabian
