### ISSUE TITLE
Questions about model accuracy

### ISSUE THREAD

**Issue by DW1003** [MIC-DKFZ/nnUNet#2225]
Hello,
I'm a newbie, what's the problem when I encounter this situation? Is it because I don't have enough data, or do I need to adjust some parameters? I probably have more than 100 pieces of data.I'm looking forward your reply!  Here is my output in slicer 5.6.2.

![image](https://github.com/MIC-DKFZ/nnUNet/assets/72432230/4885515e-725c-4968-8330-80719fc2039b)

Best,
Ruizine.

**Comment by ykirchhoff** [comment]
Hi Ruizine,

are you referring to the confusion between left and right, e.g. for the hips? This is due to mirroring nnUNet applies both during training and inference. You can turn of left/right mirroring, so that it does not confuse classes with this symmetry. See [here](https://github.com/MIC-DKFZ/nnUNet/blob/19ae215bc8fef6a95fdc166f9fc305558f2e3a74/nnunetv2/training/nnUNetTrainer/variants/data_augmentation/nnUNetTrainerNoMirroring.py) for the trainers you can use for that.

Best,
Yannick

**Comment by DW1003** [comment]
> Hi Ruizine,
> 
> are you referring to the confusion between left and right, e.g. for the hips? This is due to mirroring nnUNet applies both during training and inference. You can turn of left/right mirroring, so that it does not confuse classes with this symmetry. See [here](https://github.com/MIC-DKFZ/nnUNet/blob/19ae215bc8fef6a95fdc166f9fc305558f2e3a74/nnunetv2/training/nnUNetTrainer/variants/data_augmentation/nnUNetTrainerNoMirroring.py) for the trainers you can use for that.
> 
> Best, Yannick

Hi Yannick,

Thanks for your suggestion, I will try to use it.

Best,
Ruizine

**Comment by ykirchhoff** [comment]
Hi Ruizine,

happy to help. I will close the issue for now, feel free to reopen it or open another issue if there are any further problems.

Best,
Yannick
