### ISSUE TITLE
Hi, is there a way to print inference time? 

### ISSUE THREAD

**Issue by wyjzll** [MIC-DKFZ/nnUNet#2254]
Hi, thanks for the great work! I have trained my model and the results are pretty good! My question: To compare the speed of the nnUNet with prevalent 3D medical segmentation methods, is there a way to print inference time? 
Best

**Comment by JackRio** [comment]
If you check the `def predict_from_data_iterator` function in the inference folder I think you can add timesteps from the data loading until the predictions. If you want a rough estimate just follow the inference code you have written and wrap a function with time.time()

Maybe there is a better option but this should work to a certain degree of accuracy. Since nnUNet also sends the data to a background worker for resampling (In case you want to track those aspects as well).

**Comment by wyjzll** [comment]
> If you check the `def predict_from_data_iterator` function in the inference folder I think you can add timesteps from the data loading until the predictions. If you want a rough estimate just follow the inference code you have written and wrap a function with time.time()
> 
> 
> 
> Maybe there is a better option but this should work to a certain degree of accuracy. Since nnUNet also sends the data to a background worker for resampling (In case you want to track those aspects as well). 

Great, thanks! I'll try it.

**Comment by wyjzll** [comment]
I have a test dataset, n=500. I simply Subtracted the time of the last file creation from the time of the first file creation, and then calculate the average. Thank you all for the reply and great help, will try your ways definitely!

**Comment by ykirchhoff** [comment]
Hi @wyjzll,

that sounds good enough for a rough estimate :).
I will close this issue now, feel free to open a new issue in case you have any other questions.

Best,
Yannick
