### ISSUE TITLE
int32 overflow in compute_approx_vram_consumption

### ISSUE THREAD

**Issue by bertramRISC** [MIC-DKFZ/nnUNet#23]
Hi Fabian,

First of all - outstanding work! Having read your paper I am excited (and a bit anxious) to test nnUNet on our data set to use it - as suggested - as a baseline for our own 3D-UNet based segmentation architecture.
However, along the way I stumbled across an issue with the plan_and_preprocess_task.py scripts - specifically the get_properties_for_stage method that created a plan with unreasonable values for batch_size (negative) and patch_size (too large: 512x512x309). I traced the problem down to the compute_approx_vram_consumption method where a variable tmp flows over its int32 limit and ends up negative. Converting tmp to numpy.int64 solved the problem for me and now I end up with batch_size=2 and patch_size=96x60x128.

Kind regards,
Bertram

**Comment by bertramRISC** [comment]
I found a similar issue in ExperimentPlanner2D.plan_experiment where in the function get_properties_for_stage the variable dataset_num_voxels also overflows over its int32 limit causing the batch_size to end up negative. The issue can be fixed by appending dtype=np.int64 to the np.prod call.

**Comment by FabianIsensee** [comment]
Hi Bertram,
thank you so much for figuring this out and reporting the problem! Your dataset seems to have some unique properties that I have not yet seen before - which is why I have not noticed the overflow so far. Could you provide me with the numerical values for the input arguments you used to call compute_approx_vram_consumption? (patch_size, num_pool_per_axis, base_num_features, max_num_features, num_modalities, num_classes, pool_op_kernel_sizes). I would like to test it to make sure it is fixed.
I would also be very interested in the plans for your dataset. Maybe there is something in there that I could use to make nnU-Net better!? If you cannot send me the plans file, this output would already be a great help:

> {0: {'batch_size': 2, 'num_pool_per_axis': [5, 5, 5], 'patch_size': array([128, 128, 128]), 'median_patient_size_in_voxels': array([139, 169, 138]), 'current_spacing': array([1., 1., 1.]), 'original_spacing': array([1., 1., 1.]), 'do_dummy_2D_data_aug': False, 'pool_op_kernel_sizes': [[2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2]], 'conv_kernel_sizes': [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]}}

Ideally for both 2D and 3D. You can get these outputs using a command like this:
`python experiment_planning/plan_and_preprocess_task.py -t Task43_BraTS2019 -pf 8 -no_preprocessing 1`

Let me know how nnU-Net performs on your dataset. If it is a proper 3D dataset (not like ACDC or Prostate MRI) then you can ignore the 2D model and concentrate on the 3D models. I would be very interested in how well it performs!

Best,
Fabian

**Comment by bertramRISC** [comment]
No problem, the numerical values are:

> base_num_features = {int} 30
max_num_features = {int} 320
num_classes = {int} 3
num_modalities = {int} 1
num_pool_per_axis = {list} <class 'list'>: [6, 7, 7]
patch_size = {ndarray} [320 512 512]
pool_op_kernel_sizes = {list} <class 'list'>: [[1, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2]]

The plan output for 3D:
> {0: {'batch_size': 2, 'num_pool_per_axis': [4, 5, 5], 'patch_size': array([ 96, 160, 128]), 'median_patient_size_in_voxels': array([149, 229, 229]), 'current_spacing': array([3.10135546, 1.5567229 , 1.5567229 ]), 'original_spacing': array([1.5      , 0.6953125, 0.6953125]), 'do_dummy_2D_data_aug': False, 'pool_op_kernel_sizes': [[1, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2]], 'conv_kernel_sizes': [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]}, 1: {'batch_size': 2, 'num_pool_per_axis': [4, 5, 5], 'patch_size': array([ 96, 160, 128]), 'median_patient_size_in_voxels': array([309, 512, 512]), 'current_spacing': array([1.5      , 0.6953125, 0.6953125]), 'original_spacing': array([1.5      , 0.6953125, 0.6953125]), 'do_dummy_2D_data_aug': False, 'pool_op_kernel_sizes': [[1, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2]], 'conv_kernel_sizes': [[1, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]}}

The plan output for 2D:
> [{'batch_size': 12, 'num_pool_per_axis': [7, 7], 'patch_size': array([512, 512]), 'median_patient_size_in_voxels': array([309, 512, 512]), 'current_spacing': array([1.5      , 0.6953125, 0.6953125]), 'original_spacing': array([1.5      , 0.6953125, 0.6953125]), 'pool_op_kernel_sizes': [[2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2]], 'conv_kernel_sizes': [[3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3]], 'do_dummy_2D_data_aug': False}]

Some background: Our data set consists of abdominal CTA images where we segment the abdominal aorta lumen for subsequent bloodflow simulation. We developed an approach that utilizes 3DUnetCNN( more specifically your Isensee 2017 model) that we plan to publish in the next months. For this we would like to use nnUNet as a baseline. I am happy to share results once they are available.

Best,
Bertram

**Comment by FabianIsensee** [comment]
Hi Bertram,
thank you for sharing! I do not spot anything unusual in your dataset. Nothing I might not have encountered before. The plans look OK to me, too. So I should expect nnU-Net to work properly. I find it curious though that you have an issue with overflow because I have not seen it even for datasets that are larger (LiTS) than yours. 
If you can I recommend you run nnU-Net 100% as is without modifications first before you try to adapt things (in case you are planning to). nnU-Net is much more than the architecture it revolves around. In fact, the architecture is the least important part ;-) What makes nnU-Net strong is that everything goes hand in hand and that the entire pipeline is optimized as a whole. Separating some parts of it (like taking the architecture and using it somewhere else) will not give good results. If you feel like going to the painful process you could also integrate the 2017 model in nnU-Net and compare them using the same experimental setup. 
Let me know how the results are :-)
Best,
Fabian
