### ISSUE TITLE
Issue with num_parts and part_id in nnUNet v2 prediction

### ISSUE THREAD

**Issue by RewaaHummedi** [MIC-DKFZ/nnUNet#2358]
Hello,

I've encountered an issue while trying to speed up the inference process using the num_parts and part_id parameters in nnUNet v2.

**Steps to reproduce:**

- I have a dataset with 6000 cases.
- I set num_parts=5 and part_id=4 to distribute the prediction process across 5 parts.
- When running the inference, only 1200 cases were processed instead of the entire dataset.

**Expected behavior:**
All 6000 cases should be processed across the 5 parts, with each part handling 1200 cases.

**Actual behavior:**
Only the 1200 cases for part_id=4 were processed, and the remaining cases were not processed.

**Code snippets:**

![Screenshot 2024-07-09 092016](https://github.com/MIC-DKFZ/nnUNet/assets/151827895/e9c3a724-43d7-4eac-bb90-7ef9bae0fa5d)

**Output logs:**

![Screenshot 2024-07-09 092056](https://github.com/MIC-DKFZ/nnUNet/assets/151827895/063b04cc-7a45-482d-b598-0be07cf49f27)

**Additional context:**
I expected each part to process 1200 cases, resulting in all 6000 cases being processed. However, only the cases for part_id=4 were processed.

**Is there something I'm missing in the setup, or is this a potential bug in the code?**

Thank you for your assistance!

**Comment by GregorKoehler** [comment]
Hi @RewaaHummedi ,

from what I gather in your description, you did use the `-num_parts` and `-part_id` options, but only ran the command for the last part?
Using this option to split inference into parts expects you to run each part individually, so with 5 parts you now have 5 runs each processing 1/5 of the samples. This allows you e.g. to submit the individual inference runs to different machines in order to speed up the inference. So if you only ran inference for one part ID, processing 1/5 (1200 samples in your case) is the intended behavior.

**Comment by GregorKoehler** [comment]
I'm closing this issue as it's been stale for a while now. Please feel free to re-open if you still encounter this problem and the approach provided above didn't resolve your issue!
