### ISSUE TITLE
How to train cascade model if the lowres model is already trained but the predicted_next_stage has been deleted? 

### ISSUE THREAD

**Issue by manyu252** [MIC-DKFZ/nnUNet#2371]
Hi,

I ran a lowres model with fold=all on my dataset a while back. I have the results and the summary.json file too. The predicted_next_stage (presumably for training cascade) has been deleted by mistake over time and is nonexistent. I want to run the cascade model on top of this lowres model but it gives me an error that the path predicted_next_stage does not exist.

What can I do to fix this issue? Do I need to re-train the lowres model again or is there some shorter way to do this?

Thank you,
Abhi

**Comment by GregorKoehler** [comment]
HI @manyu252 ,

I'm afraid you will have to re-run the low-res model, since the folder `predicted_next_stage` contains the predictions required for the cascade model in the next stage. I'll close this issue, as I don't see a different option other than re-training.

Please feel free to re-open this issue if you still encounter problems once the predictions for the next stage are present.

**Comment by manyu252** [comment]
> HI @manyu252 ,
> 
> I'm afraid you will have to re-run the low-res model, since the folder `predicted_next_stage` contains the predictions required for the cascade model in the next stage. I'll close this issue, as I don't see a different option other than re-training.
> 
> Please feel free to re-open this issue if you still encounter problems once the predictions for the next stage are present.

Okay thank you for your response!
