### ISSUE TITLE
Occurs in inference process.

### ISSUE THREAD

**Issue by Joevaen** [MIC-DKFZ/nnUNet#250]
Hi!!! @FabianIsensee 
Below is where the error happened.After I use fold_0 to train(lack of dataset) and predict one xxxx.0000.nii.gz in imagesTs., What to do with the consolidate_folds?

![20](https://user-images.githubusercontent.com/46133615/86556270-6e482980-bf85-11ea-808f-21b7e18dc061.PNG)

![21](https://user-images.githubusercontent.com/46133615/86556298-8029cc80-bf85-11ea-937a-ba0a758bdcad.PNG)

**Comment by FabianIsensee** [comment]
You can ignore this. Postprocessing can only be determined if you have the full 5-fold cv.
Best,
Fabian

**Comment by Joevaen** [comment]
Oh，I get it.Thanks! So how to inference with my model trained via fold_0? Did I have to train via 5f another time?

**Comment by FabianIsensee** [comment]
You can just run inference, no problem. Specify `-f 0` when running the command so that nnunet knows to only use that fold. You will not have access to postprocessing, but that does not make much of a difference anyways.
My recommendation is however to always run the 5 fold cv, especially when there is only little data available!
Best,
Fabian

**Comment by Joevaen** [comment]
> You can just run inference, no problem. Specify `-f 0` when running the command so that nnunet knows to only use that fold. You will not have access to postprocessing, but that does not make much of a difference anyways.
> My recommendation is however to always run the 5 fold cv, especially when there is only little data available!
> Best,
> Fabian

OK!Thank you so much!!!
