### ISSUE TITLE
Script for inference with any pre trained model

### ISSUE THREAD

**Issue by GXcells** [MIC-DKFZ/nnUNet#2541]
Could you add a script for inference on any dataset using any pretrained model?

I don't understand why we have to export a model as zip and "install" it from zip? Why can't we just use the model , a folder with images and run that?

**Comment by ykirchhoff** [comment]
Hi @GXcells,

the export to zip and install from zip are just an easy way nnUNet offers for model sharing. What you are looking for is also possible with the `nnUNetv2_predict_from_modelfolder` command, which just expects a basic structure of your modelfolder, so that it is compatible with nnUNet.

Best,
Yannick
