### ISSUE TITLE
Hi, Fabian! A new question here!

### ISSUE THREAD

**Issue by Joevaen** [MIC-DKFZ/nnUNet#255]
I want to konw why inference process is so slow.And what oprations are done during inference? Especially, I am curious about what the "computing Gaussian" was doing. Can you help me with this? Did this process is done in CPU?And what should I do to speed it up? Whether Moving the process to GPU works or not? Will Speed method like TensorRT work?
![25](https://user-images.githubusercontent.com/46133615/87005538-ba97a180-c1f1-11ea-8ae7-22815ad8a6e3.png)

Thank you!
Joevaen

**Comment by FabianIsensee** [comment]
Hi,
if you want to speed up inference, set test time data augmentation to False. If you feel like experimenting a bit you can also increase the step_size. All of this will however reduce the quality of the segmentations
I have not played with TensorRT yet
Best,
Fabian

**Comment by Joevaen** [comment]
Hello, it's me!
Wake the question up! Does data augmentation excuted in CPU? Whether it is a choice to move this process to GPU for a better speed？
Another, if I have done an inferrence for one patient last night, whether the plan generated can be used for a new inference today(same ct machine and parameters)? Do these two inferences have the same data fingerprint? What about pipeline fingerprint? It is really valuable in clinical medical therapy and a good to speed up. Thank you!
Best ragards,
Joevaen

**Comment by FabianIsensee** [comment]
Hi,
data augmentation is done on CPU. This should be OK if your system has a proper CPU but can cause problems if the CPU is too weak. It cannot be moved to GPU (and I don't think that would be a good idea as of now).
I don't understand your question about inference. Inference has nothing to do with the dataset fingerpring. The fingerprint is only based on the training cases.
fold_4 means what it says: it's the fifth fold our of the 5-fold cv. You need fold_0, fold_1, ..., and fold_4 (these 5 yogether are the cv).
If you use "-f 5" it will ginve an error because fold_5 does not exist. If you want to use only some folds, you can specify that with `-f 0 2 4`

**Comment by Joevaen** [comment]
> Hi,
> data augmentation is done on CPU. This should be OK if your system has a proper CPU but can cause problems if the CPU is too weak. It cannot be moved to GPU (and I don't think that would be a good idea as of now).
> I don't understand your question about inference. Inference has nothing to do with the dataset fingerpring. The fingerprint is only based on the training cases.
> fold_4 means what it says: it's the fifth fold our of the 5-fold cv. You need fold_0, fold_1, ..., and fold_4 (these 5 yogether are the cv).
> If you use "-f 5" it will ginve an error because fold_5 does not exist. If you want to use only some folds, you can specify that with `-f 0 2 4`

Thank you, Fabian! I have realized how stupid the questions are these two days. And I have got a really amazing result after some experienments.
