### ISSUE TITLE
Hi! Can I manually stop training earlier? 

### ISSUE THREAD

**Issue by onlie202** [MIC-DKFZ/nnUNet#283]
It takes too much time to run all 1000 epochs. I hope to stop it earlier.

**Comment by Joevaen** [comment]
Hi, onlie202!
If you run training in a terminal, just close it at any time(make sure the model at this time is properly useful). I think your question is how to inference with your model when your training epoch is under 1000. You should enter the output directory of your model to find 4 files named "model_best.model", "model_best.model.pkl", "model_latest.model" and "model_latest.model.pkl". The former 2 is a couple which caused a best validate loss and the latter 2 is another couple which saved at the final epoch before your training stops. You should change the name of one couple to "model_final_checkpoint.model" and "model_final_checkpoint.model.pkl". Then you can excute your inference with this model by command line.  
Is this the question you encountered?

**Comment by onlie202** [comment]
Perfectly it works! But another problem I encountered is that prediction also took much time. Is that common ?

**Comment by Joevaen** [comment]
> Perfectly it works! But another problem I encountered is that prediction also took much time. Is that common ?

Yes, it is common.Because the developer of nnUNet didn't focus on the speed. I have done some work about acceleration. If you are interested in my work. You can keep your eyes on me by following my csdn account(if you are a Chinese) .[https://blog.csdn.net/weixin_42061636/article/details/107623757](url) I think maybe you can learn a lot from my blog.: )

**Comment by onlie202** [comment]
关注了！
