### ISSUE TITLE
How about loading the best model when the final model is not available

### ISSUE THREAD

**Issue by JunMa11** [MIC-DKFZ/nnUNet#287]
Hi Fabian,

Sometimes, we do not want to train the model with 1000 epochs because it's time-consuming.
As an alternative, we want to manually stop the training and use the best checkpoint to infer testing sets.

So, how about adding the following two lines in `load_model_and_checkpoint_files`?

```
    if os.path.exists(join(folds[0], "%s.model.pkl" % checkpoint_name)) is not True:
        checkpoint_name = "model_best"
```

https://github.com/MIC-DKFZ/nnUNet/blob/10e9fea1ed8150d53748648f8eb88ced33747bac/nnunet/training/model_restore.py#L140

Best,
Jun

**Comment by FabianIsensee** [comment]
Hi Jun,
I don't think this will be a good idea because this can cause unintended behavior when running inference with a model that has not finished training yet. While most people will have a good overview of their experiments, I for example have not: with so many experiments and datasets it could happen that I am inadvertently inferencing with the wrong model and I would rather have it crash instead.
I have pushed changes to nnUNet_predict (and predict_simple.py) now which allow you to specify a checkpoint name when running them. You can use this to specify the best checkpoint instead of the final.
Best,
Fabian

**Comment by JunMa11** [comment]
Hi Fabian,

Thanks so much for adding the checkpoint argument.

Best,
Jun
