### ISSUE TITLE
changing hyperparameters

### ISSUE THREAD

**Issue by JordinaAviles** [MIC-DKFZ/nnUNet#297]
Hi Fabian!

I am trying to do transfer learning with the network and I need to modify the depth of the network. To do so, I modify the hyperparameters in the plans pkl file (conv_kernel_sizes, num_pool_per_axis and pool_op_kernel sizes) like this:

Original

{0: {'batch_size': 2, 'num_pool_per_axis': [4, 3, 4], 'patch_size': array([160,  56, 128], dtype=int64), 'median_patient_size_in_voxels': array([158,  50, 118], dtype=int64), 'current_spacing': array([2.5, 2.5, 2.5]), 'original_spacing': array([2.5, 2.5, 2.5]), 'do_dummy_2D_data_aug': False, 'pool_op_kernel_sizes': [[2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2]], 'conv_kernel_sizes': [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]}}

Modified

{0: {'batch_size': 2, 'num_pool_per_axis': [4, 3, 4], 'patch_size': array([160,  56, 128], dtype=int64), 'median_patient_size_in_voxels': array([158,  50, 118], dtype=int64), 'current_spacing': array([2.5, 2.5, 2.5]), 'original_spacing': array([2.5, 2.5, 2.5]), 'do_dummy_2D_data_aug': False, 'pool_op_kernel_sizes': [[2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2]], 'conv_kernel_sizes': [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]}}

When I run the training I obtain this error:

2020-08-18 10:08:11.812197:
epoch:  0
Traceback (most recent call last):
  File "/hpc/javi485/anaconda3/bin/nnUNet_train", line 11, in <module>
    load_entry_point('nnunet', 'console_scripts', 'nnUNet_train')()
  File "/hpc_htom/javi485/nnUNet/nnunet/run/run_training.py", line 142, in main
    trainer.run_training()
  File "/hpc_htom/javi485/nnUNet/nnunet/training/network_training/nnUNetTrainerV2.py", line 387, in run_training
    ret = super().run_training()
  File "/hpc_htom/javi485/nnUNet/nnunet/training/network_training/nnUNetTrainer.py", line 318, in run_training
    super(nnUNetTrainer, self).run_training()
  File "/hpc_htom/javi485/nnUNet/nnunet/training/network_training/network_trainer.py", line 445, in run_training
    l = self.run_iteration(self.tr_gen, True)
  File "/hpc_htom/javi485/nnUNet/nnunet/training/network_training/nnUNetTrainerV2.py", line 241, in run_iteration
    output = self.network(data)
  File "/hpc/javi485/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/hpc_htom/javi485/nnUNet/nnunet/network_architecture/generic_UNet.py", line 400, in forward
    x = torch.cat((x, skips[-(u + 1)]), dim=1)
  File "/hpc/javi485/anaconda3/lib/python3.7/site-packages/apex-0.1-py3.7.egg/apex/amp/wrap.py", line 81, in wrapper
    return orig_fn(seq, *args, **kwargs)
RuntimeError: Sizes of tensors must match except in dimension 3. Got 7 and 8

How can I solve that?

Thank you in advance,

Jordina

**Comment by WonderSimiliar** [comment]
I modified the  plans pkl file too. batch size = 2 -->1; patch size = [40,353,176] -->[74, 650, 324]

original:
_{0: {'batch_size': 2, 'num_pool_per_axis': [3, 4, 4], 'patch_size': array([ 40, 352, 176]), 'median_patient_size_in_voxels': array([ 65, 543, 279]), 'current_spacing': array([3.68213719, 3.68213719, 3.68213719]), 'original_spacing': array([1., 1., 1.]), 'do_dummy_2D_data_aug': True, 'pool_op_kernel_sizes': [[2, 2, 2], [2, 2, 2], [2, 2, 2], [1, 2, 2]], 'conv_kernel_sizes': [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]}, 
1: {'batch_size': 2, 'num_pool_per_axis': [3, 4, 4], 'patch_size': array([ 40, 352, 176]), 'median_patient_size_in_voxels': array([ 238, 1999, 1026]), 'current_spacing': array([1., 1., 1.]), 'original_spacing': array([1., 1., 1.]), 'do_dummy_2D_data_aug': True, 'pool_op_kernel_sizes': [[2, 2, 2], [2, 2, 2], [2, 2, 2], [1, 2, 2]], 'conv_kernel_sizes': [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]}}_

after modified:
_stage:  0
{'batch_size': 1, 'num_pool_per_axis': [3, 4, 4], 'patch_size': array([ 74, 650, 324]), 'median_patient_size_in_voxels': array([ 65, 543, 279]), 'current_spacing': array([3.68213719, 3.68213719, 3.68213719]), 'original_spacing': array([1., 1., 1.]), 'do_dummy_2D_data_aug': True, 'pool_op_kernel_sizes': [[2, 2, 2], [2, 2, 2], [2, 2, 2], [1, 2, 2]], 'conv_kernel_sizes': [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]}

stage:  1
{'batch_size': 1, 'num_pool_per_axis': [3, 4, 4], 'patch_size': array([ 74, 650, 324]), 'median_patient_size_in_voxels': array([ 238, 1999, 1026]), 'current_spacing': array([1., 1., 1.]), 'original_spacing': array([1., 1., 1.]), 'do_dummy_2D_data_aug': True, 'pool_op_kernel_sizes': [[2, 2, 2], [2, 2, 2], [2, 2, 2], [1, 2, 2]], 'conv_kernel_sizes': [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]}_

and **I got the similiar error as follows**:
_###############################################
I am running the following nnUNet: 3d_fullres
My trainer class is:  <class 'nnunet.training.network_training.nnUNetTrainerV2_DP.nnUNetTrainerV2_DP'>
For that I will be using the following configuration:
num_classes:  1
modalities:  {0: 'Fluorescence Microscope'}
use_mask_for_norm OrderedDict([(0, False)])
keep_only_largest_region None
min_region_size_per_class None
min_size_per_class None
normalization_schemes OrderedDict([(0, 'nonCT')])
stages...

stage:  0
{'batch_size': 1, 'num_pool_per_axis': [3, 4, 4], 'patch_size': array([ 74, 650, 324]), 'median_patient_size_in_voxels': array([ 65, 543, 279]), 'current_spacing': array([3.68213719, 3.68213719, 3.68213719]), 'original_spacing': array([1., 1., 1.]), 'do_dummy_2D_data_aug': True, 'pool_op_kernel_sizes': [[2, 2, 2], [2, 2, 2], [2, 2, 2], [1, 2, 2]], 'conv_kernel_sizes': [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]}

stage:  1
{'batch_size': 1, 'num_pool_per_axis': [3, 4, 4], 'patch_size': array([ 74, 650, 324]), 'median_patient_size_in_voxels': array([ 238, 1999, 1026]), 'current_spacing': array([1., 1., 1.]), 'original_spacing': array([1., 1., 1.]), 'do_dummy_2D_data_aug': True, 'pool_op_kernel_sizes': [[2, 2, 2], [2, 2, 2], [2, 2, 2], [1, 2, 2]], 'conv_kernel_sizes': [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]}

I am using stage 1 from these plans
I am using batch dice + CE loss

I am using data from this folder:  /home/ma-user/work/nnUNet-master/nnUNet_preprocessed/Task161_NerveRecon2/nnUNetData_plans_v2.1
###############################################
WARNING: self.batch_size < self.num_gpus. Will not be able to use the GPUs well
2020-08-19 15:16:11.420577: Using dummy2d data augmentation
unpacking dataset
done
2020-08-19 15:16:20.269454: lr: 0.01
Selected optimization level O1:  Insert automatic casts around Pytorch functions and Tensor methods.

Defaults for this optimization level are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Processing user overrides (additional kwargs that are not None)...
After processing overrides, optimization options are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Warning:  multi_tensor_applier fused unscale kernel is unavailable, possibly because apex was installed without --cuda_ext --cpp_ext. Using Python fallback.  Original ImportError was: ModuleNotFoundError("No module named 'amp_C'")
using pin_memory on device 0
using pin_memory on device 0
2020-08-19 15:27:27.788265: Unable to plot network architecture:
2020-08-19 15:27:27.788432: module 'torch.jit' has no attribute '_get_trace_graph'
2020-08-19 15:27:27.788493: 
printing the network instead:

2020-08-19 15:27:27.788530: DataParallel(
  (module): Generic_UNet_DP(
    (conv_blocks_localization): ModuleList(
      (0): Sequential(
        (0): StackedConvLayers(
          (blocks): Sequential(
            (0): ConvDropoutNormNonlin(
              (conv): Conv3d(512, 256, kernel_size=[3, 3, 3], stride=(1, 1, 1), padding=[1, 1, 1])
              (instnorm): InstanceNorm3d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
              (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
            )
          )
        )
        (1): StackedConvLayers(
          (blocks): Sequential(
            (0): ConvDropoutNormNonlin(
              (conv): Conv3d(256, 256, kernel_size=[3, 3, 3], stride=(1, 1, 1), padding=[1, 1, 1])
              (instnorm): InstanceNorm3d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
              (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
            )
          )
        )
      )
      (1): Sequential(
        (0): StackedConvLayers(
          (blocks): Sequential(
            (0): ConvDropoutNormNonlin(
              (conv): Conv3d(256, 128, kernel_size=[3, 3, 3], stride=(1, 1, 1), padding=[1, 1, 1])
              (instnorm): InstanceNorm3d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
              (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
            )
          )
        )
        (1): StackedConvLayers(
          (blocks): Sequential(
            (0): ConvDropoutNormNonlin(
              (conv): Conv3d(128, 128, kernel_size=[3, 3, 3], stride=(1, 1, 1), padding=[1, 1, 1])
              (instnorm): InstanceNorm3d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
              (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
            )
          )
        )
      )
      (2): Sequential(
        (0): StackedConvLayers(
          (blocks): Sequential(
            (0): ConvDropoutNormNonlin(
              (conv): Conv3d(128, 64, kernel_size=[3, 3, 3], stride=(1, 1, 1), padding=[1, 1, 1])
              (instnorm): InstanceNorm3d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
              (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
            )
          )
        )
        (1): StackedConvLayers(
          (blocks): Sequential(
            (0): ConvDropoutNormNonlin(
              (conv): Conv3d(64, 64, kernel_size=[3, 3, 3], stride=(1, 1, 1), padding=[1, 1, 1])
              (instnorm): InstanceNorm3d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
              (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
            )
          )
        )
      )
      (3): Sequential(
        (0): StackedConvLayers(
          (blocks): Sequential(
            (0): ConvDropoutNormNonlin(
              (conv): Conv3d(64, 32, kernel_size=[3, 3, 3], stride=(1, 1, 1), padding=[1, 1, 1])
              (instnorm): InstanceNorm3d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
              (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
            )
          )
        )
        (1): StackedConvLayers(
          (blocks): Sequential(
            (0): ConvDropoutNormNonlin(
              (conv): Conv3d(32, 32, kernel_size=[3, 3, 3], stride=(1, 1, 1), padding=[1, 1, 1])
              (instnorm): InstanceNorm3d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
              (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
            )
          )
        )
      )
    )
    (conv_blocks_context): ModuleList(
      (0): StackedConvLayers(
        (blocks): Sequential(
          (0): ConvDropoutNormNonlin(
            (conv): Conv3d(1, 32, kernel_size=[3, 3, 3], stride=(1, 1, 1), padding=[1, 1, 1])
            (instnorm): InstanceNorm3d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
            (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
          )
          (1): ConvDropoutNormNonlin(
            (conv): Conv3d(32, 32, kernel_size=[3, 3, 3], stride=(1, 1, 1), padding=[1, 1, 1])
            (instnorm): InstanceNorm3d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
            (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
          )
        )
      )
      (1): StackedConvLayers(
        (blocks): Sequential(
          (0): ConvDropoutNormNonlin(
            (conv): Conv3d(32, 64, kernel_size=[3, 3, 3], stride=[2, 2, 2], padding=[1, 1, 1])
            (instnorm): InstanceNorm3d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
            (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
          )
          (1): ConvDropoutNormNonlin(
            (conv): Conv3d(64, 64, kernel_size=[3, 3, 3], stride=(1, 1, 1), padding=[1, 1, 1])
            (instnorm): InstanceNorm3d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
            (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
          )
        )
      )
      (2): StackedConvLayers(
        (blocks): Sequential(
          (0): ConvDropoutNormNonlin(
            (conv): Conv3d(64, 128, kernel_size=[3, 3, 3], stride=[2, 2, 2], padding=[1, 1, 1])
            (instnorm): InstanceNorm3d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
            (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
          )
          (1): ConvDropoutNormNonlin(
            (conv): Conv3d(128, 128, kernel_size=[3, 3, 3], stride=(1, 1, 1), padding=[1, 1, 1])
            (instnorm): InstanceNorm3d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
            (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
          )
        )
      )
      (3): StackedConvLayers(
        (blocks): Sequential(
          (0): ConvDropoutNormNonlin(
            (conv): Conv3d(128, 256, kernel_size=[3, 3, 3], stride=[2, 2, 2], padding=[1, 1, 1])
            (instnorm): InstanceNorm3d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
            (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
          )
          (1): ConvDropoutNormNonlin(
            (conv): Conv3d(256, 256, kernel_size=[3, 3, 3], stride=(1, 1, 1), padding=[1, 1, 1])
            (instnorm): InstanceNorm3d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
            (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
          )
        )
      )
      (4): Sequential(
        (0): StackedConvLayers(
          (blocks): Sequential(
            (0): ConvDropoutNormNonlin(
              (conv): Conv3d(256, 320, kernel_size=[3, 3, 3], stride=[1, 2, 2], padding=[1, 1, 1])
              (instnorm): InstanceNorm3d(320, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
              (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
            )
          )
        )
        (1): StackedConvLayers(
          (blocks): Sequential(
            (0): ConvDropoutNormNonlin(
              (conv): Conv3d(320, 320, kernel_size=[3, 3, 3], stride=(1, 1, 1), padding=[1, 1, 1])
              (instnorm): InstanceNorm3d(320, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
              (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
            )
          )
        )
      )
    )
    (td): ModuleList()
    (tu): ModuleList(
      (0): ConvTranspose3d(320, 256, kernel_size=[1, 2, 2], stride=[1, 2, 2], bias=False)
      (1): ConvTranspose3d(256, 128, kernel_size=[2, 2, 2], stride=[2, 2, 2], bias=False)
      (2): ConvTranspose3d(128, 64, kernel_size=[2, 2, 2], stride=[2, 2, 2], bias=False)
      (3): ConvTranspose3d(64, 32, kernel_size=[2, 2, 2], stride=[2, 2, 2], bias=False)
    )
    (seg_outputs): ModuleList(
      (0): Conv3d(256, 2, kernel_size=(1, 1, 1), stride=(1, 1, 1), bias=False)
      (1): Conv3d(128, 2, kernel_size=(1, 1, 1), stride=(1, 1, 1), bias=False)
      (2): Conv3d(64, 2, kernel_size=(1, 1, 1), stride=(1, 1, 1), bias=False)
      (3): Conv3d(32, 2, kernel_size=(1, 1, 1), stride=(1, 1, 1), bias=False)
    )
    (ce_loss): CrossentropyND()
  )
)
2020-08-19 15:27:27.790529: 

2020-08-19 15:27:27.791570: 
epoch:  0
^[[BTraceback (most recent call last):
  File "/home/ma-user/work/venv/nnunet/bin/nnUNet_train_DP", line 11, in <module>
    load_entry_point('nnunet', 'console_scripts', 'nnUNet_train_DP')()
  File "/home/ma-user/work/nnUNet-master/nnunet/run/run_training_DP.py", line 145, in main
    trainer.run_training()
  File "/home/ma-user/work/nnUNet-master/nnunet/training/network_training/nnUNetTrainerV2_DP.py", line 170, in run_training
    ret = nnUNetTrainer.run_training(self)
  File "/home/ma-user/work/nnUNet-master/nnunet/training/network_training/nnUNetTrainer.py", line 318, in run_training
    super(nnUNetTrainer, self).run_training()
  File "/home/ma-user/work/nnUNet-master/nnunet/training/network_training/network_trainer.py", line 445, in run_training
    l = self.run_iteration(self.tr_gen, True)
  File "/home/ma-user/work/nnUNet-master/nnunet/training/network_training/nnUNetTrainerV2_DP.py", line 190, in run_iteration
    ret = self.network(data, target, return_hard_tp_fp_fn=run_online_evaluation)
  File "/home/ma-user/work/venv/nnunet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ma-user/work/venv/nnunet/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/ma-user/work/venv/nnunet/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/ma-user/work/venv/nnunet/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/home/ma-user/work/venv/nnunet/lib/python3.7/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/ma-user/work/venv/nnunet/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/ma-user/work/venv/nnunet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ma-user/work/nnUNet-master/nnunet/network_architecture/generic_UNet_DP.py", line 63, in forward
    res = super(Generic_UNet_DP, self).forward(x)  # regular Generic_UNet forward pass
  File "/home/ma-user/work/nnUNet-master/nnunet/network_architecture/generic_UNet.py", line 400, in forward
    x = torch.cat((x, skips[-(u + 1)]), dim=1)
  File "/home/ma-user/work/venv/nnunet/lib/python3.7/site-packages/apex/amp/wrap.py", line 81, in wrapper
    return orig_fn(seq, *args, **kwargs)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 41 and 42 in dimension 4 at /pytorch/aten/src/THC/generic/THCTensorMath.cu:71_

**Comment by WonderSimiliar** [comment]
And if I don't use multi GPU training, just use single GPU training
$ CUDA_VISIBLE_DEVICES=0 nnUNet_train 3d_fullres nnUNetTrainerV2 161 3 -p nnUNetPlansv2.1_BS1_PSL

There would be the similiar error:
Traceback (most recent call last):
  File "/home/ma-user/work/venv/nnunet/bin/nnUNet_train", line 11, in <module>
    load_entry_point('nnunet', 'console_scripts', 'nnUNet_train')()
  File "/home/ma-user/work/nnUNet-master/nnunet/run/run_training.py", line 142, in main
    trainer.run_training()
  File "/home/ma-user/work/nnUNet-master/nnunet/training/network_training/nnUNetTrainerV2.py", line 387, in run_training
    ret = super().run_training()
  File "/home/ma-user/work/nnUNet-master/nnunet/training/network_training/nnUNetTrainer.py", line 318, in run_training
    super(nnUNetTrainer, self).run_training()
  File "/home/ma-user/work/nnUNet-master/nnunet/training/network_training/network_trainer.py", line 445, in run_training
    l = self.run_iteration(self.tr_gen, True)
  File "/home/ma-user/work/nnUNet-master/nnunet/training/network_training/nnUNetTrainerV2.py", line 241, in run_iteration
    output = self.network(data)
  File "/home/ma-user/work/venv/nnunet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ma-user/work/nnUNet-master/nnunet/network_architecture/generic_UNet.py", line 400, in forward
    x = torch.cat((x, skips[-(u + 1)]), dim=1)
  File "/home/ma-user/work/venv/nnunet/lib/python3.7/site-packages/apex/amp/wrap.py", line 81, in wrapper
    return orig_fn(seq, *args, **kwargs)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 41 and 42 in dimension 4 at /pytorch/aten/src/THC/generic/THCTensorMath.cu:71

**Comment by WonderSimiliar** [comment]
If I only change batch size, do not change patch size, there is no error, the training is fine.

**Comment by FabianIsensee** [comment]
Hi,
please don't just change things in the plans file when you don't know exactly what you are doing. You are downsampling the data in a way that when they are back upsampled in the U-Net their sizes don't match the feature maps coming form the skip connections. Please use 
`nnUNet_plan_and_preprocess [...] -pl2d None -pl3d ExperimentPlanner3D_v21_32GB`
Best,
Fabian

**Comment by WonderSimiliar** [comment]
Thanks, Fabian!

**Comment by sbajpai2** [comment]
Hi @JordinaAviles  and @WonderSimiliar ,

You can look into [Models Genesis](https://github.com/MrGiovanni/ModelsGenesis/tree/master/competition) developed by our lab.
We provide pre-trained weights for nnUNet framework. (Transfer Learning) (https://github.com/MrGiovanni/ModelsGenesis/tree/master/competition)

Best,
Shivam
