### ISSUE TITLE
Problem with Cascade Training

### ISSUE THREAD

**Issue by Jiawei-Yang** [MIC-DKFZ/nnUNet#33]
Hey Fabian,

Thanks for your fantastic and brilliant work!

I recently encountered a problem when trying to run cascade training.

    ###############################################
    2019-07-17 15:23:20.822183: Using dummy2d data augmentation
    2019-07-17 15:23:22.990462: Using dummy2d data augmentation
    Traceback (most recent call last):
    File "run/run_training.py", line 96, in <module>
        trainer.initialize(not validation_only)
    File "nnUNet/nnunet/training/network_training/nnUNetTrainerCascadeFullRes.py", line 118, in initialize
        self.dl_tr, self.dl_val = self.get_basic_generators()
    File "nnUNet/nnunet/training/network_training/nnUNetTrainerCascadeFullRes.py", line 59, in get_basic_generators
        self.do_split()
    File "nnUNet/nnunet/training/network_training/nnUNetTrainerCascadeFullRes.py", line 49, in do_split
        "seg from prev stage missing: %s" % (self.dataset[k]['seg_from_prev_stage_file'])
    AssertionError: seg from prev stage missing: /nnUNet/nnUNet_preprocessed/Task00_Test/segs_prev_stage/00000_segFromPrevStage.npz

By looking into the code:

    if network == '3d_lowres':
        trainer.load_best_checkpoint(False)
        print("predicting segmentations for the next stage of the cascade")
        predict_next_stage(trainer, join(dataset_directory, trainer.plans['data_identifier'] + "_stage%d" % 1))

and jumping to `nnunet/training/cascade_stuff/predict_next_stage.py`
I found

    def predict_next_stage(trainer, stage_to_be_predicted_folder):
        output_folder = join(pardir(trainer.output_folder), "pred_next_stage")
        maybe_mkdir_p(output_folder)

        process_manager = Pool(2)
        results = []

        for pat in trainer.dataset_val.keys():
            print(pat)
            data_file = trainer.dataset_val[pat]['data_file']
            ......

Here, it seems that the `predict_next_stage` only processes the validation data, not training data.

For the convenience of comparing the performance of different models, I modified your code to fix the training sample IDs and validation sample IDs when `FOLD` is `all`. 

I guess I should attribute this problem to using `all` folds scheme. So there are no other cross-validation sets to form a complete segFromPrevStage set for the next stage. 

Is there any way to apply cascade training when previously using `all` for the lowRes model?

Best,
Jiawei

**Comment by FabianIsensee** [comment]
Hi there,
thank you for your kind words about nnU-Net. It is great to see so many people are working with it :-)
The second stage of the cascade needs to learn to correct errors from the previous stage (and it also needs to smooth out the interpolation artifacts). It can only do so if segFromPrevStage was generated on held out validation sets. Otherwise an overfitted network would produce too easy segmentation masks and the whole thing will not generalize. Therefore you should not use fold=all if you intend to run the cascade. I will add this to the documentation in the next days.
If you have issues with the amount of GPU resources available to you you could consider changing the 5-fold CV into a 3-fold CV.
In general the 3d cascade model was not so much better than the other models (3d_lowres and 3d_fullres). So unless you really need it you could also consider just using the simpler models.
Best,
Fabian

**Comment by Jiawei-Yang** [comment]
Hi Fabian,

Thanks for your comprehensive answers and so quick response.  I appreciate it a lot! Your work is just dominating the medical image segmentation problem.

I'll try 3-fold CV or 5-fold CV later on. 

I also got another problem that this code does not support multiple GPUs, right?

Best,
Jiawei

**Comment by FabianIsensee** [comment]
Dear Jiawei,
multiple GPUs are not supported right now. Due to the nature of "batch dice" this requires some additional coding and cannot be done quick and dirty with nn.DataParallel. I have a trainer class ready for multi GPU training and will add it in the upcoming weeks. Bear in mind though that a batch size of 2 (which is common for my 3D U-Nets) can only be distributed to two GPUs (less than one batch per GPU is not possible) so the speedup you can get by doing so is limited.
Best,
Fabian

**Comment by Jiawei-Yang** [comment]
Hi Fabian

Thanks again for your detailed explanation!

I just have learned so much from your work.
