### ISSUE TITLE
model weights ETA

### ISSUE THREAD

**Issue by bkonk** [MIC-DKFZ/nnUNet#339]
In the readme under **How to run inference with pretrained models** you mention `(work in progress! Model weights have not been uploaded yet!)`. Is there an estimate for when these weights will be made available? 

Thanks!

**Comment by FabianIsensee** [comment]
the statement is old. Models have been out for months now. Sorry :-D

**Comment by bkonk** [comment]
great, I was hoping that was the case! thanks!

**Comment by bkonk** [comment]
I downloaded the  LiTS model and tried the` nnUNet_find_best_configuration` command to find the inference command:

`nnUNet_find_best_configuration -m 2d 3d_fullres 3d_lowres 3d_cascade_fullres -t 029 --strict`

but received the following error:

AssertionError: Output folder for model 3d_lowres is missing, expected: /nnUNet_raw_data_base/nnUNet_trained_models/nnUNet/2d/Task029_LITS/nnUNetTrainerV2__nnUNetPlansv2.1/cv_niftis_raw/summary.json

Looks like the path to` cv_niftis_raw` exists, just the json file is missing. Is there a different step to generate this prior to finding the best configuration?

**Comment by FabianIsensee** [comment]
When you download the models the files required to run nnUNet_find_best_configuration are not available because they were generated during training. That is because I already ran nnUNet_find_best_configuration and the result are published in our paper (see Supplement). You do not have to run that and can simply use what the paper says.

If you really want to run it yourself, you need to have the lits training data and then run all the validations again (`nnUNet_train [...] -val`)

**Comment by bkonk** [comment]
thank you! Paper results will work just fine
