### ISSUE TITLE
How can I see preprocessed image when doing prediction?

### ISSUE THREAD

**Issue by Hitdahit** [MIC-DKFZ/nnUNet#343]
Hello Fabian, I'm using nnunet and it works so good for me. Thank you for developing such a nice model.

But one thing, when i use prediction command(which is nnUNet_predict ~~~) , this command seems like it does not save preprocessed image. But I want to see preprocessed image even when i'm performing inference.

How can I save preprocessed image when using nnUNet_predict?

**Comment by FabianIsensee** [comment]
Hi,
glad to hear you enjoy using nnU-Net!
Unfortunately there is no code for saving the preprocessed images. Even for the training cases there is no way of accessing the preprocessed images with a regular image viewer because they are saved as numpy arrays. You have to dive into the code yourself to make it save the preprocessed images.
Best,
Fabian

**Comment by Hitdahit** [comment]
Thank you so much!
