### ISSUE TITLE
Can I use pytorch 1.5 to run the latest nnUNet?

### ISSUE THREAD

**Issue by tea321000** [MIC-DKFZ/nnUNet#368]
As the server is installed with`cuda9.0` and I don't have administrator privileges on the server, I can only install the pytorch version 1.5 from the source and install `apex` manually as v1.6 requires `cuda9.2`. Can I use pytorch 1.5 to run the latest nnUNet, will this cause some problems?

**Comment by FabianIsensee** [comment]
Hi,
the newest nnunet will not run with pytorch 1.5 because it requires the amp module which does not exist prior to 1.6.
You should ask your admins to update your graphics driver. A newer cuda version is not required! (the cuda versionlisted in the top right corner of `nvidia-smi` is what's important.
You don't need apex anymore
Best,
Fabian

**Comment by tea321000** [comment]
Thank you, I already know the difference between the CUDA driver API and runtime API，and driver API can be backward compatible with runtime API. Unfortunately, my graphics card driver version is old and can only support up to CUDA9.1, I can only contact my administrator to solve this problem.
