### ISSUE TITLE
Questions on Cascade training

### ISSUE THREAD

**Issue by MichaelLempart** [MIC-DKFZ/nnUNet#375]
Hi Fabian and thanks for this great framework!

I just started to use it and I hoped that you could help me to understand some the cascade training part in more detail?

As far as I have understood, in cases where the original volume size is large compared to the patch size, a cascade Unet is used.

Does the ’stage’ parameter tell if a cascade is trained or not? e.g. when training in 3Dfullres, for my training set, the command line says stage0 and stage 1. 

According to your article, the first stage is trained on low resolution images. Does that mean that volumes are resampled and that the training is performed by randomly cropping images from the volume?

Iam also wondering how the second stage is connected to the first? 
Here is my understanding of the training process:
- train stage 0 for e.g 1000 epochs
- once the first stage is trained, take all low resolution training and validation images of the actual fold, predict a coarse segmentation, resample the coarse segmentation to their original size and save them to disk 
- now take the fullres input volumes (e.g CT) and concatenate them with the corresponding coarse segmentation
- now train the second stage on randomly cropped patches to refine the segmentations

If my understanding is correct, why does the second unet does not care about different voxel sizes (I guess this is a result of resampling the coarse segmentations?)

I would be really happy of you would take the time to answer some of my questions :-)

Cheers and best regards,

Michael

**Comment by FabianIsensee** [comment]
Hi Michael,
apologies for the late response.

> As far as I have understood, in cases where the original volume size is large compared to the patch size, a cascade Unet is used.

correct

> Does the ’stage’ parameter tell if a cascade is trained or not? e.g. when training in 3Dfullres, for my training set, the command line says stage0 and stage 1.

Yes. If there are two stages (0 and 1) then the cascade is intended to be used along with the other configurations

> According to your article, the first stage is trained on low resolution images. Does that mean that volumes are resampled and that the training is performed by randomly cropping images from the volume?

Yes. The volumes are downsampled and the first stage will be trained on the low resolution images. 


What is important to note about the cascade is that we always run the full 5 fold cross-validation on the low resolution. That means that we have low resolution predictions for all training cases. These are upsampled to the resolution of the second stage of the cascade (so that they have the same size as the preprocessed images). Then during training they are concatenated.

Best,
Fabian

**Comment by MichaelLempart** [comment]
Hi Fabian,

thanks for taking time to answer my questions:-)
That really makes things more clear.

Cheers, 

Michael
