### ISSUE TITLE
Metrics for absent regions in segmentation or ground truth

### ISSUE THREAD

**Issue by stalhabukhari** [MIC-DKFZ/nnUNet#380]
Hi Fabian,

This is more of a question rather than an issue, as I am trying to understand the conventions used in medical image segmentation.

I noticed that you used a set of conditions to handle special cases in calculation of segmentation metrics (e.g., in [Hausdorff Distance](https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunet/evaluation/metrics.py#L314)). I restate a snippet of the code below:
```python
if test_empty or test_full or reference_empty or reference_full:
    if nan_for_nonexisting:
        return float("NaN")
    else:
        return 0
```

I have the following questions regarding this:
- By default, what is the flag `nan_for_nonexisting` set to?
- If `nan_for_nonexisting=True`, then if `test_empty=True` and if `reference_empty=True`, the code returns `float("NaN")` while the correct hausdorff score should be `0`, indicating a perfect segmentation.
- If `nan_for_nonexisting=False`, then if `test_empty=True` and if `reference_empty=False` while `reference_full=False` as well (indicating that there was *some* segmentation), then such a segmentation should be **maximally** penalized, while the function returns a perfect score of `0`.
- About maximally penalizing a segmentation using Hausdorff Distance, I am unable to find any reference or guide (my use case is brain tumor segmentation). Using the `float("NaN")` will ignore the value in calculation of mean, and hence, the mean score may turn out to be *over-stated*.
- Another observation, regarding use of `float("NaN")`, is that if I am calculating the *Final Ranking Score* (FRS) of the BraTS challenges), I won't be sure of how to do per-subject ranking (of multiple methods segmenting a given test-set). The `pandas.DataFrame.rank()` method, by default, ignores the value, which may again provide an *over-stated* FRS. Would you happen to know about the right thing to do here?

Best Regards,
Talha

**Comment by FabianIsensee** [comment]
Hi Talha,
@jenspetersen can give you insights on the implementation of the evaluation. This was his work originally. I just modified a couple of things on top (multiprocessing). 
Regarding the BraTS ranking score I would like to point you to the BraTS2020 file: https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunet/dataset_conversion/Task082_BraTS_2020.py
It is very chaotic but somewhere in there is a reimplementation of the BraTS ranking. We used this to select our models for this years challenge. Our method won the competition - so the implementation is not completely off. 
Note that BraTS does not use nan, ever. They circumvent this problem by manually setting the scores in extreme cases. I have reimplemented that here https://github.com/MIC-DKFZ/nnUNet/blob/5c18fa32f2b31575aae59d889d196e4c4ba8b844/nnunet/dataset_conversion/Task082_BraTS_2020.py#L301 and here https://github.com/MIC-DKFZ/nnUNet/blob/5c18fa32f2b31575aae59d889d196e4c4ba8b844/nnunet/dataset_conversion/Task082_BraTS_2020.py#L330 for Dice and HD95, respectively.
Best,
Fabian

**Comment by jenspetersen** [comment]
Hi Talha!

* By default, what is the flag `nan_for_nonexisting` set to?

By default it's set to True.

* If `nan_for_nonexisting=True`, then if `test_empty=True` and if `reference_empty=True`, the code returns `float("NaN")` while the correct hausdorff score should be `0`, indicating a perfect segmentation.

The Hausdorff distance (and also the average surface distance) is undefined if either set is empty. The medpy implementation will actually raise a RuntimeError in that case, we choose to return NaN instead. But you're right, an empty segmentation is the desired behaviour if the reference is also empty, that's why we have the `nan_for_nonexisting` switch, so you can decide what should happen. Note that we treat full segmentations the same as empty segmentations here, because the surface is not really meaningful in that case. But that could absolutely be done differently. @FabianIsensee what do you think?

* If `nan_for_nonexisting=False`, then if `test_empty=True` and if `reference_empty=False` while `reference_full=False` as well (indicating that there was _some_ segmentation), then such a segmentation should be **maximally** penalized, while the function returns a perfect score of `0`.

Again, NaN would actually be the correct answer, because the HD is undefined. But I see how you would like to penalize this case. In this particular scenario, `nan_for_nonexisting=False` would be a poor choice. But what would be a good value? Should it be independent of the reference segmentation? Surely it should be smaller if the reference segmentation is also small. One could bound the value to the maximum distance between all points in the reference, but then there could be scenarios where it would be better to predict an empty segmentation instead of one that's a little too large. I think we just have to accept that the Hausdorff distance (and other surface distances) can't ideally judge every scenario.

* About maximally penalizing a segmentation using Hausdorff Distance, I am unable to find any reference or guide (my use case is brain tumor segmentation). Using the `float("NaN")` will ignore the value in calculation of mean, and hence, the mean score may turn out to be _over-stated_.

Yes, the idea of returning NaN is that you can later use something like np.nanmean to just ignore that value. This should obviously not be reported alone, but along with e.g. the error of the mean, which becomes larger of more values are ignored.

Hope that helps!

@FabianIsensee for the surface distances, `nan_for_nonexisting` switches between NaN and the best possible value, while for Dice et al. it switches between NaN and the worst possible value. We could consider returning 1 for those instead?

**Comment by FabianIsensee** [comment]
Hi Jens,
I am happy with the way Dice works at the moment. The way it currently is I can do whatever I want with the nans in post. If you set Dice to 0 or 1 some information will get lost.
I am not using HD95 but here again I would argue for nan. You can set it in post to whatever you like depending on the true positive and false negative statistics.
Best,
Fabian

**Comment by stalhabukhari** [comment]
Thank you @FabianIsensee and @jenspetersen !
Using a maximal penalization of `math.sqrt(240**2 + 240**2 + 155**2) = 373.12866` in the case of Hausdorff Distance makes sense to me. But using such a huge value causes the mean scores to be pretty off from the scores reported in papers.

How were the special cases treated in reporting mean scores in tables of [No New-Net (2018)](https://arxiv.org/pdf/1809.10483.pdf)? [Method 1](https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunet/evaluation/metrics.py#L314) or [Method 2](https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunet/dataset_conversion/Task082_BraTS_2020.py#L330)? Any other paper that reports the metrics similarly/differently?

**Comment by FabianIsensee** [comment]
We talk about this in our most recent BraTS paper (uploaded yesterday): https://arxiv.org/abs/2011.00848

Technically you should not use the mean values for comparing methods. But in the case of the Dice score this proxy is good enough. I don't know about HD95 though.

In No New Net we used the metric aggregation as reported by the validation platform. Back them the HD95 was not 373, though. They set it to 0 when you had a mistake (pred empty, gt not OR gt empty, pred not). If both pred and gt were empty they gave a nan and excluded it from the mean. I think this was a better way of handling this than the 373 value. The same goes for Dice. It should be 0 or nan and if it's nan it should be excluded from the mean. But this is not how the BraTS ranking works.

In context of the BraTS ranking, the 373 - 0 dichotomy (HD95) or 1 - 0  dichotomy (Dice) in cases where the reference is empty makes sense: you either get it right (best rank) or not (worst rank).

**Comment by stalhabukhari** [comment]
I checked out your latest work, which is pretty interesting and I completely agree with you; mean values cannot be used for comparing methods, which is also why I am interested in understanding how FRS works, especially given the special cases.

> Back them the HD95 was not 373, though. They set it to 0 when you had a mistake (pred empty, gt not OR gt empty, pred not).

This is boggling, as making a mistake is being incentivized instead of penalized. Anyway, thank you for your time.

**Comment by FabianIsensee** [comment]
I think what BraTS is doing makes perfect sense for their ranking. There is a lof of considerations you need to make in order to be able to incorporate these cases into the ranking. The fact that is beneficial to remove small enhancing tumor labels is a side-effect of that. But to be honest - I don't have an idea on how one could handle these cases better. Rank-then-aggregate is probably the best way of doing that.

The big problem to me is that BraTS is reporting these mean values, thus suggesting that they have value in evaluating models. They should not do that because this leads people into using those values for model selection (including me up until this year lol). On the other hand they need to report something back to the participants - otherwise the whole experience is going to be just frustrating. Using the actual BraTS ranking for the leaderboard (and display the ranking score) would be better, but not without flaws: the mean values remain constant and do not change as long as you don't change your model. Your ranking score (and your ranking) will change over time as more models are added to the leadrboard. Therefore, reporting your score has little value to someone who reads the publication in the future

**Comment by stalhabukhari** [comment]
> I think what BraTS is doing makes perfect sense for their ranking.

I agree with the convention used for rankings (1-0 for Dice, 0-373 for Hausdorff).

> The big problem to me is that BraTS is reporting these mean values, thus suggesting that they have value in evaluating models.

Agreed. There should be explicitly stated caveats wherever mean scores are reported and discussed.

> the mean values remain constant and do not change as long as you don't change your model. Your ranking score (and your ranking) will change over time as more models are added to the leadrboard. Therefore, reporting your score has little value to someone who reads the publication in the future

A valid observation!
