### ISSUE TITLE
Does the RTX3080 suffer from lack of VRAM on training nn-UNet models?

### ISSUE THREAD

**Issue by ai-animate** [MIC-DKFZ/nnUNet#384]
Hi, fabian
I might buy an RTX3080 recently, but its VRAM is only 10G, which is smaller than 2080TI. I don’t know if this will result in a smaller batch size and thus a decrease in performance. Is VRAM important for training nn-UNet models?

**Comment by FabianIsensee** [comment]
Hi,
nnU-net typically needs 8GB, sometimes 9GB. So the 3080 should work well. You can also configure nnU-Net to use less GPU memory in case is should not be enough (but I am pretty confident that 10G suffice).
Best,
Fabian

**Comment by FabianIsensee** [comment]
(wrong button)

**Comment by pkuppens** [comment]
@FabianIsensee, The 'Installation' section on this GitHub states 'For training nnU-Net models the GPU should have at least 11 GB' quite explicitly. (But I expect this would be only for the most complex networks?) Maybe a small re-edit of this statement, and point to the memory configuration section that tells how to lower the memory need?

@ai-animate , however, I also recall having read somewhere that 3080 will have GPU/CPU memory sharing options over PCIe. Not sure if this is initially with the launch, or with a driver update later, but this could be worth investigating.

@ai-animate, early next year I intend to buy a new deep learning capable setup that should be able to deal with nnUNet, and I am thinking of the 3080, so I am interested if you could are successful using 3080 for nnUNet.

**Comment by FabianIsensee** [comment]
You are right. I need to work some more on the documentation

> @ai-animate , however, I also recall having read somewhere that 3080 will have GPU/CPU memory sharing options over PCIe. Not sure if this is initially with the launch, or with a driver update later, but this could be worth investigating.

If you are referring to nvidias SAM clone then yes that will come. I am however not sure how this could affect deep neural network training. That seems more like a gaming oriented feature to me - but I am happy to be proven wrong

> @ai-animate, early next year I intend to buy a new deep learning capable setup that should be able to deal with nnUNet, and I am thinking of the 3080, so I am interested if you could are successful using 3080 for nnUNet.

Not sure if 3080 will still be the best choice by the start of next year. There are rumors about a 3080ti with 20GB of VRAM for ~999USD. I would go for that, because nnU-Net is probably not the only thing you will be running.

**Comment by pkuppens** [comment]
@FabianIsensee, on a different platform, I read the suggestion to consider 2x 3070 in SLI.
I suspect this will only result in problems, but do you have any experience with SLI in nnUNet?

**Comment by FabianIsensee** [comment]
SLI has nothing to do with deep learning. It's a very narrow interface only intended to coordinate frame rendering between cards. What you probably mean is nvlink. Using nvlink has a very small impact on performance.
nnU-Net runs best on single GPUs. Multi-GPU is simply not needed because larger patch/batch sizes do not improve the results in the small datasets of our domain. That's why multi GPU training is not implemented well: The multi-GPU trainers are not even in a state where you would be able to run inference with them after training. You would need to fiddle around with it to make it work.
My recommencation would be to go 3080.
