### ISSUE TITLE
As a new user of nnUNet, I would like to have reproducible setup steps for an Ubuntu environment.

### ISSUE THREAD

**Issue by pkuppens** [MIC-DKFZ/nnUNet#388]
From the Installation section and other issues raised, it is clear that the go-to place for using nnUNet is Ubuntu.
However, there is a variety of Ubuntu solutions, e.g. Windows Subsystem for Linux (WSL2), Docker images, Ubuntu native on a workstation or server, or even cloud solutions.

A proven setup would be a great start for new users. Such Installation section could include: 
* an Ubuntu image name/link
* required and recommended tooling (python versions that have proven to work)
* setup for CUDA on Ubuntu (if the hardware supports it)

-- 
A minor side question:
I might want or even need to port the inference solution to Windows. It seems that the final solution is created/used using Python. Am I correct to think that the portability of the final inference model should not be a great concern?
(Though the training and model optimizations will be.)

**Comment by FabianIsensee** [comment]
Hi there,
thank you for the suggestion. I agree that we could do a better job communicating the setup requirements. I will try to find some time to add more information.
Note that we are only a couple of developers with access to a limited number of Systems for testing. As a result, we cannot test any windows compatibility and can also not investigate WSL2 at all. 
nnU-Net has so far run on all linux distros we have access to: Ubuntu 16.04, 18.04, 20.04, centOS, RHEL.
You do not need any cuda setup at all - just install a recent driver for your graphics card.
Python 3.6 and above should work, this is something we need to clarify. 3.5 does not support type hinting as far as I know.
What graphics cards (aka compute architectures) are supported depends on pytorch and is beyond our control.

Please note that porting the inference pipeline to windows may be a lot more complicated than it first sounds. You will need the correct preprocessing and also the whole tile-based inference scheme (do not change the patch size for inference!). You will also need the code to export the generated segmentations. nnU-Net has a well-optimized inference pipeline. preprocessing and segmentation export are handled with background workers so that the main process can focus on the actual inference. Python multiprocessing in windows seems to be a pain. You have been warned ;-)
Best,
Fabian

**Comment by FabianIsensee** [comment]
Would a set of instructions on how to set up an NGC docker container with nnU-Net in it along with minimal system requirements satisfy your request?

**Comment by pkuppens** [comment]
@FabianIsensee , that would really be great. I'm working on a similar solution, but having some uniformity in setup between different users could prevent a lot of problems. (And I'm relatively new to Docker).
Will it be in this github repo?

And coincidence or not, I just found this article, https://www.docker.com/blog/wsl-2-gpu-support-is-here/ 

Haven't checked it in-depth, but it could mean it will be a lot easier to develop and test on a Windows PC, before moving to the Cloud, without having too many 'beta' problems.

I intend to have a Django web server, some Jupyter notebooks in my own container, to be able to inspect it, and create a server for automated predictions.

**Comment by pkuppens** [comment]
@FabianIsensee , is the set of instructions to set up this docker container available somewhere? (Or do I have to modify example  from BRATS if  I can find it?)

**Comment by FabianIsensee** [comment]
Hi,
it's not available but it's also not difficult to get a docker with nnU-Net in it: just start with nvidias most recent NGC pytorch docker and run pip install nnunet in the dockerfile :-)
(don't forget to also set the environment variables)
Best,
Fabian
