### ISSUE TITLE
How can we take full advantage of multiple GPUs to train several models at the same time?

### ISSUE THREAD

**Issue by JunMa11** [MIC-DKFZ/nnUNet#4]
Hi @FabianIsensee ,

Thanks for the great repository. I test it on Linux and it works very well.

### Q1. How can we take full advantage of multiple GPUs to train several models at the same time?

My GPU server has 8 Nvidia TitanX GPUs (12GB). I want to **train multiple models at the same time using different GPU**. For example, training a 2D U-Net, 3D U-Net (full resolution) with different folds.
> CUDA_VISIBLE_DEVICES=1 python run/run_training.py 2d nnUNetTrainer TaskXX_MY_DATASET all --ndet
> CUDA_VISIBLE_DEVICES=2 python run/run_training.py 3d_fullres nnUNetTrainer TaskXX_MY_DATASET 0 --ndet
> CUDA_VISIBLE_DEVICES=3 python run/run_training.py 3d_fullres nnUNetTrainer TaskXX_MY_DATASET 1 --ndet

However, if I do this (eg. only training 2 models), the Linux server tends to be stuck. The training time of each epoch increases by 60% for each training task. To be precise, when I run one `run_training.py`, each epoch costs ~480s. If I run two `run_training.py`, each epoch costs ~800s for single training task.  So I can only run one training task at a time. The remained GPUs are not be fully used. How can I efficiently train several models at the same time?

### Q2. Following is a screenshot of `htop` when running one training task. Why one training task costs 32 PIDs?
![htop](http://i1.bvimg.com/595387/27214af5182cffb2.png)

### Q3.1 Does nnU-Net use a cascaded way for a large dataset (e.g. LiTS) even if run with `3d_fullres`?

![Markdown](http://i1.bvimg.com/595387/53c375541b5f7b22.png)

### Q3.2 When counting the number of class (`num_classes`), nnunet does not count background class. right?

A typo in [readme->Inference](https://github.com/MIC-DKFZ/nnUNet#inference)
> python inference/predict_simple.py -i INPUT_FOLDER -o OUTPUT_FOLDER_CASCADE -t TaskXX_MY_DATASET -tr nnUNetTrainerCascadeFullRes -m 3d_fullres_cascade -l OUTPUT_FOLDER_LOWRES
It should be [3d_cascade_fullres](https://github.com/MIC-DKFZ/nnUNet/blob/6150f1b0282daad11d4ad8d7227e68abe75e6f06/nnunet/inference/predict_simple.py#L32) rahter than `3d_fullres_cascade`.

I'm looking forward to your reply.
Best regards,
Jun

**Comment by FabianIsensee** [comment]
Dear Jun,
thank you so much! I am very happy you like the repository!
About your questions:
**1)**
CUDA_VISIBLE_DEVICES is the right way to run several trainings in parallel. Using this, we observe perfect scaling with our own servers. We have several different configurations, ranging from dual TitanXP nodes all the way up to dgx2 (16 V100). So yes, there must be some kind of problem. Maybe one of those helps:
- make sure the trainings are correctly assigned to the GPUs by looking at nvidia-smi
- There is an issue with numpy that could cause the problems you are seeing: starting from numpy version 1.14.6, numpy supports threading for the underlying blas library. This will allow numpy to run some operations (such as matrix multiply) in a multithreaded way leveraging all available CPU cores This causes problems with python multiprocessing (as is used in batchgenerators) because each process (of which there are 12 for each training) will run these multithreaded operations on all CPUs (40 in your case = 12x40 threads max. That is too much). Please try running all commands with `MKL_NUM_THREADS=1,NUMEXPR_NUM_THREADS=1,OMP_NUM_THREADS=1,CUDA_VISIBLE_DEVICES=X python3 run_training.py ...`. On our servers setting OMP_NUM_THREADS=1 helps a lot! (*)
- Your Server seems a bit weak on the CPU side. It has only 2.5 physical CPU cores per GPU. Not sure how much you can influence future purchases but I recommend having at least 4 physical cores per GPU
- what is your CPU configuration? You may not have sufficient PCIe lanes? (Not sure about this)

(*) try this first!

**2)**
This is most definitely due to numpy, see first suggestion above
(I do not see the training use 32 threads/processes in the htop screenshot you sent. Are you sure about this?)

**3.1)**
The cascade will not run automatically. You need to run the five folds of 3d_lowres first and then run the five folds of 3d_cascade_fullres after that. 3d_fullres will just train a 3D U-Net on full resolution (which worked very well for lits by the way!)

**3.2)**
Not quite sure and I cannot verify this because I am on vacation right now. I believe it displays only the number of foreground classes. You can verify this by looking at the output segmentations. It should output class 0 (background), 1 and 2 for lits.

Let me know if that helped!
Best,
Fabian

**Comment by JunMa11** [comment]
Hi Fabian,

Thanks for your quick and helpful reply.
1) Yes, `OMP_NUM_THREADS=1` helps in my server! Thanks for the great advice very much.
Following is the CPU information by `lscpu`.

![CPU](http://i2.bvimg.com/595387/de6ab8e6442d7029.png)

2) I counted the PIDs manually.

![32 PIDs](http://i2.bvimg.com/595387/3b1000aef10b72ac.png)

3.1) I think so. I run `3d_fullres`, but what do the `stage:0` and `stage: 1` mean (red rectangle)?

![Markdown](http://i1.bvimg.com/595387/53c375541b5f7b22.png)

3.2) Yes, you are right.

I very appreciate your help and time.

I wish you have a great vacation.

Best regards,
Jun

**Comment by FabianIsensee** [comment]
Dear Jun,
I am happy to help out!
1) Your CPUs have 40 PCIe lanes each, so that's 10 lanes per GPU (the GPUs probably run with 8 each). That is enough for regular model training, but you may run into bottlenecks if you do distributed training - I am not 100% sure about that though)
nnunet requires about 2-3 CPU cores per training for each input modality. Lits has only CT so your system should be powerful enough. If you were to run brats (4 modalities) on this system you may run into CPU issues.
2) Not all of these PIDs actually do real work I think, so looking at the running number of threads may be more informative. nnunet will have one main process and 12 background processes for data augmentation (you can adjust that number if you wish). That's 13. During training most of the background workers will be idle, though as they are way too many for most of the datasets (that won't hurt though as long as you have enough RAM).
3) This is just a debug print. It shows the network and data configuration. stage 0 is 3D lowres and stage 1 is 3d_fullres/3d_cascade_fullres. I print that for convenience. For datasets that don't have a 3d_lowres configuration 3d_fullres may be called stage0 instead. Not sure though. 
Further down below it says `I am using stage 1 from these plans` to indicate that this is the configuration that corresponds to 3d_fullres.

Best,
Fabian

**Comment by JunMa11** [comment]
Dear Fabian,

Thanks for your answer very much.

> If you were to run brats (4 modalities) on this system you may run into CPU issues.

I have to deal with multi-modalities/sequences data (e.g. 7 MR contrast-enhancement series at 7 time points),  in this situation, may I reduce the number of data augmentation threads (e.g. reduce default 12 to 2) to eliminate the CPU issues?

Best,
Jun

**Comment by FabianIsensee** [comment]
Reducing the number of processes will not improve your situation. Your server has too little CPU power to deal with 7 modalities on 8 GPUs at the same time. If you reduce the number of Processes then all you will achieve is that the GPU will have to wait more often for batches to be ready. nnunet is designed so that it can have the GPU running at 100% the entire time. This will not be the case here and the training will thus take a lot longer.

What you can do is disable all the spatial transformations (elastic deform, roration, scaling). This will reduce the CPU load substantially. I recommend you try that first.

Monitor the GPU usage with `watch -n 0.1 nvidia-smi`. If it's not at 100% all the time with occasional dips into the 90s then there is something wrong

Best,
Fabian

**Comment by JunMa11** [comment]
Dear Fabian,

Thanks for your advance very much. 
It works! GPU-util is almost at 100%  all the time.

Best,
Jun
