### ISSUE TITLE
About five folds problem

### ISSUE THREAD

**Issue by goodsave** [MIC-DKFZ/nnUNet#411]
I see such a sentence in the explanatory document：
`Note that the 3D full resolution U-Net of the cascade requires the five folds of the low resolution U-Net to be completed beforehand!`
I want to know what this five fold is designed for.
This greatly increases the training time. Is there any way to achieve better results in the case of training only once?
We look forward to your reply，thank u so much.

**Comment by FabianIsensee** [comment]
Hi,
you need the five folds to run the cascade. The second stage of the cascade needs the imperfect predictions from the low resolution stage. There is no way around this, unfortunately.
Best,
Fabian

**Comment by goodsave** [comment]
ok. Are all these five models needed in predicting?
Can I use only one model in a production environment?

**Comment by FabianIsensee** [comment]
You can train one model by specifying 'all' as fold instead of an integer (0,1, 2, 3, 4). This will train on all data. But you cannot (!) determine postprocessing with that. Given that postprocessing does not improve the results much, if at all, you don't need it.
When you run inference, you need to specify that it is supposed to use the 'all' model by passing `-f all` to nnUNet_predict

**Comment by goodsave** [comment]
I see. Thank you~
