### ISSUE TITLE
Training on 2D data only

### ISSUE THREAD

**Issue by bkonk** [MIC-DKFZ/nnUNet#414]
Is it possible to train nnUNet on 2D only data or would inputing 2D data interfere with the data fingerprinting? If so, would anything special need to be done during preprocessing etc. or could I just run the preprocess commands normally and then train only the 2D model?

**Comment by FabianIsensee** [comment]
You can train with 2D data by just making them pseudo-3d. Just add a third dimension so that the data is, for example (1, 256, 256) (first dimension only has shape of 1). Then you can use the data with nnU-Net. Make sure to disable 3D networks in plan and preprocess: `nnUNet_plan_and_preprocess -t XX -pl3d None`

**Comment by bkonk** [comment]
Great, thanks!
