### ISSUE TITLE
Calculation of brats defined classes during inference using nnU-net

### ISSUE THREAD

**Issue by saruarlive** [MIC-DKFZ/nnUNet#487]
Hi Fabian et al,

As you had mentioned in the Brats 2020 paper, you have trained models using sigmoid activation, and tumor regions independently such as tumor core(TC), ET, and whole tumor(WT). 
My question is how have you extracted Brats20 defined classes (0=Background, 1 = NER, 2 = Edema, 4= ET) from the three trained tumor regions to submit to the brats web portal to get the performance metric.
Is the formula for calculation  is more or less like that,

set(Edema) = set(WT) - set(TC)
set(NER) =  set(TC) - set(ET)
?
Still, there might be overlapping values among set(Edema),  set(NER), and set(ET). How had you handled the issue?
Could you kindly mention that?

I am looking forward to hearing from you.

**Comment by FabianIsensee** [comment]
You can read about this in
https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunet/dataset_conversion/Task082_BraTS_2020.py

(I map the labels from [0, 1, 2, 4] to [0, 1, 2, 3] because they need to be consecutive for nnunet, also see https://github.com/MIC-DKFZ/nnUNet/blob/c379974dbca57d2d1f4b999128de293b778d1d52/nnunet/dataset_conversion/Task043_BraTS_2019.py#L25)

and in 
https://github.com/MIC-DKFZ/nnUNet/blob/c379974dbca57d2d1f4b999128de293b778d1d52/nnunet/training/network_training/competitions_with_custom_Trainers/BraTS2020/nnUNetTrainerV2BraTSRegions.py#L66

conversion to the regions during training is done as part of the data augmentation: https://github.com/MIC-DKFZ/nnUNet/blob/c379974dbca57d2d1f4b999128de293b778d1d52/nnunet/training/network_training/competitions_with_custom_Trainers/BraTS2020/nnUNetTrainerV2BraTSRegions.py#L134

(see regions!)

conversion back is part of segmentation export: https://github.com/MIC-DKFZ/nnUNet/blob/c379974dbca57d2d1f4b999128de293b778d1d52/nnunet/training/network_training/nnUNetTrainer.py#L621

(see self.regions_class_order)

Best,
Fabian
