### ISSUE TITLE
Cupy works on accelarate the process of interpolation!

### ISSUE THREAD

**Issue by Joevaen** [MIC-DKFZ/nnUNet#498]
Hi, fabian.
I am so happy to tell you that the process of interpolation in nnUNet have been optimized from more than 1 min to <5 s. I take an advantage of cupy and it really work. The work on acceleration of trt implement failed but I still keep focus on the solution. I am aiming to realize `nnUNet-3dpredict`in 10s. 
I hope everyone know someone is working on this way and searching for any possibility for nnUNet's better deployment in reality.
Thanks for your exellent job, always.
Joevaen

**Comment by FabianIsensee** [comment]
Hi,
those are great news! Have you verified that you implementation is mathematically identical to the one nnU-Net currently uses? nnU-Net uses sometimes linear, sometimes third order spline interpolation and sometimes a mix of these.
Best,
Fabian

**Comment by Joevaen** [comment]
Yeah, I know nnUNet use different interpolation methods according to the property of dataset. In my test of cupy 8.4, the 3-spline-filter of `map_coordinates`is not supported, but it would work if you install cupy 9.0 via  `conda install conda-forge/label/cupy_rc::cupy=9`.I am testing this and I will feed back to you later. I am sure that cupy can do a lot for nnUNet-preprocess.
Best,
Joevaen.

**Comment by FabianIsensee** [comment]
It sounds like the interpolation will then be done on GPU? That is not a problem, we would just need to make that clear to users. Currently we do not need a GPU for preprocessing.
Note that anisotropic cases are interpolated with spline interpolation in-plane (2d!) and then with nearest neighbor out of plane. Just so you are aware of all the edge cases ;-)
I do not like linear interpolation because it smears the data a lot. So getting spline to work would be important
Best,
Fabian
