### ISSUE TITLE
postprocessing error when using folds = all

### ISSUE THREAD

**Issue by lord-bubbacub** [MIC-DKFZ/nnUNet#561]
Hi,
Have just spent 4 days training my custom dataset using the '-f all' option and the 3dfullres trainer (RTX3090 - cudnn 8005).

When trying to use inference with this command:
nnUNet_predict -i inputpath -o outputpath -t 103 -m 3d_fullres -f all

I get the following error:

WARNING! Cannot run postprocessing because the postprocessing file is missing. Make sure to run consolidate_folds in the output folder of the model first!

When I try to run:
nnUNet_determine_postprocessing -t 103 -m 3d_fullres

It seems to want all 5 folds trained!

Is this a bug in the folds all option? or is there a way of running inference without having to do post processing.
Interestingly when I have done a partial training cycle and renamed the best model file to the final checkpoint name on other almost identical datasets the inference has run without error?

Very grateful for any insights?

**Comment by FabianIsensee** [comment]
Hi,

why did your training take 4 days? It should be MAX 2 days on a 3090. More like 1 1/2. Did you maybe have a CPU bottleneck?

nnUNet_determine_postprocessing needs all five folds because it needs predictions of the training set. If you set folds=all it uses all available cases for training and therefore cannot get meaningful predictions on the training set. Therefore postprocessing cannot be determined.

But this doesn't matter much. Postprocessing does not improve the results by a lot. You can ignore it and just run without postprocessing :-)

Best,
Fabian

**Comment by lord-bubbacub** [comment]
Dear Fabian,
Thanks for your quick reply. 
The slow training is a surprise - have a 12 thread ryzen and 32gb ram, nvme ssd. May have to try compiling pytorch from source. 

The issue I'm getting is that nnunet_predict is quitting with an error demanding post-processing. Is there a way of making nnunet predict run without post-processing?
Best wishes

**Comment by FabianIsensee** [comment]
HI,
are you sure it is quitting with an error? That is just a warning. It should still generate the predictions
Best,
Fabian

**Comment by sungchu** [comment]
Hi, 

I get the same error. I did not finish all 5 folds but only one fold. When i run this commmand:
nnUNet_predict -i ./qiao/nnUNetFrame/DATASET/nnUNet_raw/nnUNet_raw_data/Task071_Brain/imagesTs -o ./qiao/nnUNetFrame/DATASET/nnUNet_raw/nnUNet_raw_data/Task071_Brain/labelsTs_3d_pred -t 71 -m 3d_fullres -f 4 --save_npz

I get the following error:
WARNING! Cannot run postprocessing because the postprocessing file is missing. Make sure to run consolidate_folds in the output folder of the model first!
The folder you need to run this in is /root/user/home/qiao/nnUNetFrame/DATASET/nnUNet_trained_models/nnUNet/3d_fullres/Task071_Brain/nnUNetTrainerV2__nnUNetPlansv2.1

**Comment by FabianIsensee** [comment]
This is not an error. It is a warning. You can ignore it. Or you run nnUNet_determine_postprocessing for that task

**Comment by sungchu** [comment]
Hi Fabian,

nnUNet_predict did not generate the predicted results. What should I deal with it?

when I run nnUNet_determine_postprocessing -m 3d_fullres -t 71. It returns 
RuntimeError: some folds are missing. Please run the full 5-fold cross-validation. The following folds seem to be missing: [0, 1, 2, 3]

Thanks for the reply,
Sungchu

**Comment by FabianIsensee** [comment]
Hi @yunfeihaha have you run all these 5 trainings?
