### ISSUE TITLE
why use npz instead of nii.gz format for training?

### ISSUE THREAD

**Issue by Wangyulin-user** [MIC-DKFZ/nnUNet#566]
Hello, I would like to ask why do you use npz instead of nii.gz format for training? The size of them both are about the same, so what's the advantage of using npz?
Thank you.

**Comment by FabianIsensee** [comment]
npz is not the goal - it's npy (uncompressed numpy arrays). The reason for this is that we can read npy files partially and thus minimize both CPU usage, RAM usage and I/O at the same time. We simply always only read the crop or slice we currently need.
If we were to use .nii.gz then we would need much more CPU (for decompressing) and RAM (because we would need to load the entire image first and then crop). Imagine training a 2D U-Net with .nii.gz. For every 2D slice you want you would have to read and decompress the entire 3D volume. What a waste :-)
Best,
Fabian

**Comment by Wangyulin-user** [comment]
Thank you for your kind explanation, and I am wondering if it will also work well by using nii format because it can also omit the decompressing step.
Best regards,
Yulin

**Comment by FabianIsensee** [comment]
I do not know how to partially read nii files. This is very well implemented in numpy so I don't really see a reason to change it ;-)

**Comment by Wangyulin-user** [comment]
Thank you very much, I got it.
Have a good day.

**Comment by tuan-ld** [comment]
Hi, can I use npy and npz preprocessed output files to feed into my customize CNN network? Thanks!
