### ISSUE TITLE
How important is nnUNet_cropped_data?

### ISSUE THREAD

**Issue by harsharaman** [MIC-DKFZ/nnUNet#583]
Hi Fabian,

I am processing my own dataset with your preprocessing pipeline. My dataset is about 255 GB. When preprocessing I observed that the memory was running out on my system, so I checked and nnUNet_cropped_data is occupying the same size as my dataset essentially doubling the memory consumption. Is this cropped data necessary for preprocessing? That is, should it be stored? Are there other memory light ways of preprocessing?

**Comment by harsharaman** [comment]
![image](https://user-images.githubusercontent.com/25810772/113188196-04ca2280-925a-11eb-98b6-7ba13ab6c142.png)

It isn't cropping much. Is there a way to avoid cropping?

**Comment by FabianIsensee** [comment]
cropping is not what is eating your memory. Resampling is.
Try reducing the number of workers: `nnUNet_plan_and_preprocess [...] -tl 1 -tf 1`
These images are very large. Please use nnU-Net_train with `--disable_postprocessing_on_folds` and nnUNet_find_best_configuration with `--disable_postprocessing`. Otherwise it might take ages to complete. We need to work on that ;-)
Best,
Fabian

**Comment by FabianIsensee** [comment]
(You cannot disable cropping)

**Comment by harsharaman** [comment]
Ok. Thank you.
