### ISSUE TITLE
 could not broadcast input array from shape

### ISSUE THREAD

**Issue by odindis** [MIC-DKFZ/nnUNet#592]
I successfully used "nnUNet_plan_and_preprocess -t 58 --verify_dataset_integrity" 

But when I use "nnUNet_train 3d_fullres nnUNetTrainerV2 58 4"，i get the following error:"could not broadcast input array from shape (1,20,435,423) into shape (1,20,423,423)"

Why？

**Comment by FabianIsensee** [comment]
verify_dataset_integrity does not check everything. It just checks for the most common kind of problems. Could you descriube a little more what the problem is? What is the whole error message?

**Comment by piebirds** [comment]
> verify_dataset_integrity does not check everything. It just checks for the most common kind of problems. Could you descriube a little more what the problem is? What is the whole error message?

Thank you for your reply.

I have avoided this error.But I still don't know why it happened.
My solution to the problem is as follows: 
    (1) First of all, I'm using this framework for the first time, so I've tried the command several times to make it work. Therefore, before I use "nnUNet_plan_and_preprocess -t 58 --verify_dataset_integrity", many files generated after that already exist, because it's not the first time I use it.
    (2) Then, I deleted all the files that might be generated repeatedly, including those generated in the "nnUNet_trained_models", ,"nnUNet_preprocessed","nnUNet_raw_data" and "nnUNet_cropped_data" folders.
    (3) In the end, I followed the tutorial again and succeeded.

“could not broadcast input array from shape (1,20,435,423) into shape (1,20,423,423)” is my error message. There is no more detailed information. This error means that the parameters of the model deviate from the shape of the preprocessed data. I don't know more details, but I've avoided the bug now.

**Comment by Karol-G** [comment]
Hey @odindis,

Is the problem still current or did you manage to solve it?

Best,
Karol
