### ISSUE TITLE
Why we set the minimum feature map to 4x4(x4)

### ISSUE THREAD

**Issue by yan4821567** [MIC-DKFZ/nnUNet#594]
Hi Fabian:

'In Dynamic Network adaptation, we perform downsampling until the feature maps are relatively small (minimum is
4x4(x4)) to ensure sufficient context aggregation.'

I adjusted the minimum feature map size from 4x4x4 to 8x8x8 in my own dataset, and then the number of network layers was reduced by one layer, and then the segmentation effect was improved. I am trouble in how to explain this phenomenon based on the relationship between the feature map size and the data set. 

For example, I guess the smaller the organ to be segmented, the smaller the feature map should we set to aggregate information? Or when the organ to be segmented occupies a small size of the original image, the feature map should not be set too small, because there is no more information to aggregate in this way?

I want to know how the minimum feature map is selected here, can you give some advice?

**Comment by FabianIsensee** [comment]
The minimum feature map size was set empirically. This is what performed best (on average) in our internal evaluations. The smaller you let the feature maps get, the more global information the network can capture (because it does more pooling operations). The fact that you got better results with 8x8x8 is a bit surprising, but you should consider the following:
- is the difference really significant?
- nnU-Net does not use seeding. If the two results are close to each other then it might be the other way around if you rerun the training
- depending on dataset size fewer layers (implicit consequencce of larger feature maps in nnU-Net) could be beneficial.
In general I would not advise going below 4x4x4.
Best,
Fabian

**Comment by yan4821567** [comment]
> The minimum feature map size was set empirically. This is what performed best (on average) in our internal evaluations. The smaller you let the feature maps get, the more global information the network can capture (because it does more pooling operations). The fact that you got better results with 8x8x8 is a bit surprising, but you should consider the following:
> 
> * is the difference really significant?
> * nnU-Net does not use seeding. If the two results are close to each other then it might be the other way around if you rerun the training
> * depending on dataset size fewer layers (implicit consequencce of larger feature maps in nnU-Net) could be beneficial.
>   In general I would not advise going below 4x4x4.
> 
> Best,
> Fabian

Thank you. I will check it again
