### ISSUE TITLE
Softmax probabilities in nii.gz format

### ISSUE THREAD

**Issue by annukkaa** [MIC-DKFZ/nnUNet#620]
Hello, 

After running nnUNet_predict (with the -save_npz flag), I'm left with 3 files in the output folder for each case: the **.nii.gz** 'thresholded' segmentation (with the same shape as the raw image, which in my case is 40x960x960), a **.npz** file (with shape 4x40x684x960) and a **.pkl** file with origin/spacing/ and other information. I have 3 labels.

I'm interested in saving the softmax maps in the **.nii.gz** format. However, I'm having a hard time interpreting what each of the dimensions in the **.npz** file represent and how I can, based on the **.pkl** file, reconstruct it into a **.nii.gz** file with the same shape as the raw image (for each label).

Is there any function I can use to save the softmax maps as .nii.gz?

I've been looking into the [save_segmentation_nifti_from_softmax](https://github.com/MIC-DKFZ/nnUNet/blob/52f16d7f2b134f8a29d0106f06304a985486d2e2/nnunet/inference/segmentation_export.py) function, which seems like I could possibly adapt to output the probabilistic maps. Is this the approach I should take or is there a better way?

Thank you

**Comment by FabianIsensee** [comment]
save_segmentation_nifti_from_softmax is where you can find out how to restore the original geometry. If you want the softmax output then you will need to adapt it so that it does not do the argmax. The softmax probabilities are already resampled to the original image shape (after cropping) so all you need to do is reverse the cropping and then plug in the original geometry (as done in save_segmentation_nifti_from_softmax !) .
First dimension is the labels. It's (background, label1, label2, label3)

**Comment by annukkaa** [comment]
Thanks, I'll look into and adpat save_segmentation_nifti_from_softmax

**Comment by agroenenberg** [comment]
@annukkaa Any update on this? Did you figure it out? I'm trying to do the same thing ! :)

**Comment by annukkaa** [comment]
Yes, it worked by doing this :)

> Edit: Just to see if I undestand, what I need to do is take npz files, pad around the crop (based on the bbox) to get the original size and set the spacing/origin/direction?
