### ISSUE TITLE
Use Resnet18 backbone for 2D-Unet

### ISSUE THREAD

**Issue by sbajpai2** [MIC-DKFZ/nnUNet#63]
Hi Fabian,

Your code for nnunet is awesome.
I want to use Resnet18 as backbone for 2d-UNet.
How can I do so?
Is it possible in nnunet?

**Comment by adhusch** [comment]
Hi @sbajpai2,

semi off topic, but when you want to do pure 2d stuff using a dynamic UNet like architecture build on a pretrained encoder the dynamic UNet provided in fastai might be interesting for you. It can build a UNet from any pretrained encoder available in pytorch ( `learn = unet_learner(data, models.resnet18)` would give you the resnet based network you asked for). To apply that to medical data you have to fiddle a bit with the channels as the pretrained models are AFAIK all for 3 channel RGB data, but thats sort of straightforward.

Best 
Andy

P.S.: I was already thinking that it would be super nice to integrate that approach to nnU-Net when i listened to Fabians presentation at BVM, so i just hijacked your question now to spread that idea ;-) Sorry ;-)

**Comment by FabianIsensee** [comment]
Hi Andy,
pretty cool idea! This requires however that you can somehow estimate the GPU memory consumption of all these networks. Or you just buy a big ass GPU and hope it fits.
Also 2D is not really where it's at for medical image data. Most MRI/CT data will get much better results in a 3D network. Pretrained 3D models don't really exist, so that reduces the usability of something like this a lot. 
Fastai is doing amazing work. I did not know about the unet_learner but it looks extremely powerful and convenient. I am participating in this years RobustMIS challenge at MICCAI (2D RGB images). Of course not with nnU-Net but a lot of my code is based on parts of nnU-Net. I do not use pretrained models but will probably have to compete against teams who do. Let's see how this goes :-) If my network is bottom of the barrel I might be tempted to give the unet_learner a try
Best,
Fabian

**Comment by adhusch** [comment]
Hi Fabian,

yeah, the memory consumption estimation problem would be a nice one for a student project i guess, could try to find one but i am not overly optimistic about that. But well, along the lines of your "attempt at beating the u-net" other encoders might anyway not yield so much. But besides that i just love the structural  beauty ot the unet_learner approach.

Regarding the pretrained 3d models: Actually i was hoping that your group might release some pretrained models at some point ;-) Seems you would be the right people to provide a sort of baseline standard here.

Best
Andy

**Comment by FabianIsensee** [comment]
> Regarding the pretrained 3d models: Actually i was hoping that your group might release some pretrained models at some point ;-) Seems you would be the right people to provide a sort of baseline standard here.

That is a really good point and we should definitely start working on that. We actually have models from brain extraction and brain tumor segmentation available at https://github.com/NeuroAI-HD/ right now. But as you said, we should probably just make all the parameters public. I really don't have time for anything right now but I will do it in the near future

> yeah, the memory consumption estimation problem would be a nice one for a student project i guess, could try to find one but i am not overly optimistic about that.

GPU memory consumption is a b***. There is no deterministic way of knowing which algorithm will be used by torch/cudnn and all these algorithms have different memory footprints.If you look into the nnU-Net code then you will see that the memory estimation is hacked together here as well - but it somehow works well enough ;-) I would not want to reimplement it tough, especially not for arbitrary network architectures.

> But well, along the lines of your "attempt at beating the u-net" other encoders might anyway not yield so much. 

I think that depends on the datasets of the future. Right now I believe our datasets are just too small to allow for more fancy architectures to succeed. But with larger datasets this may change. 

Best,
Fabian
