### ISSUE TITLE
Discussion of results on Medical Segmentation Decathlon

### ISSUE THREAD

**Issue by Chris-On-PC** [MIC-DKFZ/nnUNet#634]
Hi Fabian,

Thanks for sharing this great work. 
I was wondering if there was ever a paper written or maybe a discussion based on the performance of nnUNet on the various challenges presented during the decathlon? For example what made certain challenges/structures more difficult to accurately segment i.e. low dice scores on Brats challenge? 

Any feedback will be appreciated!

**Comment by FabianIsensee** [comment]
Hi Chris,
there is no discussion of these aspects because it is often unclear why Dice scores are the way they are. In Task10 for example, I think that much more training data is needed because the target structure is extremely difficult to find. In Task01 on the other hand (I believe that) the ground truth is too inaccurate to allow for learning better segmentation (this is the old brats data which is no longer used in the modern brats challenges). If you ask me about a specific dataset I can tell you what I think (without giving any guarantees for correctness).
Best,
Fabian

**Comment by Chris-On-PC** [comment]
Hi Fabian,
Thanks for the response! 
I am particularly interested in Task07. Dice scores on the pancreas seems great but the tumour segmentation is not as good and, in some cases, even missed.  Interesting that there are in some cases no prediction made even though the model was trained on cases all containing tumour. The tumour ground truth seems quite blob like, probably due to the annotation tool used. Do you have any further comments on the performance on this challange?

**Comment by FabianIsensee** [comment]
Hi,
unfortunately I cannot comment on that because I am not knowledgeable in interpreting the data. Someone once told me that the ground truth for the tumor in this task is not very good, but again - I don't know :-)
If you want recommendations for good datasets tell me what you are looking for (modality, segmentation target) and I will recommend some.
Best,
Fabian

**Comment by Chris-On-PC** [comment]
Thanks again for the feedback. 
Yes, if you are aware of any CT-based pancreatic tumour dataset, that would be great!

**Comment by FabianIsensee** [comment]
Unfortunately I only know Task07 from the MSD
