### ISSUE TITLE
Patch Oversampling for Validation Stage

### ISSUE THREAD

**Issue by Beth1094** [MIC-DKFZ/nnUNet#639]
Hi, 

Many thanks for this great open source codebase. 
I have a question about the patch oversampling of the foreground classes that is done in the dataloader. 
Using knowledge of the locations of the foreground classes during the validation stage doesn't sound right to me. Is there a reason that this is done for both the training and validation data that I am missing? See [here](https://github.com/MIC-DKFZ/nnUNet/blob/058b695d61d34dda7f79cd36ab950a5d3e031653/nnunet/training/network_training/nnUNetTrainer.py#L407).

Thanks,
Beth

**Comment by FabianIsensee** [comment]
Hi Beth,
the reason this is in there is so that we can compare the red and blue lines and thus learn about overfitting. If we were not to do that then this comparison would not be possible. The validation stage in nnU-Net is not a real validation anyways. We don't predict entire images and we do not compute the real Dice score. That would take way too long on some datasets. Just use the validation stage as an estimate and base any decisions you make on the real validation which happens at the end of each training.
Best,
Fabian
