### ISSUE TITLE
Query data-augmentation: random crop

### ISSUE THREAD

**Issue by LalithShiyam** [MIC-DKFZ/nnUNet#645]
Hi Fabian,
many thanks for the wonderful toolbox (and also for making it open-source). I was wondering if there was any particular reason for not using random crop in data-augmentation, the default setting is for random crop is set to false. 
Cheers,
Lalith

**Comment by FabianIsensee** [comment]
Hi,
we use random crop, but the implementation of that is in DataLoader3D, not in the data augmentation. The center crop in the spatial transform is needed because we initially crop a larger patch, rotate/scale then and then create a center crop of the final patch size. This way we avoid border artifacts

**Comment by LalithShiyam** [comment]
Hi Fabian, 
Thanks! 
Cheers,
Lalith
