### ISSUE TITLE
Batch size at inference

### ISSUE THREAD

**Issue by justingm** [MIC-DKFZ/nnUNet#651]
Hello Fabian,

I am just curious whether nnU-Net uses the same batch size as in training during inference. Does increasing the batch size (provided that the GPU can handle it) make the inference faster?
Thanks!

Best,
Justin

**Comment by justingm** [comment]
Also, if I want to measure the inference time, is it correct to time predict_3D (see snippet below)? Or is it somewhere else? Is it the same for all models?

https://github.com/MIC-DKFZ/nnUNet/blob/e29f7c04f3c5458033ee522ad6145db780d3f510/nnunet/training/network_training/nnUNetTrainer.py#L519-L524

**Comment by FabianIsensee** [comment]
We only use batch size of 1 during inference. Looking at the GPU utilization and power consumption this is not a huge bottleneck though. Refactoring the code would be difficult and potentially introduce different bottlenecks

**Comment by FabianIsensee** [comment]
timing predict_3d is the rightplace (for 3D data). Note that this may be called multiple times per sample if predicting with multiple folds as ensemble

**Comment by PTRRupprecht** [comment]
> We only use batch size of 1 during inference. Looking at the GPU utilization and power consumption this is not a huge bottleneck though. Refactoring the code would be difficult and potentially introduce different bottlenecks

I have a very related question. We're right now using a batch size of 1 for inference. The GPU utilization is high (70-90%), but the GPU memory is used only by 20-25%. I would assume that the processing would be faster if we had a batch size e.g. of 2 due to possible parallelization of batches in the GPU. Then the GPU memory usage would be at ~50% and the GPU utilization still at a high level. Do you think there is a flaw in my understanding?

**Comment by PTRRupprecht** [comment]
Thank you for your quick reply!

A 20% performance increase would be already quite helpful in our case since the inference is going to run for a couple of months (several 100 TB of data). I therefore wonder how complex it would be to implement larger batches. Our current understanding is that one could append several (2-4) patches within the function _internal_predict_3D_3Dconv_tiled(). This 5D array (batch_size,channels,x,y,z) could then be handed over to the function _internal_maybe_mirror_and_pred_3D() as previously without any modifications to the latter function. Do you see any potential issues with this approach?

Btw, I'd like to take this opportunity to say that the nnUNet is really a great resource. Super useful, and great work!
