### ISSUE TITLE
Reduce memory usage?

### ISSUE THREAD

**Issue by davidaderup** [MIC-DKFZ/nnUNet#7]
Hi!

Thank you for a very interesting framework! 

I am trying to run some training on a custom dataset with the 3D Unet and I keep getting  CUDA out of memory errors. I am using a Nvidia GeForce GTX 1080 to train the network. Is there anything i can adjust in the code to reduce the batch size or patch size?

Cheers,
David

**Comment by FabianIsensee** [comment]
Hi David,
the code was made to run on 12 GB GPUs and an adaptation is not very straightforward. You would have to adjust Generic_UNet.use_this_for_batch_size_computation_3D to something else and then rerun EVERYTHING (especially experiment planning AND preprocessing). Before you do that I recommend you manually edit base_num_features in the plans files (located where the preprocessed data is). Set it to 20 instead of 30 and it should work.
Best,
Fabian

**Comment by davidaderup** [comment]
Thanks for a quick response. This is really good advice. Will try this approach!

**Comment by FabianIsensee** [comment]
I just added fp16 support. You can run your trainings with --fp16 now to use it. That could also solve your vmem problem.
Best,
Fabian

**Comment by FabianIsensee** [comment]
Hm my push is not there yet. Let me figure this out :-D

**Comment by FabianIsensee** [comment]
It's there yet. Let me know how this works

**Comment by davidaderup** [comment]
Hi, sorry for the late response I got bogged down on other projects. 

I managed to get it to run by adjusting the use_this_for_batch_size_computation_3D, however it only runs for like ~5 epochs before giving me a cuda runtime error that a device-side assert has been triggered. Could that be because of memory problems too?

Will try --fp16 aswell. will let you know how it works

**Comment by FabianIsensee** [comment]
device side assert can be anything. But I have seen it in nnunet before in one very specific situation: If there are numbers in your ground truth segmentation maps that don't belong there. For example if you are running the Liver task (which has 0=bg, 1=liver, 2=tumor) and there are 3's or something in the segmentation map. That will raise this error.
Let me know if that is your issue.

If you adapt use_this_for_batch_size_computation_3D then you may get bad performance as a result. I think it may be better to just reduce the number of filters. I don't know what happens if you reduce use_this_for_batch_size_computation_3D

You need to install nvidia apex for fp16 support: https://github.com/NVIDIA/apex

Best,
Fabian

**Comment by davidaderup** [comment]
Thanks, that was exactly it. I managed to get it to train for the whole duration now. I updated my CUDA drivers from 7.5 to 10.0 which I think helped as well. 

Thanks for all the help and providing such a good platform!

Cheers!
David

**Comment by likeeeee** [comment]
The memory of my gpu is also very limited, so I added --fp16 to train my dataset. Strangly, the loss is negative!  How can I solve it? I suspect the problem is caused by fp16.
(I didn't read the code carffuly yet, but just tried to run it.)

**Comment by likeeeee** [comment]
@FabianIsensee

**Comment by JunMa11** [comment]
@likeeeee 
Yes, the loss should be negative.
the default loss in nnunet is Dice + Cross entropy. Here, `Dice = -2*(pred*gt)/(pred+gt)`, thus the loss will be negative.

**Comment by FabianIsensee** [comment]
Thanks @JunMa11 ! I am on vacation right now so my responses will be delayed. Glad you stepped in.
I never understood why you would add +1 to the dice loss. The constant has no effect at all other than making people comfortable :-D

**Comment by likeeeee** [comment]
@JunMa11 @FabianIsensee  Thanks for your response. I'm not familiar with Dice loss before, but now   understand it.

**Comment by FoilHao** [comment]
In your code you says that fp16 makes sense for 2d only. What does that mean? I used fp16 to train 3d_fullres model and it seemed fine.

**Comment by FabianIsensee** [comment]
Back then tensorcore acceleration for 3d convs was not available. It is now, but only on volta and only if the feature maps are divisible by 8 (which is currently not the case)
