### ISSUE TITLE
Task082_BraTS2020 pretrained model can not find postprocessing.json

### ISSUE THREAD

**Issue by TangVVV** [MIC-DKFZ/nnUNet#709]
Hi,

Thank you for your excellent work. Recentlly, we downloaded the Task082_BraTS2020 pretrained model, when we run nnUNet_determine_postprocessing, it shows the following information:
Display the following information:

WARNING! Cannot run postprocessing because the postprocessing file is missing. Make sure to run consolidate_folds in the output folder of the model first!
The folder you need to run this in is /home/XXX/nnUNetFrame/DATASET/nnUNet_trained_models/nnUNet/3d_fullres/Task082_BraTS2020/nnUNetTrainerV2__nnUNetPlansv2.1

I followed the prompts to execute this program，but it does not work. Could you give me some help?

Best Regards,
Zhiwei Tang

**Comment by FabianIsensee** [comment]
Hi,
just ignore the warning. It doesn't do anything on that dataset anyways :-)
Best,
Fabian

**Comment by rafaloz** [comment]
Hello Fabian,

Great work with nnUNet! I am working with the pretrained models from task 082, however all segmentations I obtain are completely black. input codes for the images are the same as for the decathlon dataset (FLAIR:0000; T1:0001; T1C:0002; T2:0003)?

This is my output: 

> using model stored in  /datos/work/rnavgon/nnUNet_trained_models/nnUNet/3d_fullres/Task082_BraTS2020/nnUNetTrainerV2__nnUNetPlansv2.1

>This model expects 4 input modalities for each image
>Found 1 unique case ids, here are some examples: ['BraTS20_Training_084']
>If they don't look right, make sure to double check your filenames. They must end with _0000.nii.gz etc
>number of cases: 1
>number of cases that still need to be predicted: 1
>emptying cuda cache
>loading parameters for folds, None
>folds is None so we will automatically look for output folders (not using 'all'!)
>found the following folds:  ['/datos/work/rnavgon/nnUNet_trained_models/nnUNet/3d_fullres/Task082_BraTS2020/nnUNetTrainerV2__nnUNetPlansv2.1/fold_0', '/datos/work/rnavgon/nnUNet_trained_models/nnUNet/3d_fullres/Task082_BraTS2020/nnUNetTrainerV2__nnUNetPlansv2.1/fold_1', '/datos/work/rnavgon/nnUNet_trained_models/nnUNet/3d_fullres/Task082_BraTS2020/nnUNetTrainerV2__nnUNetPlansv2.1/fold_2', '/datos/work/rnavgon/nnUNet_trained_models/nnUNet/3d_fullres/Task082_BraTS2020/nnUNetTrainerV2__nnUNetPlansv2.1/fold_3', '/datos/work/rnavgon/nnUNet_trained_models/nnUNet/3d_fullres/Task082_BraTS2020/nnUNetTrainerV2__nnUNetPlansv2.1/fold_4']
using the following model files:  ['/datos/work/rnavgon/nnUNet_trained_models/nnUNet/3d_fullres/Task082_BraTS2020/nnUNetTrainerV2__nnUNetPlansv2.1/fold_0/model_final_checkpoint.model', '/datos/work/rnavgon/nnUNet_trained_models/nnUNet/3d_fullres/Task082_BraTS2020/nnUNetTrainerV2__nnUNetPlansv2.1/fold_1/model_final_checkpoint.model', '/datos/work/rnavgon/nnUNet_trained_models/nnUNet/3d_fullres/Task082_BraTS2020/nnUNetTrainerV2__nnUNetPlansv2.1/fold_2/model_final_checkpoint.model', '/datos/work/rnavgon/nnUNet_trained_models/nnUNet/3d_fullres/Task082_BraTS2020/nnUNetTrainerV2__nnUNetPlansv2.1/fold_3/model_final_checkpoint.model', '/datos/work/rnavgon/nnUNet_trained_models/nnUNet/3d_fullres/Task082_BraTS2020/nnUNetTrainerV2__nnUNetPlansv2.1/fold_4/model_final_checkpoint.model']
starting preprocessing generator
starting prediction...
preprocessing /datos/work/rnavgon/Casos16Meses_Copia/BraTS20_Training_084/BraTS20_Training_084.nii.gz
using preprocessor GenericPreprocessor
before crop: (4, 155, 240, 240) after crop: (4, 144, 167, 139) spacing: [1. 1. 1.] 

>no resampling necessary
no resampling necessary
before: {'spacing': array([1., 1., 1.]), 'spacing_transposed': array([1., 1., 1.]), 'data.shape (data is transposed)': (4, 144, 167, 139)} 
after:  {'spacing': array([1., 1., 1.]), 'data.shape (data is resampled)': (4, 144, 167, 139)} 

>(4, 144, 167, 139)
This worker has ended successfully, no errors to report
predicting /datos/work/rnavgon/Casos16Meses_Copia/BraTS20_Training_084/BraTS20_Training_084.nii.gz
debug: mirroring True mirror_axes (0, 1, 2)
step_size: 0.5
do mirror: True
data shape: (4, 144, 167, 139)
patch size: [128 128 128]
steps (x, y, and z): [[0, 16], [0, 39], [0, 11]]
number of tiles: 8
computing Gaussian
prediction done
debug: mirroring True mirror_axes (0, 1, 2)
step_size: 0.5
do mirror: True
data shape: (4, 144, 167, 139)
patch size: [128 128 128]
steps (x, y, and z): [[0, 16], [0, 39], [0, 11]]
number of tiles: 8
using precomputed Gaussian
prediction done
debug: mirroring True mirror_axes (0, 1, 2)
step_size: 0.5
do mirror: True
data shape: (4, 144, 167, 139)
patch size: [128 128 128]
steps (x, y, and z): [[0, 16], [0, 39], [0, 11]]
number of tiles: 8
using precomputed Gaussian
prediction done
debug: mirroring True mirror_axes (0, 1, 2)
step_size: 0.5
do mirror: True
data shape: (4, 144, 167, 139)
patch size: [128 128 128]
steps (x, y, and z): [[0, 16], [0, 39], [0, 11]]
number of tiles: 8
using precomputed Gaussian
prediction done
debug: mirroring True mirror_axes (0, 1, 2)
step_size: 0.5
do mirror: True
data shape: (4, 144, 167, 139)
patch size: [128 128 128]
steps (x, y, and z): [[0, 16], [0, 39], [0, 11]]
number of tiles: 8
using precomputed Gaussian
prediction done
inference done. Now waiting for the segmentation export to finish...
force_separate_z: None interpolation order: 1
no resampling necessary
WARNING! Cannot run postprocessing because the postprocessing file is missing. Make sure to run consolidate_folds in the output folder of the model first!
The folder you need to run this in is /datos/work/rnavgon/nnUNet_trained_models/nnUNet/3d_fullres/Task082_BraTS2020/nnUNetTrainerV2__nnUNetPlansv2.1

**Comment by FabianIsensee** [comment]
`nnUNet_print_available_pretrained_models`

> Task082_BraTS2020
Brain tumor segmentation challenge 2020 (BraTS)
Segmentation targets are 0: background, 1: edema, 2: enhancing tumor, 3: necrosis
Input modalities are 0: T1, 1: T1ce, 2: T2, 3: FLAIR (MRI images)
Also see https://www.med.upenn.edu/cbica/brats2020/

**Comment by FabianIsensee** [comment]
also see here

https://github.com/MIC-DKFZ/nnUNet/blob/cd9cb633e14e5d27aec43ea21c958449437c99b2/nnunet/dataset_conversion/Task082_BraTS_2020.py#L663

**Comment by rafaloz** [comment]
Thank you very much!
