### ISSUE TITLE
How to add HD95 score while training?

### ISSUE THREAD

**Issue by JustcallmeTuner** [MIC-DKFZ/nnUNet#79]
Dear @FabianIsensee :
    Thanks for this great repository, it  has helped me a lot! And I want to add and print hd95 while training the nnUNet model(I have found hd95 in metrics.py and evaluator.py), please tell me how to modify the code. 

Best,
Tuner

**Comment by FabianIsensee** [comment]
Hi, glad to hear you like the repo. I don't think it is a good idea to include hd95 during training. Unlike dice it cannot be computed on the GPU AND computation generally takes very long. This will cause validation to run basically forever. I suggest you let the training finish and enable the hd95 metric in the evaluator.
Best,
Fabian

**Comment by JustcallmeTuner** [comment]
I am sorry not expressing my true demand. I would like to display hd95 after every training epoch ，but don't know how to do it. Loking forward to your reply~

**Comment by FabianIsensee** [comment]
Hi,
this is what I meant as well. Have a loot at run_online_evaluation of the nnUNetTrainer. HD95 is not a good candidate to be integrated there because:

1. it cannot run on GPU (run_online_evaluation computed dice on GPU)
2. This is not a real validation. I only evaluate patches, not entire patients. So everything, including the Dice value, is going to be inaccurate
3. HD95 takes too long to compute. It would make your training run much longer


If you really want to integrate it, run_online_evaluation is where it needs to be done. You will also need to create class variables to track the hd95

Best,
Fabian

**Comment by JustcallmeTuner** [comment]
Thanks very much , I  have got it. And I'll close this question , 3ks again~
Best,
Tuner
