### ISSUE TITLE
Dice collapses during training

### ISSUE THREAD

**Issue by thomsonn** [MIC-DKFZ/nnUNet#812]
### Description
I have a segmentation task with a rare class. While training the lowres model, the Dice frequently collapses to zero after several hundred epochs. I previously trained a lowres model on the same dataset using a different CT convolution kernel. The same issue occurred infrequently enough that I could train a model by restarting, but it now consistently happens every time. The fullres model is working fine.
### Screenshots
![progress](https://user-images.githubusercontent.com/23429340/136882651-b6495fbe-0fa3-4e3c-bc10-ab6a07c81127.png)
### Research
I wondered if the data loader might be [sampling low resolution batches not containing any foreground voxels](https://github.com/MIC-DKFZ/nnUNet/blob/904c9c2a0546b155b341ea044f7a5aea81c55013/nnunet/training/dataloading/dataset_loading.py#L303-L316) if `class_locations` were computed from full resolution images. However I see that you are correctly preprocessing the lowres and fullres images separately, so I'm stumped.

**Comment by numanai** [comment]
@FabianIsensee Thank you for sharing the solution. I faced the same issue and by following your suggestion, it worked. Please can you help in understanding the reason behind it?. Thank You

**Comment by thomsonn** [comment]
No, I didn't understand it either.

**Comment by Mushtaqml** [comment]
Thank You, @thomsonn for the response. I will wait then to hear from @FabianIsensee

**Comment by FabianIsensee** [comment]
Hey, sorry I am completely overburdened at the moment with other things - keep in mind that I am just a guy and not a whole company. Time I can put aside for support is quite limited :-/ I wish it was different.
Anyhow.
I am not sure what exactly causes this problem. The current working hypothesis is that the implementation of the 'smooth' parameter in the Dice loss is wrong:
[`dc = nominator / (denominator + 1e-8)`](https://github.com/MIC-DKFZ/nnUNet/blob/d0ba941a8a8996dca3ac36afc34988bafbc575a1/nnunet/training/loss_functions/dice_loss.py#L183)
The 1e-8 should probably not be there and it should use clip instead. No idea why this causes a problem with the default smooth of 1e-5 and does not cause problems with smooth=0. 
The decrease in loss is the result of some class no longer being predicted, and a class being rather rare. + sample Dice. Hard to explain and complicated, but hopefully fixed with the next iteration of nnU-Net I am planning :-)

**Comment by numanai** [comment]
Thank you @FabianIsensee  for the response, indeed it is a bit complicated. I wish you best of luck with your work :)
