### ISSUE TITLE
Questions about the Cascade stage.

### ISSUE THREAD

**Issue by benefree** [MIC-DKFZ/nnUNet#854]
Hello Fabien, I already read the papers, but I still don't know  about the 3d cascade stage. I understood that the 3d cascade stage consists of two stages: low resolution U-Net and full resolutionU-Net, used the ouput of the first U-Net (lowres) as an extra input for the second U-Net(fullres) to proceed with the training.

![Q1](https://user-images.githubusercontent.com/71970610/141978779-43571fe9-1780-464b-bdeb-907369151a33.png)

However, if you look at the cascade picture in the paper, there is a cropping part between stages 1 and 2.

1. What is the role of cropping here? Are you cropping the foreground part from the lowres division result and using it as an input to fullres?
 
2. I wonder how the lowres(stage1) and fullres(stage2) steps are connected. Can you point me to the location of the code that shows how the result of lowres is used in the fullres network?

3.  I want to know what input data is used in fullres. Can you point me the location of the code that gets the input data used for training the cascade fullres network? I've seen the nnUNetTrainerV2_CascadeFullRes.py file, but I couldn't find it.

**Comment by FabianIsensee** [comment]
1. cropping is always random-ish (33% of samples have guaranteed foreground in them, just like on regular 3d_fullres and 3d_lowres training). 
2. a) 3d_lowres does predictions for the next stage after the training is completed: https://github.com/MIC-DKFZ/nnUNet/blob/96d44c2fc1ce5e18da4cd54bf52882047c37982e/nnunet/run/run_training.py#L195. b) cascade trainer looks for those predictions https://github.com/MIC-DKFZ/nnUNet/blob/96d44c2fc1ce5e18da4cd54bf52882047c37982e/nnunet/training/network_training/nnUNetTrainerV2_CascadeFullRes.py#L51
3. nnUNet_preprocessed/TASK/nnUNetData_plans_v2.1_stage1 (same as 3d_fullres)

cropping between the stages is necessary because the fullres part of the cascade cannot process entire images at once

**Comment by jihoon3327** [comment]
@FabianIsensee Does cropping size equal fullres patch size??

**Comment by jihoon3327** [comment]
@FabianIsensee Does cropping size equal patch size??

**Comment by FabianIsensee** [comment]
yes and no. Initial crops are larger so that we can rotate/scale them without getting border problems. The inital crops are then later cropped to the patch size
