### ISSUE TITLE
Clean-up scripts for data

### ISSUE THREAD

**Issue by paul-reiners** [MIC-DKFZ/nnUNet#864]
This is a question, not an 'issue'.

Are there any sample clean-up scripts available for cleaning up data after a model has been trained?  For example, I imagine the folder for a task in the `nnUNet_raw_data_base/nnUNet_raw_data/` folder can be safely deleted.  Are there other data that can be deleted while still retaining the ability to run inference for a given model?

**Comment by FabianIsensee** [comment]
Hi, there is no cleanup script. But once you generated the preprocessed you can delete the raw data in nnUNet_raw_data and nnUNet_cropped_data.
Important! If you are planning to keep one copy of the raw data my recommendation would be to delete the dataset in nnUNet_cropped_data, NOT nnUNet_raw_data because cropped can be generated from raw but not the other way around
