### ISSUE TITLE
Why is the border padding value (-1)?

### ISSUE THREAD

**Issue by jchen42703** [MIC-DKFZ/nnUNet#88]
I noticed that `border_val_seg=-1` for the default data augmentations and `cval_seg=-1` for `resample_patient`. This makes `RemoveLabelTransform(-1, 0)` necessary as part of the training/validation transforms. I was just wondering why not have them = 0? Wouldn't that eliminate the need to `RemoveLabelTransform(-1, 0)`? Is there some sort of significance/nuance that I'm missing here? 
Thanks

**Comment by FabianIsensee** [comment]
This is entangled with cropping. All images are cropped to the nonzero region. This is important for datasets like BraTS. The nonzero mask is encoded in the segmentation as -1. If cropping reduced the image size on the training cases, the normalization is different (mean and std are computed only on the nonzero region). In this case we need to remember where the zero values in the data were so that we can restore them after running through data augmentation (we only want to augment the nonzero region and reset the zero region to zeros). Since data is padded with 0, the segmentation must be padded with -1. Hope this is clear.
Best,
Fabian

**Comment by jchen42703** [comment]
Makes sense! Thank you!
