### ISSUE TITLE
how to change cuda:0 to cuda 1

### ISSUE THREAD

**Issue by timehasspeed** [MIC-DKFZ/nnUNet#89]
hi @FabianIsensee :
 thanks for sharing ~ . i got trouble in changing the gpu , i need to use cuda:1 but i can`t find where to  change the code .
best wishes

**Comment by FabianIsensee** [comment]
Hi,
run python like this:

`CUDA_VISIBLE_DEVICES=1 python my_file.py`

CUDA_VISIBLE_DEVICES is the best way to select what GPU the code is supposed to run on. It will still say gpu 0 but that is because it appears to the python prcess as if there was only one gpu in the  system. Verfiy what GPU it is running on with nvidia-smi
Best,
Fabian

**Comment by timehasspeed** [comment]
sorry to boher you again
i run this python file , and there are two cards in my server .but still got gpu 0
![image](https://user-images.githubusercontent.com/38032376/68672629-f7d96000-058c-11ea-8e64-aafc31f21c35.png)

**Comment by timehasspeed** [comment]
![git](https://user-images.githubusercontent.com/38032376/68672848-7209e480-058d-11ea-9f20-7c1bdfca1739.png)

**Comment by FabianIsensee** [comment]
`CUDA_VISIBLE_DEVICES=1 python WHATEVER_YOUR_COMMAND_IS
`
not

`python WHATEVER_YOUR_COMMAND_IS`

Best,
Fabian

**Comment by timehasspeed** [comment]
thank you . i got it ！
