### ISSUE TITLE
Does nnunet set a limit for RAM usage, and could this cause slow epoch times?

### ISSUE THREAD

**Issue by davidkvcs** [MIC-DKFZ/nnUNet#912]
Hi

My system never uses more than 14 GB RAM during training of 3dfullres model on a local dataset, even though 4x32GB is installed. Don't know if that's relevant, but after about half  an hour my SWAP memory fills up completely. Epoch times much slower than I would expect. I wonder, if this limited RAM-usage could have anything to do with an nnunet setup, or if you think it is almost certainly some local work station issue? And if the limited RAM-usage could be the cause of the unexpectedly slow epoch times?

Added additional details to this question below, and can of course forward more, if that helps. 

Thank you in advance!

_______________________________

Additional details:
I train on an in-house data (training data is approx 800 PET-CT cases with size approx 175x512x512 in each case) preprocessed using nnUNet_plan_and_preprocess I get unusually long epoch times, especially when training 3d_fullres.
I ran all the Heart and Prostate benchmarks from expected_epoch_times.md. In all cases I get expected epoch-times somewhere between the A100 and V100 systems with GPU being around 90-100% utilized most of the time, CPU's used a lot as expected and no seeming I/O issues.

With my local PET-CT dataset however, GPU only peaks to 100% rarely, and is at 0-1% most of the time, CPU's are mostly unused (high waiting times and mostly idle). An epoch typically lasts 1200-2000 seconds. 

My machine is a recently purchased Bizon G3000 with 12-Core 3.50 GHz Intel Core i9-10920X with 128 GB memory and 1x NVIDIA RTX A6000 48 GB graphics card. Only 500 GB storage (500 GB PCI-E NVMe SSD), so the dataset is located on a network drive. However, I have not seen this storage limitation to be the cause of I/O problems with any other test cases.

Your guide points to the fact that I have some sort of I/O problem, so I am also looking into this (currently awaiting delivery of additional local SSD storage).

**Comment by FabianIsensee** [comment]
Hi,
this is most likely an I/O problem due to the dataset being located on a network drive. You would at least need a SATA SSD (500MB/s) to run that properly. Given that you are using a workstation your ethernet is probably 1 or 2.5Gbit = 128 or 256MB/s at best.
The reason you are not seeing this I/O bottleneck with the other datasets is because they are small. Your system will cache the entire datasets in its RAM and thus no longer read from the network drive. Your PET-CT is too large to be cached.
Best,
Fabian

**Comment by FabianIsensee** [comment]
ah and don't let yourself be fooled by RAM utilization. When you look at htop, the cached stuff is part of the yellow-ish bars and not reported as 'used' RAM because it can be freed up instantaneously if another program needs it:
![image](https://user-images.githubusercontent.com/11302164/149342368-4fd95238-d23f-45a3-83a2-a8f8b177bc44.png)

Best,
Fabian

**Comment by davidkvcs** [comment]
Hi -- Just a quick update om this: Upgrading storage to local nvme ssd resulted in about15-20-fold increase in training speed. 
There is still some smaller bottleneck (GPU not utilized 80-100% all the time, but reaches 0% for a a few seconds every 5-7 seconds or so), so might look into further optimization later, but for now, this is fast enough for our purposes. Thanks for the support!

**Comment by FabianIsensee** [comment]
Glad to hear things work smoothly now!
