### ISSUE TITLE
How to add other metrics to progress.png and log

### ISSUE THREAD

**Issue by Tunaaaaa** [MIC-DKFZ/nnUNet#937]
I'd like to use Hausdorff loss to finetune the model, so I need to have a look of the progress of HD and other metrics. How to add them to the log and progress.png ? 
Besides, can I add metrics to tensorboard during training?
Thank you very much~

**Comment by FabianIsensee** [comment]
Hey so the progress.png plot itsnt based on real validation steps. Using the Dice there is already sketchy, Hausdorff would be even worse. If I were you I would use the nnUNetTrainerV2_fullEvals trainer. It runs actual evaluations at the end of each epoch (warning: this could take a long time). It is written for Brats, so you may need to update the code according to your task. Insert your metric computation (dice, HD) instead of `evaluate_regions`, make validate return your metrics. You can then use the metrics in on_epoch_end to generate a plot.
Best,
Fabian

**Comment by Tunaaaaa** [comment]
Hi Fabian,
    It helps a lot. Thank you very much!!

Best 
Junyu
