### ISSUE TITLE
2D better than 3D fullres

### ISSUE THREAD

**Issue by yilei-wu** [MIC-DKFZ/nnUNet#949]
I have two datasets regarding the same type of task and ran nnUNet on both of them;
For dataset A (public), 3D full resolution solution is slightly better than the 2D solution. 
For dataset B (private), 2D solution outperform the 3D solution by around 8% dice score. (70% v.s. 62%)

I am not sure if it could be an indication of something wrong with my dataset B? The sanity check of nnunet data processing did not prompt me error but I am just feel it very uncommon since most of experiments listed in the supplemental material of the nnunet paper are seemed to achieve better performance with 3D solution. 

To put it in a more concise way:
Under what circumstance that 2D UNet may outperform 3D UNet ?

Thank you :)

**Comment by FabianIsensee** [comment]
There was an old version of nnunet where this could happen (like years old, nothing recent) but we have since fixed this problem. On 3D datasets, the 3D configurations always work better or equally well as the 2D config. I don't know why this could be different for your dataset and I cannot really tell you what's going on without taking a look at the data

**Comment by chrisrapson** [comment]
If 3D configurations are always better than 2D, why do the instructions still say to run the 2D training? Isn't that a waste of GPU cycles?

**Comment by FabianIsensee** [comment]
@chrisrapson correct! Running all nnU-Net configurations is only really needed for users who don't know much about it (yet). Once you get a feeling for the datasets you will know what you'll need to run and what you can omit. For most 3D datasets I never run the 2D config.
Best,
Fabian
